/**
 * tGameJobChange.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameJobChange
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	data: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	view(a: any, b: any): any
	/**
	* Unknown
	*/
	viewOne(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	enableJobChange(a: any): any
}
