/**
 * tGameAdventurerGuild.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameAdventurerGuild
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	questMaxNum: any
	/**
	* Unknown
	*/
	nextCreateTime: any
	/**
	* Unknown
	*/
	quests: any
	/**
	* Unknown
	*/
	attackedList: any
	/**
	* Unknown
	*/
	iconInfo: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initSaveData(): any
	/**
	* Unknown
	*/
	getSaveData(): any
	/**
	* Unknown
	*/
	setSaveData(a: any): any
	/**
	* Unknown
	*/
	deleteReceivedQuest(a: any): any
	/**
	* Unknown
	*/
	getCharactorQuests(a: any): any
	/**
	* Unknown
	*/
	removeCharactor(a: any): any
	/**
	* Unknown
	*/
	removeMap(a: any): any
	/**
	* Unknown
	*/
	getTownQuestTarget(a: any): any
	/**
	* Unknown
	*/
	getTownQuestTargetFromMapId(a: any): any
	/**
	* Unknown
	*/
	createTownQuests(a: any): any
	/**
	* Unknown
	*/
	getQuestFreeCharactors(a: any): any
	/**
	* Unknown
	*/
	createTownQuest(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	createTownJikeidanQuest(a: any, b: any): any
	/**
	* Unknown
	*/
	createTownQuest_1(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	createTownQuest_2(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	createTownQuest_3(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	createTownQuest_4(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	createTownQuest_4_field(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	createTownQuest_5(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	createTownQuest_6(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	createTownQuest_7(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	createTownQuest_8(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	createTownQuest_9(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	createTownQuest_10(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	createTownQuest_11(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	createTownQuest_12(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	createTownQuest_13(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	createTownQuest_14(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	createTownQuest_15(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	getQuestSentence(a: any, b: any): any
	/**
	* Unknown
	*/
	getQuestSentence_1(a: any, b: any): any
	/**
	* Unknown
	*/
	getQuestSentence_2(a: any, b: any): any
	/**
	* Unknown
	*/
	getQuestSentence_3(a: any, b: any): any
	/**
	* Unknown
	*/
	getQuestSentence_4(a: any, b: any): any
	/**
	* Unknown
	*/
	getQuestSentence_4_field(a: any, b: any): any
	/**
	* Unknown
	*/
	getQuestSentence_5(a: any, b: any): any
	/**
	* Unknown
	*/
	getQuestSentence_6(a: any, b: any): any
	/**
	* Unknown
	*/
	getQuestSentence_7(a: any, b: any): any
	/**
	* Unknown
	*/
	getQuestSentence_8(a: any, b: any): any
	/**
	* Unknown
	*/
	getQuestSentence_9(a: any, b: any): any
	/**
	* Unknown
	*/
	getQuestSentence_10(a: any, b: any): any
	/**
	* Unknown
	*/
	getQuestSentence_11(a: any, b: any): any
	/**
	* Unknown
	*/
	getQuestSentence_12(a: any, b: any): any
	/**
	* Unknown
	*/
	getQuestSentence_13(a: any, b: any): any
	/**
	* Unknown
	*/
	getQuestSentence_14(a: any, b: any): any
	/**
	* Unknown
	*/
	getQuestSentence_15(a: any, b: any): any
	/**
	* Unknown
	*/
	setMyTown(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getQuestRewordMessage(a: any): any
	/**
	* Unknown
	*/
	addReceived(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	initReceived_1(a: any, b: any): any
	/**
	* Unknown
	*/
	initReceived_2(a: any, b: any): any
	/**
	* Unknown
	*/
	initReceived_3(a: any, b: any): any
	/**
	* Unknown
	*/
	initReceived_4(a: any, b: any): any
	/**
	* Unknown
	*/
	initReceived_5(a: any, b: any): any
	/**
	* Unknown
	*/
	initReceived_6(a: any, b: any): any
	/**
	* Unknown
	*/
	initReceived_7(a: any, b: any): any
	/**
	* Unknown
	*/
	initReceived_8(a: any, b: any): any
	/**
	* Unknown
	*/
	initReceived_9(a: any, b: any): any
	/**
	* Unknown
	*/
	initReceived_10(a: any, b: any): any
	/**
	* Unknown
	*/
	initReceived_11(a: any, b: any): any
	/**
	* Unknown
	*/
	initReceived_12(a: any, b: any): any
	/**
	* Unknown
	*/
	initReceived_13(a: any, b: any): any
	/**
	* Unknown
	*/
	initReceived_14(a: any, b: any): any
	/**
	* Unknown
	*/
	initReceived_15(a: any, b: any): any
	/**
	* Unknown
	*/
	finishQuest(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	failureQuest(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	clearQuestData(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	checkTimeOver(a: any): any
	/**
	* Unknown
	*/
	getTowns(a: any): any
	/**
	* Unknown
	*/
	getTownsFromPosition(a: any, b: any): any
	/**
	* Unknown
	*/
	getAffectAnswer(a: any): any
	/**
	* Unknown
	*/
	affectAnswer(a: any): any
	/**
	* Unknown
	*/
	affectAnswer_2(a: any, b: any): any
	/**
	* Unknown
	*/
	affectAnswer_3(a: any, b: any): any
	/**
	* Unknown
	*/
	affectAnswer_9(a: any, b: any): any
	/**
	* Unknown
	*/
	getTargetItem(a: any): any
	/**
	* Unknown
	*/
	getTargetQuestItem(a: any): any
	/**
	* Unknown
	*/
	createID(): any
	/**
	* Unknown
	*/
	searchReceivedQuest(a: any): any
	/**
	* Unknown
	*/
	getFieldObjectToQuest1Name(a: any): any
	/**
	* Unknown
	*/
	getQuestFinishFameExp(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getQuestFinishGaeExp(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	changeMapEvent(a: any): any
	/**
	* Unknown
	*/
	createQuestRank(): any
	/**
	* Unknown
	*/
	createQuestItem_2(a: any): any
	/**
	* Unknown
	*/
	createQuestItem_3(a: any): any
	/**
	* Unknown
	*/
	updateAttackedList(): any
	/**
	* Unknown
	*/
	getAttackedList(): any
	/**
	* Unknown
	*/
	calQuestIconData(): any
	/**
	* Unknown
	*/
	addQuestSentenceCommon(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	isSokuji(a: any): any
	/**
	* Unknown
	*/
	actSokuji(a: any): any
	/**
	* Unknown
	*/
	createQuestTargetType(a: any, b: any): any
	/**
	* Unknown
	*/
	guildpointkau(a: any, b: any): any
	/**
	* Unknown
	*/
	guildpointkau2(a: any, b: any): any
	/**
	* Unknown
	*/
	getGuildPointBottomData(): any
}
