/**
 * tGameGameClear.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameGameClear
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	checkClearFlg(): any
	/**
	* Unknown
	*/
	checkFirst(): any
	/**
	* Unknown
	*/
	setClearDungeon(): any
	/**
	* Unknown
	*/
	setClearEtc(): any
}
