/**
 * tGameChipsetResource.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameChipsetResource
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	chipsetLink: any
	/**
	* Unknown
	*/
	chipsetData: any
	/**
	* Unknown
	*/
	counters: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	getUseData(a: any): any
	/**
	* Unknown
	*/
	getUseDataFromMap(a: any): any
	/**
	* Unknown
	*/
	loadImage(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	loadLinkJson(a: any): any
	/**
	* Unknown
	*/
	loadAllImage(a: any): any
	/**
	* Unknown
	*/
	getChipsetData(a: any): any
	/**
	* Unknown
	*/
	getMyAdventurerChipData(a: any): any
	/**
	* Unknown
	*/
	loadOverwrite(a: any): any
	/**
	* Unknown
	*/
	loadOverwrite__chipset_chara(a: any): any
}
