/**
 * tGameEventFrame.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameEventFrame
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	hiddenCanvases: any
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	view(a: any, b: any): any
	/**
	* Unknown
	*/
	addCharactor(a: any): any
	/**
	* Unknown
	*/
	removeCharactor(a: any): any
	/**
	* Unknown
	*/
	destory(a: any): any
	/**
	* Unknown
	*/
	viewMap(a: any, b: any): any
	/**
	* Unknown
	*/
	backMap(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	backGotoMap(a: any, b: any): any
	/**
	* Unknown
	*/
	backMapAct(a: any): any
	/**
	* Unknown
	*/
	backGotoMapAct(a: any): any
	/**
	* Unknown
	*/
	viewOutAnimation(a: any, b: any): any
	/**
	* Unknown
	*/
	viewInAnimation(a: any, b: any): any
}
