/**
 * tGameGod.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameGod
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	viewMapWarikomi(a: any): any
	/**
	* Unknown
	*/
	getCastleEventData(a: any): any
	/**
	* Unknown
	*/
	viewMapWarikomiAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	viewMapWarikomiAction_godtoujou(a: any, b: any): any
	/**
	* Unknown
	*/
	viewMapWarikomiAction_godcastle1(a: any, b: any): any
	/**
	* Unknown
	*/
	viewMapWarikomiAction_godcastle2(a: any, b: any): any
	/**
	* Unknown
	*/
	viewMapWarikomiAction_godfaith1(a: any, b: any): any
	/**
	* Unknown
	*/
	viewMapWarikomiAction_godmonderu(a: any, b: any): any
	/**
	* Unknown
	*/
	viewMapWarikomiAction_monderu2(a: any, b: any): any
	/**
	* Unknown
	*/
	viewMapWarikomiAction_clear3towers(a: any, b: any): any
	/**
	* Unknown
	*/
	viewMapWarikomiAction_megamigekihafield(a: any, b: any): any
	/**
	* Unknown
	*/
	viewMapWarikomiAction_god2_tojo(a: any, b: any): any
	/**
	* Unknown
	*/
	viewMapWarikomiAction_god2_junbiok(a: any, b: any): any
	/**
	* Unknown
	*/
	viewMapWarikomiAction_god2_lasthe(a: any, b: any): any
	/**
	* Unknown
	*/
	checkOverwriteBossFloor(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	talkDungeonBoss(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	viewMap(a: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_nuebattlechecktimeout(a: any, b: any): any
	/**
	* Unknown
	*/
	autoCreateExpand(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	getDungeonRandomPos(a: any): any
}
