/**
 * tGameStorage.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameStorage
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	data: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initSaveData(): any
	/**
	* Unknown
	*/
	getSaveData(): any
	/**
	* Unknown
	*/
	setSaveData(a: any): any
	/**
	* Unknown
	*/
	createStorage(a: any): any
	/**
	* Unknown
	*/
	viewWindow(a: any): any
	/**
	* Unknown
	*/
	initTalk(a: any): any
	/**
	* Unknown
	*/
	viewDefault(a: any, b: any): any
	/**
	* Unknown
	*/
	viewArrears(a: any): any
	/**
	* Unknown
	*/
	pay(): any
	/**
	* Unknown
	*/
	getItemNum(): any
	/**
	* Unknown
	*/
	payArrearsMoney(a: any): any
	/**
	* Unknown
	*/
	addItem(a: any): any
	/**
	* Unknown
	*/
	removeItem(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	inCharaItem(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	outCharaItem(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	outOkuItem(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	azukeru(a: any): any
	/**
	* Unknown
	*/
	toridasu(a: any, b: any): any
	/**
	* Unknown
	*/
	selectItem(a: any): any
	/**
	* Unknown
	*/
	help(a: any): any
	/**
	* Unknown
	*/
	maoupay(a: any, b: any): any
	/**
	* Unknown
	*/
	fusaiShometsu(): any
	/**
	* Unknown
	*/
	sortItems(a: any): any
	/**
	* Unknown
	*/
	setSortType(a: any, b: any): any
	/**
	* Unknown
	*/
	setSortTypeWindow(a: any, b: any): any
	/**
	* Unknown
	*/
	fixKakeraGroup(): any
	/**
	* Unknown
	*/
	searchItemId(a: any, b: any): any
	/**
	* Unknown
	*/
	getPrice(): any
}
