/**
 * tGameMyShop.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameMyShop
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	maxItemNum: any
	/**
	* Unknown
	*/
	kakuchoMoney: any
	/**
	* Unknown
	*/
	tesuryoMax: any
	/**
	* Unknown
	*/
	data: any
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initSaveData(): any
	/**
	* Unknown
	*/
	getSaveData(): any
	/**
	* Unknown
	*/
	setSaveData(a: any): any
	/**
	* Unknown
	*/
	isViewSelectColumn(): any
	/**
	* Unknown
	*/
	getSelectColumn(): any
	/**
	* Unknown
	*/
	view(a: any, b: any): any
	/**
	* Unknown
	*/
	viewIn1(a: any): any
	/**
	* Unknown
	*/
	viewIn2(a: any, b: any): any
	/**
	* Unknown
	*/
	inItem(a: any): any
	/**
	* Unknown
	*/
	viewOut1(a: any): any
	/**
	* Unknown
	*/
	viewOut2(a: any): any
	/**
	* Unknown
	*/
	outItem(a: any): any
	/**
	* Unknown
	*/
	removeItem(a: any, b: any): any
	/**
	* Unknown
	*/
	kakucho(a: any): any
	/**
	* Unknown
	*/
	buy(): any
	/**
	* Unknown
	*/
	getTesuryoRate(a: any, b: any): any
}
