/**
 * tGameWindows.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameWindows
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	isEnabled: any
	/**
	* Unknown
	*/
	type: any
	/**
	* Unknown
	*/
	callObj: any
	/**
	* Unknown
	*/
	callBacks: any
	/**
	* Unknown
	*/
	bSteamBigPictureMode: any
	/**
	* Unknown
	*/
	initLoad: any
	/**
	* Unknown
	*/
	pageClose: any
	/**
	* Unknown
	*/
	pageReload: any
	/**
	* Unknown
	*/
	getSaveList: any
	/**
	* Unknown
	*/
	getSaveData: any
	/**
	* Unknown
	*/
	setSaveData: any
	/**
	* Unknown
	*/
	deleteSaveData: any
	/**
	* Unknown
	*/
	changeContentSize: any
	/**
	* Unknown
	*/
	sendJsSysError: any
	/**
	* Unknown
	*/
	exportMyAdventurerCharactor: any
	/**
	* Unknown
	*/
	importMyAdventurerCharactor: any
	/**
	* Unknown
	*/
	importMyAdventurerCharactor2FromData0: any
	/**
	* Unknown
	*/
	importMyAdventurerCharactor2FromBase64Data0: any
	/**
	* Unknown
	*/
	overwriteMyAdventurerCharactorData: any
	/**
	* Unknown
	*/
	sendIsTr: any
	/**
	* Unknown
	*/
	exportMpaData: any
	/**
	* Unknown
	*/
	importMapData: any
	/**
	* Unknown
	*/
	closeGame: any
	/**
	* Unknown
	*/
	activeAchievement: any
	/**
	* Unknown
	*/
	initMydata: any
	/**
	* Unknown
	*/
	getControllerType: any
	/**
	* Unknown
	*/
	isSteamInBigPictureMode: any
	/**
	* Unknown
	*/
	overwriteMydataFace: any
	/**
	* Unknown
	*/
	overwriteMydataChipset: any
	/**
	* Unknown
	*/
	overwriteMydataTalk: any
	/**
	* Unknown
	*/
	getExportMyAdventurerCharactorK1upData: any
	/**
	* Unknown
	*/
	getTargetImageBase64: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	pageClose(): any
	/**
	* Unknown
	*/
	pageReload(): any
	/**
	* Unknown
	*/
	getSaveList(a: any): any
	/**
	* Unknown
	*/
	getSaveData(a: any, b: any): any
	/**
	* Unknown
	*/
	setSaveData(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	deleteSaveData(a: any, b: any): any
	/**
	* Unknown
	*/
	changeContentSize(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	sendJsSysError(a: any, b: any): any
	/**
	* Unknown
	*/
	exportMyAdventurerCharactor(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	getExportMyAdventurerCharactorK1upData(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	importMyAdventurerCharactor(a: any): any
	/**
	* Unknown
	*/
	importMyAdventurerCharactor2FromBase64Data0(a: any, b: any): any
	/**
	* Unknown
	*/
	overwriteMyAdventurerCharactorData(a: any, b: any, c: any, d: any, e: any, f: any): any
	/**
	* Unknown
	*/
	sendIsTr(): any
	/**
	* Unknown
	*/
	exportMpaData(a: any, b: any): any
	/**
	* Unknown
	*/
	importMapData(a: any): any
	/**
	* Unknown
	*/
	closeGame(): any
	/**
	* Unknown
	*/
	activeAchievement(a: any, b: any): any
	/**
	* Unknown
	*/
	initMydata(a: any): any
	/**
	* Unknown
	*/
	getControllerType(a: any): any
	/**
	* Unknown
	*/
	isSteamInBigPictureMode(a: any): any
	/**
	* Unknown
	*/
	overwriteMydataFace(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	overwriteMydataItem(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	overwriteMydataChipset(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	overwriteMydataTalk(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	getTargetImageBase64(a: any, b: any): any
	/**
	* Unknown
	*/
	openBrowser(a: any, b: any): any
	/**
	* Unknown
	*/
	outputFile(a: any, b: any): any
	/**
	* Unknown
	*/
	openDirectory(a: any, b: any): any
}
