/**
 * tGameCharactorRuleWindow.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameCharactorRuleWindow
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	viewCharactorRuleWindow(a: any, b: any): any
	/**
	* Unknown
	*/
	viewCharactorRule2Window(a: any, b: any): any
	/**
	* Unknown
	*/
	viewCharactorRule3Window(a: any, b: any): any
	/**
	* Unknown
	*/
	getCharaRule_townruleKantei(a: any): any
	/**
	* Unknown
	*/
	getCharaRule_townruleNoroikeshi(a: any): any
	/**
	* Unknown
	*/
	getCharaRule_townruleRustrepair(a: any): any
	/**
	* Unknown
	*/
	getCharaRule_usenoroiitem(a: any): any
}
