/**
 * tGameMagicalGirl.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameMagicalGirl
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	isWarikomi(a: any, b: any): any
	/**
	* Unknown
	*/
	actWarikomi(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_magicalgirlgekiha(a: any, b: any): any
	/**
	* Unknown
	*/
	okoru(a: any): any
	/**
	* Unknown
	*/
	viewMap(a: any): any
	/**
	* Unknown
	*/
	getMoriPositions(): any
}
