/**
 * tGameNoriai.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameNoriai
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	selectMokutekichi(a: any): any
	/**
	* Unknown
	*/
	moveEvent(a: any): any
	/**
	* Unknown
	*/
	start(a: any): any
	/**
	* Unknown
	*/
	createRestMap(): any
	/**
	* Unknown
	*/
	restFinish(a: any): any
	/**
	* Unknown
	*/
	yatouFinish(a: any): any
	/**
	* Unknown
	*/
	addTime(a: any): any
	/**
	* Unknown
	*/
	createYatouMap(): any
	/**
	* Unknown
	*/
	finishYatou(a: any): any
	/**
	* Unknown
	*/
	removeNoriaiBashaObject(a: any): any
}
