/**
 * tGameSkillActionBook.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameSkillActionBook
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	randomTargets: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	createRandomItem(a: any): any
	/**
	* Unknown
	*/
	createItem(a: any): any
}
