/**
 * tGameMatsuri.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameMatsuri
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	tryMap(a: any): any
	/**
	* Unknown
	*/
	createMap(): any
	/**
	* Unknown
	*/
	getMapId(): any
	/**
	* Unknown
	*/
	createMap_act(a: any): any
	/**
	* Unknown
	*/
	addCharactor(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_creatematsuri(a: any, b: any): any
}
