/**
 * tGameShokuzaifukuro.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameShokuzaifukuro
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	data: any
	/**
	* Unknown
	*/
	types: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initSaveData(): any
	/**
	* Unknown
	*/
	getSaveData(): any
	/**
	* Unknown
	*/
	setSaveData(a: any): any
	/**
	* Unknown
	*/
	addItem(a: any): any
	/**
	* Unknown
	*/
	removeItem(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	inCharaItem(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	outCharaItem(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	enableAzukeru(a: any): any
	/**
	* Unknown
	*/
	azukeru(a: any): any
	/**
	* Unknown
	*/
	toridasu(a: any, b: any): any
	/**
	* Unknown
	*/
	view(a: any, b: any): any
	/**
	* Unknown
	*/
	getShokuzaiShunoMikanteiItems(): any
	/**
	* Unknown
	*/
	getShokuzaiShunoNoroiItems(): any
	/**
	* Unknown
	*/
	kanteiItem(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	noroikeshiItem(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	searchItemId(a: any, b: any): any
}
