/**
 * tGameFullscreenLog.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameFullscreenLog
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	callBack: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	view(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_dispose(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_frame(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_draw(a: any): any
	/**
	* Unknown
	*/
	drawCanvas(): any
}
