/**
 * tGameShortCut.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameShortCut
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	maxNum: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	getShortCut(): any
	/**
	* Unknown
	*/
	setShortCutIdx(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	getShortCutIdx(a: any, b: any): any
	/**
	* Unknown
	*/
	actionShortCutIdx(a: any, b: any): any
}
