/**
 * tGameCharactor.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameCharactor
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	charas: any
	/**
	* Unknown
	*/
	teams: any
	/**
	* Unknown
	*/
	levelFraction: any
	/**
	* Unknown
	*/
	limit: any
	/**
	* Unknown
	*/
	talkResetAddTime: any
	/**
	* Unknown
	*/
	playerTeamMemberLimitNum: any
	/**
	* Unknown
	*/
	maxDamage: any
	/**
	* Unknown
	*/
	conditionStatusPairs: any
	/**
	* Unknown
	*/
	statusMinMax: any
	/**
	* Unknown
	*/
	ctypeObjects: any
	/**
	* Unknown
	*/
	findPoliceConditions: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	getToPlayerRelation(a: any): any
	/**
	* Unknown
	*/
	getTeamRelation(a: any, b: any): any
	/**
	* Unknown
	*/
	getBattleCharactors(a: any, b: any): any
	/**
	* Unknown
	*/
	updateTeamRelation(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	addTeam(a: any): any
	/**
	* Unknown
	*/
	addTeamMember(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	restoreEventTeamMembers(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	removeEventTeamMember(a: any): any
	/**
	* Unknown
	*/
	removeTeamMember(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	removeTeam(a: any): any
	/**
	* Unknown
	*/
	removeTeam0(a: any): any
	/**
	* Unknown
	*/
	resetWaitTimeStorage(): any
	/**
	* Unknown
	*/
	addTargetCharactor(a: any): any
	/**
	* Unknown
	*/
	addMobCharactor(a: any): any
	/**
	* Unknown
	*/
	addAdventurerCharactor(a: any): any
	/**
	* Unknown
	*/
	addPeddlerCharactor(a: any): any
	/**
	* Unknown
	*/
	addPoliceCharactor(a: any): any
	/**
	* Unknown
	*/
	addSlavetraderCharactor(a: any): any
	/**
	* Unknown
	*/
	addSojiyaCharactor(a: any): any
	/**
	* Unknown
	*/
	addNoriaiBashaCharactor(a: any): any
	/**
	* Unknown
	*/
	addCriminalCharactor(a: any): any
	/**
	* Unknown
	*/
	addEnemy(a: any): any
	/**
	* Unknown
	*/
	addAnimal(a: any): any
	/**
	* Unknown
	*/
	getSlaveCharactor(a: any): any
	/**
	* Unknown
	*/
	addCharactor(a: any, b: any): any
	/**
	* Unknown
	*/
	deleteCharactor(a: any, b: any): any
	/**
	* Unknown
	*/
	getMapCharactors(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	isCantActCondition(a: any): any
	/**
	* Unknown
	*/
	affect(a: any): any
	/**
	* Unknown
	*/
	actCondition(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	musicAction(a: any): any
	/**
	* Unknown
	*/
	action(a: any): any
	/**
	* Unknown
	*/
	action2(a: any, b: any): any
	/**
	* Unknown
	*/
	action_forceAction(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	action_teamTsuibi(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	action_mapAction(a: any, b: any): any
	/**
	* Unknown
	*/
	action_targetMove(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	action_targetAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	action_playerAffect(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	action_playerAffectKojiki(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	action_randomMove(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	action_mudaAction(a: any, b: any): any
	/**
	* Unknown
	*/
	action_cure(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	action_support(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	action_curecdt(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	action_kuufuku(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	action_noroikeshi(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	action_kantei(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	action_sokuji(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	action_actionData(a: any, b: any, c: any, d: any, e: any, f: any): any
	/**
	* Unknown
	*/
	action_moveTekiseiKyori(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	action_actionA(a: any, b: any): any
	/**
	* Unknown
	*/
	action_actionP(a: any, b: any): any
	/**
	* Unknown
	*/
	action_fovPoliceBattle(a: any, b: any): any
	/**
	* Unknown
	*/
	action_actionN(a: any, b: any): any
	/**
	* Unknown
	*/
	action_actionL(a: any, b: any): any
	/**
	* Unknown
	*/
	action_buyItem(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	action_open(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getLevelDivision(a: any): any
	/**
	* Unknown
	*/
	getPercent(a: any): any
	/**
	* Unknown
	*/
	getLevel(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	addExp2(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	addExp(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	loseExp(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	addMoney(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	removeItem(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	addItem(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	addSkill(a: any, b: any, c: any, d: any, e: any, f: any): any
	/**
	* Unknown
	*/
	addSkillAction(a: any, b: any, c: any, d: any, e: any, f: any): any
	/**
	* Unknown
	*/
	removeSkillAction(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	giftItem(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	giftItem2(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	giftItem3(a: any, b: any, c: any, d: any, e: any, f: any): any
	/**
	* Unknown
	*/
	buyItem(a: any): any
	/**
	* Unknown
	*/
	buySkill(a: any): any
	/**
	* Unknown
	*/
	sellItem(a: any): any
	/**
	* Unknown
	*/
	okuItem(a: any, b: any, c: any, d: any, e: any, f: any, g: any, h: any): any
	/**
	* Unknown
	*/
	okuItemOkuLog(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	getPickupItemMaxNum(a: any, b: any): any
	/**
	* Unknown
	*/
	pickupItem(a: any): any
	/**
	* Unknown
	*/
	addFriendship(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	addFame(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	addGae(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	updateTalkResetTime(a: any): any
	/**
	* Unknown
	*/
	checkTalkFsp(a: any, b: any): any
	/**
	* Unknown
	*/
	initSaveData(): any
	/**
	* Unknown
	*/
	getSaveData(): any
	/**
	* Unknown
	*/
	setSaveData(a: any): any
	/**
	* Unknown
	*/
	setPlayerPosition(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	joinPlayerTeam(a: any, b: any, c: any, d: any, e: any, f: any): any
	/**
	* Unknown
	*/
	setFukidashi(a: any): any
	/**
	* Unknown
	*/
	getFspTalkTarget(a: any): any
	/**
	* Unknown
	*/
	setFukidashiTalk(a: any, b: any): any
	/**
	* Unknown
	*/
	setCommonFukidashiTalk(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	setEmotion(a: any): any
	/**
	* Unknown
	*/
	removeEmotion(a: any): any
	/**
	* Unknown
	*/
	removeEquip(a: any): any
	/**
	* Unknown
	*/
	setEquipFromItem(a: any): any
	/**
	* Unknown
	*/
	setStatus(a: any): any
	/**
	* Unknown
	*/
	checkAttack(a: any, b: any): any
	/**
	* Unknown
	*/
	attack(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	longAttack(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	usePlayerSkillAction(a: any, b: any, c: any, d: any, e: any, f: any): any
	/**
	* Unknown
	*/
	isCanAction(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	isCanUseItem(a: any, b: any): any
	/**
	* Unknown
	*/
	isCanUseSkillAction(a: any, b: any): any
	/**
	* Unknown
	*/
	getSkillActionCost2(a: any, b: any): any
	/**
	* Unknown
	*/
	getSkillActionCost(a: any, b: any): any
	/**
	* Unknown
	*/
	getCdtBukizokusei(a: any): any
	/**
	* Unknown
	*/
	getAttackSkillAction(a: any): any
	/**
	* Unknown
	*/
	getLongAttackSkillAction(a: any): any
	/**
	* Unknown
	*/
	useSkillAction(a: any, b: any, c: any, d: any, e: any, f: any, g: any, h: any, i: any, j: any, k: any, l: any): any
	/**
	* Unknown
	*/
	nonBattleAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getAptitudeDistance(a: any): any
	/**
	* Unknown
	*/
	battleAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	setBattleTarget(a: any): any
	/**
	* Unknown
	*/
	takeSkillAction(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	getKnockDownExp(a: any, b: any): any
	/**
	* Unknown
	*/
	isEnableTarget(a: any): any
	/**
	* Unknown
	*/
	setCondition(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	removeAllCondition(a: any): any
	/**
	* Unknown
	*/
	removeCondition(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	setAdventurerMap(a: any): any
	/**
	* Unknown
	*/
	usedItem2(a: any, b: any): any
	/**
	* Unknown
	*/
	usedItem(a: any, b: any): any
	/**
	* Unknown
	*/
	getCharactorFsp(a: any, b: any): any
	/**
	* Unknown
	*/
	getCharactorFame(a: any, b: any): any
	/**
	* Unknown
	*/
	getCharactorGae(a: any, b: any): any
	/**
	* Unknown
	*/
	addValue(a: any): any
	/**
	* Unknown
	*/
	getItemMaxSpace(a: any): any
	/**
	* Unknown
	*/
	getItemSpace(a: any): any
	/**
	* Unknown
	*/
	getCharactorMoney(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	searchCharactorItem(a: any, b: any): any
	/**
	* Unknown
	*/
	setCharactorPosition(a: any, b: any): any
	/**
	* Unknown
	*/
	addLogEffects(a: any, b: any): any
	/**
	* Unknown
	*/
	getWalkChipset(a: any, b: any): any
	/**
	* Unknown
	*/
	turnToCharactor(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	isDeath(a: any): any
	/**
	* Unknown
	*/
	setMoveChipset(a: any): any
	/**
	* Unknown
	*/
	setTrunToDirection(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	setTurnToPosition(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	stepCharactor(a: any): any
	/**
	* Unknown
	*/
	getCantMoveIdx(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	dropItem(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	calDamage(a: any): any
	/**
	* Unknown
	*/
	autoCure(a: any): any
	/**
	* Unknown
	*/
	getExp(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	setLevelUpGrowthStatus(a: any, b: any): any
	/**
	* Unknown
	*/
	addSkillActionExp(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getFriendshipExp(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getFameExp(a: any, b: any): any
	/**
	* Unknown
	*/
	getGaeExp(a: any, b: any): any
	/**
	* Unknown
	*/
	tryNpcJoinTeam(a: any): any
	/**
	* Unknown
	*/
	requestJoinTeam(a: any, b: any): any
	/**
	* Unknown
	*/
	requestJoinMyMember(a: any, b: any): any
	/**
	* Unknown
	*/
	requestJoinMyMember2(a: any, b: any): any
	/**
	* Unknown
	*/
	isBlockRequestJoin(a: any): any
	/**
	* Unknown
	*/
	requestRemoveMyTown(a: any, b: any): any
	/**
	* Unknown
	*/
	requestRemoveMyTeam(a: any, b: any): any
	/**
	* Unknown
	*/
	requestMyTownBefore(a: any, b: any): any
	/**
	* Unknown
	*/
	requestMyTown(a: any, b: any): any
	/**
	* Unknown
	*/
	isEnableRemovePlayerTeam(a: any): any
	/**
	* Unknown
	*/
	removePlayerTeam_checkQuest(a: any): any
	/**
	* Unknown
	*/
	removePlayerTeam(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	playerBodilyFunctions(a: any): any
	/**
	* Unknown
	*/
	sleepPlayer(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	deathAction(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	deleteChangeMapCharactor(): any
	/**
	* Unknown
	*/
	timeRevival(a: any): any
	/**
	* Unknown
	*/
	eventRevival(a: any): any
	/**
	* Unknown
	*/
	clearMoveMapCondition(a: any): any
	/**
	* Unknown
	*/
	setHomeMap(a: any, b: any): any
	/**
	* Unknown
	*/
	gotoHospital(a: any, b: any): any
	/**
	* Unknown
	*/
	setPoliceMap(a: any): any
	/**
	* Unknown
	*/
	setSojiyaMap(a: any): any
	/**
	* Unknown
	*/
	setNoriaiBashaMap(a: any): any
	/**
	* Unknown
	*/
	setPeddlerMap(a: any): any
	/**
	* Unknown
	*/
	setCriminalMap(a: any): any
	/**
	* Unknown
	*/
	setMyTownCharaMap(a: any): any
	/**
	* Unknown
	*/
	setSubTownCharaMap(a: any): any
	/**
	* Unknown
	*/
	isFreeCharactor(a: any, b: any): any
	/**
	* Unknown
	*/
	getFreeCharactors(): any
	/**
	* Unknown
	*/
	judgeCondition(a: any, b: any, c: any, d: any, e: any, f: any, g: any): any
	/**
	* Unknown
	*/
	getConditionDefaultValue(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	removeOnemapTeam(a: any): any
	/**
	* Unknown
	*/
	addDeathAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	clearDeathAction(a: any): any
	/**
	* Unknown
	*/
	inFlg(a: any, b: any): any
	/**
	* Unknown
	*/
	setFlg(a: any, b: any): any
	/**
	* Unknown
	*/
	removeFlg(a: any, b: any): any
	/**
	* Unknown
	*/
	kantei(a: any): any
	/**
	* Unknown
	*/
	kantei2(a: any): any
	/**
	* Unknown
	*/
	kantei3(a: any): any
	/**
	* Unknown
	*/
	requestEnchantment(a: any, b: any): any
	/**
	* Unknown
	*/
	requestRustRepair(a: any): any
	/**
	* Unknown
	*/
	stayInn(a: any): any
	/**
	* Unknown
	*/
	allkantei(a: any): any
	/**
	* Unknown
	*/
	allnoroikeshi(a: any): any
	/**
	* Unknown
	*/
	noroiwotoku(a: any): any
	/**
	* Unknown
	*/
	noroiwotoku2(a: any): any
	/**
	* Unknown
	*/
	noroiwotoku3(a: any): any
	/**
	* Unknown
	*/
	noroiwotoku4(a: any): any
	/**
	* Unknown
	*/
	fukkatusaseru(a: any): any
	/**
	* Unknown
	*/
	hospitalmeibomiru(a: any): any
	/**
	* Unknown
	*/
	isPlayerTeamMemberSpaceNum(): any
	/**
	* Unknown
	*/
	isPlayerTeamMemberFull(a: any): any
	/**
	* Unknown
	*/
	isMyMemberFull(a: any): any
	/**
	* Unknown
	*/
	getHitRatio(a: any): any
	/**
	* Unknown
	*/
	getCriticalRatio(a: any): any
	/**
	* Unknown
	*/
	setActionData(a: any, b: any): any
	/**
	* Unknown
	*/
	autoEquipment(a: any): any
	/**
	* Unknown
	*/
	pickupItemFoot(a: any, b: any): any
	/**
	* Unknown
	*/
	isFavoriteItem(a: any, b: any): any
	/**
	* Unknown
	*/
	teleportNearCharactor(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getOverlookMessage(a: any): any
	/**
	* Unknown
	*/
	setEventChara(a: any): any
	/**
	* Unknown
	*/
	removeEventChara(a: any): any
	/**
	* Unknown
	*/
	requestKoibito(a: any, b: any): any
	/**
	* Unknown
	*/
	requestKoibito_act(a: any, b: any): any
	/**
	* Unknown
	*/
	requestKekkon(a: any, b: any): any
	/**
	* Unknown
	*/
	requestKekkon_act(a: any, b: any): any
	/**
	* Unknown
	*/
	viewChestOpenMessage(a: any): any
	/**
	* Unknown
	*/
	npcGrowth(a: any): any
	/**
	* Unknown
	*/
	removeNpcCharactor(): any
	/**
	* Unknown
	*/
	fillNpcCharactor(): any
	/**
	* Unknown
	*/
	criminalBattle(a: any): any
	/**
	* Unknown
	*/
	jobChange(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getTalkHomeMap(a: any): any
	/**
	* Unknown
	*/
	getHomeMap(a: any): any
	/**
	* Unknown
	*/
	getMemberSumSkillLevel(a: any, b: any): any
	/**
	* Unknown
	*/
	fovBattlePolice(): any
	/**
	* Unknown
	*/
	pushCharaPosition(a: any, b: any, c: any, d: any, e: any, f: any): any
	/**
	* Unknown
	*/
	getCharactorCantPositionIdx(a: any, b: any): any
	/**
	* Unknown
	*/
	nakanaorishiyo(a: any, b: any): any
	/**
	* Unknown
	*/
	getAttackDamageAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getAttackKaihiAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	isDyingValue(a: any, b: any): any
	/**
	* Unknown
	*/
	updatePoliceRelation(): any
	/**
	* Unknown
	*/
	setFovPoliceBattle(a: any): any
	/**
	* Unknown
	*/
	getCharactorItemInfo(a: any, b: any): any
	/**
	* Unknown
	*/
	getShopMinMoney(a: any): any
	/**
	* Unknown
	*/
	updateAllEquipment(): any
	/**
	* Unknown
	*/
	setAutoEquipment(a: any): any
	/**
	* Unknown
	*/
	getJakutaiLevel(a: any): any
	/**
	* Unknown
	*/
	isExpHakiMask(a: any): any
	/**
	* Unknown
	*/
	getJobRandomActionSkill(a: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_criminalaround(a: any, b: any): any
	/**
	* Unknown
	*/
	convertName(a: any): any
	/**
	* Unknown
	*/
	getActionMyMembers(a: any, b: any): any
	/**
	* Unknown
	*/
	getShopRankScale(a: any): any
	/**
	* Unknown
	*/
	updateShopRankScale(a: any, b: any): any
	/**
	* Unknown
	*/
	addFirstMoney(a: any, b: any): any
	/**
	* Unknown
	*/
	addFirstItem(a: any): any
	/**
	* Unknown
	*/
	isStealCondition(a: any): any
	/**
	* Unknown
	*/
	isEnableNakanaori(a: any): any
	/**
	* Unknown
	*/
	addFriendshipLog(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	addFameLog(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	addGaeLog(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	addLevelUpBonus(a: any): any
	/**
	* Unknown
	*/
	specialAffect(a: any, b: any): any
	/**
	* Unknown
	*/
	actEventTeamRemove(a: any): any
	/**
	* Unknown
	*/
	checkEventTeamRemove(a: any, b: any): any
	/**
	* Unknown
	*/
	removeLongStayCharactors(a: any): any
	/**
	* Unknown
	*/
	getTargetItem(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getTargetItem2(a: any, b: any): any
	/**
	* Unknown
	*/
	chikakuShisetsu(a: any, b: any): any
	/**
	* Unknown
	*/
	timeHungry(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	viewNpcJoinTeamMessage(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	setAroundPosition(a: any, b: any): any
	/**
	* Unknown
	*/
	isAkumu(a: any): any
	/**
	* Unknown
	*/
	viewLineEffect(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getFukkatsuPrice(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getFukkatsuPrice2(a: any): any
	/**
	* Unknown
	*/
	setZentaishiji(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	specialAffect_bokenshadoko(a: any, b: any): any
	/**
	* Unknown
	*/
	getActionTurnShohi(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	setRemoveNonActionConditionValue(a: any): any
	/**
	* Unknown
	*/
	checkAroundBed(a: any): any
	/**
	* Unknown
	*/
	addHojuCharactor(a: any, b: any): any
	/**
	* Unknown
	*/
	getCharactorObjects(a: any, b: any): any
	/**
	* Unknown
	*/
	hoju(a: any): any
	/**
	* Unknown
	*/
	hojuCriminalCharactor(): any
	/**
	* Unknown
	*/
	shojiItemKasane(a: any, b: any): any
	/**
	* Unknown
	*/
	kojikiKaiwa(a: any, b: any): any
	/**
	* Unknown
	*/
	ketugoHogyokus(a: any): any
	/**
	* Unknown
	*/
	recipeAutoUse(a: any): any
	/**
	* Unknown
	*/
	getMytownNokoriNum(): any
	/**
	* Unknown
	*/
	getMySumNum(): any
	/**
	* Unknown
	*/
	getMymemberiNum(a: any): any
	/**
	* Unknown
	*/
	skillNarau(a: any): any
	/**
	* Unknown
	*/
	allBattleReset(): any
	/**
	* Unknown
	*/
	setPlayerItemRecord(a: any): any
	/**
	* Unknown
	*/
	setPlayerItemRecordFromEquipment(): any
	/**
	* Unknown
	*/
	changeHmapType(a: any): any
	/**
	* Unknown
	*/
	getHajimarinochiKanteiPrice(): any
	/**
	* Unknown
	*/
	removeNakamaFuyouDeathAction(a: any): any
	/**
	* Unknown
	*/
	fixDoreiMonsterMoney(): any
	/**
	* Unknown
	*/
	fixSkillActionID(): any
	/**
	* Unknown
	*/
	addZokuseiFuyo(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	viewMap_fix(a: any): any
	/**
	* Unknown
	*/
	fixTeam(): any
	/**
	* Unknown
	*/
	clearFukidashiAll(): any
	/**
	* Unknown
	*/
	checkReuseItem(a: any, b: any): any
	/**
	* Unknown
	*/
	getReuseItemMinutes(a: any, b: any): any
	/**
	* Unknown
	*/
	setReuseItem(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	refreshItemReuseTime(): any
	/**
	* Unknown
	*/
	getRyouriFromFukuro(a: any): any
	/**
	* Unknown
	*/
	ryourifukurokure(a: any): any
	/**
	* Unknown
	*/
	shokuzaifukurokure(a: any): any
	/**
	* Unknown
	*/
	autoTownFacilityUse(a: any): any
	/**
	* Unknown
	*/
	autoTownFacilityUse_kantei(a: any): any
	/**
	* Unknown
	*/
	autoTownFacilityUse_noroikeshi(a: any): any
	/**
	* Unknown
	*/
	autoTownFacilityUse_rustrepair(a: any): any
	/**
	* Unknown
	*/
	autoTownFacilityUse__targetChara(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getEquipmentIds(a: any, b: any): any
	/**
	* Unknown
	*/
	birthdayLog(a: any): any
	/**
	* Unknown
	*/
	setKinenbi(a: any, b: any): any
	/**
	* Unknown
	*/
	checkCdtTarget(a: any): any
	/**
	* Unknown
	*/
	addItemWithFukuro(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	viewAddItemLog(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	npcShiokuri(a: any): any
	/**
	* Unknown
	*/
	getItemSpaceMaxNum(a: any, b: any): any
}
