/**
 * tGameWeather.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameWeather
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	weatherData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	updateWeather(a: any, b: any): any
	/**
	* Unknown
	*/
	setWeather(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	viewWeather(): any
	/**
	* Unknown
	*/
	viewTargetWeather(a: any): any
}
