/**
 * tGameBazaarGenerator.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameBazaarGenerator
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	nextUpdateTime: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	tryMap(a: any): any
	/**
	* Unknown
	*/
	createMap(): any
	/**
	* Unknown
	*/
	oneActionFinishAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_createbazaar(a: any, b: any): any
}
