/**
 * tGameGuide.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameGuide
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	checkChangeMapGuideEvent(): any
	/**
	* Unknown
	*/
	checkMoveGuideEvent(a: any): any
	/**
	* Unknown
	*/
	checkAffectObjectGuideEvent(a: any, b: any): any
	/**
	* Unknown
	*/
	checkElfdungeonJoinEvent(a: any, b: any): any
	/**
	* Unknown
	*/
	checkMagicalGirlAuEvent(a: any, b: any): any
	/**
	* Unknown
	*/
	changeMapEvent(a: any, b: any): any
	/**
	* Unknown
	*/
	gameStartEvent(a: any, b: any): any
	/**
	* Unknown
	*/
	checkMaouShutsugenEvent(a: any, b: any): any
}
