/**
 * tGameFieldMaterial.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameFieldMaterial
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	autoCreate(a: any): any
	/**
	* Unknown
	*/
	getName(a: any, b: any): any
	/**
	* Unknown
	*/
	createSpot(a: any, b: any): any
	/**
	* Unknown
	*/
	convertData(a: any): any
	/**
	* Unknown
	*/
	createSaikutsujo(a: any, b: any): any
	/**
	* Unknown
	*/
	createSaishujo(a: any, b: any): any
	/**
	* Unknown
	*/
	createHoujou(a: any, b: any): any
	/**
	* Unknown
	*/
	isEnableSetObject(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getFreeSpace(a: any): any
	/**
	* Unknown
	*/
	inMaterial(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	changeMap(a: any): any
}
