/**
 * tGameCastleGenerator.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameCastleGenerator
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	createCastleWithLoad(a: any, b: any): any
	/**
	* Unknown
	*/
	createCastle(a: any, b: any): any
	/**
	* Unknown
	*/
	actionPattern(a: any): any
	/**
	* Unknown
	*/
	updateActionPattern(a: any): any
	/**
	* Unknown
	*/
	actionPatternOne(a: any): any
}
