/**
 * tGameBlacksmith.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameBlacksmith
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	maxNum: any
	/**
	* Unknown
	*/
	gineikesshoMaxNum: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	getMaterialMaxNum(a: any): any
	/**
	* Unknown
	*/
	getGineikesshoMaxNum(): any
	/**
	* Unknown
	*/
	getSoukesshoNeedNum(): any
	/**
	* Unknown
	*/
	create(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	createMember(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	selectMaterial(a: any, b: any): any
	/**
	* Unknown
	*/
	selectEquipmentType2(a: any): any
	/**
	* Unknown
	*/
	selectSoukessho(a: any): any
	/**
	* Unknown
	*/
	getSuccessRate(a: any): any
	/**
	* Unknown
	*/
	getMaxRank(): any
	/**
	* Unknown
	*/
	actBlacksmith(): any
	/**
	* Unknown
	*/
	blacksmithResult(a: any, b: any): any
	/**
	* Unknown
	*/
	getExp(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	bunkai(a: any, b: any): any
	/**
	* Unknown
	*/
	getSoukesshoItems(): any
	/**
	* Unknown
	*/
	getGineikesshoItems(): any
}
