/**
 * tGameTitle.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameTitle
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	images: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	viewTitle(): any
	/**
	* Unknown
	*/
	drawBackground(a: any, b: any): any
	/**
	* Unknown
	*/
	drawBackground_etc(a: any, b: any): any
	/**
	* Unknown
	*/
	drawBackground_title(a: any): any
}
