/**
 * tGameMapCharaCommonAction.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameMapCharaCommonAction
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	actionBeforePatternOne(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	actionPatternOne(a: any, b: any): any
	/**
	* Unknown
	*/
	viewMapActionPatternOne(a: any, b: any): any
	/**
	* Unknown
	*/
	actionPatternType_counter(a: any, b: any): any
	/**
	* Unknown
	*/
	viewMapActionPatternOne_myhome(a: any, b: any): any
	/**
	* Unknown
	*/
	viewMapActionPatternOne_counter(a: any, b: any): any
	/**
	* Unknown
	*/
	viewMapActionPatternOne_bed(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	viewMapActionPatternOne_chair(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	viewMapActionPatternOne_diningchair(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	viewMapActionPatternOne_farm(a: any, b: any): any
	/**
	* Unknown
	*/
	viewMapActionPatternOne_goei(a: any, b: any): any
	/**
	* Unknown
	*/
	viewMapActionPatternOne_kenkyu(a: any, b: any): any
	/**
	* Unknown
	*/
	viewMapActionPatternOne_imushitsu(a: any, b: any): any
	/**
	* Unknown
	*/
	actionPatternType_myhome(a: any, b: any): any
	/**
	* Unknown
	*/
	actionPatternType_myhomecenter(a: any, b: any): any
	/**
	* Unknown
	*/
	actionPatternType_kenkyu(a: any, b: any): any
	/**
	* Unknown
	*/
	actionPatternType_imushitsu(a: any, b: any): any
	/**
	* Unknown
	*/
	actionPatternType_animalwood(a: any, b: any): any
	/**
	* Unknown
	*/
	actionPatternType_bed(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	actionPatternType_noriaibasha(a: any, b: any): any
	/**
	* Unknown
	*/
	actionPatternType_aroundtypedataposition(a: any, b: any): any
	/**
	* Unknown
	*/
	actionPatternType_randompoint(a: any, b: any): any
	/**
	* Unknown
	*/
	actionPatternType_chair(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	actionPatternType_diningchair(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	actionPatternType_adventureguild(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	actionPatternType_goei(a: any, b: any): any
	/**
	* Unknown
	*/
	moveTargetPoint(a: any, b: any): any
	/**
	* Unknown
	*/
	actionPatternBeforeAction(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	actionPatternType_farm(a: any, b: any): any
	/**
	* Unknown
	*/
	updateActionPattern(a: any): any
	/**
	* Unknown
	*/
	getCharactorObjects(a: any): any
	/**
	* Unknown
	*/
	selectEatTarget(a: any, b: any): any
	/**
	* Unknown
	*/
	selectRandomTarget(a: any, b: any): any
	/**
	* Unknown
	*/
	selectRandomNightTarget(a: any, b: any): any
	/**
	* Unknown
	*/
	selectBedTarget(a: any, b: any): any
	/**
	* Unknown
	*/
	updateActionPattern_default(a: any, b: any): any
	/**
	* Unknown
	*/
	updateActionPattern_outmain(a: any, b: any): any
	/**
	* Unknown
	*/
	updateActionPattern_shop(a: any, b: any): any
	/**
	* Unknown
	*/
	updateActionPattern_shop2(a: any, b: any): any
	/**
	* Unknown
	*/
	updateActionPattern_housemain(a: any, b: any): any
	/**
	* Unknown
	*/
	updateActionPattern_farmor(a: any, b: any): any
	/**
	* Unknown
	*/
	updateActionPattern_king(a: any, b: any): any
	/**
	* Unknown
	*/
	updateActionPattern_goei(a: any, b: any): any
	/**
	* Unknown
	*/
	updateActionPattern_kenkyu(a: any, b: any): any
	/**
	* Unknown
	*/
	updateActionPattern_isha(a: any, b: any): any
	/**
	* Unknown
	*/
	updateActionPattern_animalwood(a: any, b: any): any
	/**
	* Unknown
	*/
	updateActionPattern_tougijo_uketsuke(a: any, b: any): any
	/**
	* Unknown
	*/
	updateActionPattern_casino_dealer(a: any, b: any): any
	/**
	* Unknown
	*/
	updateActionPattern_casino_chonin(a: any, b: any): any
	/**
	* Unknown
	*/
	updateActionPattern_noriai(a: any, b: any): any
	/**
	* Unknown
	*/
	updateActionPattern_shitaiasari(a: any, b: any): any
	/**
	* Unknown
	*/
	addTimeAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	viewMapFixPosition(a: any): any
	/**
	* Unknown
	*/
	okiru(a: any, b: any): any
}
