/**
 * tGameFaith.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameFaith
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	addTownFaith(a: any): any
	/**
	* Unknown
	*/
	getRivalCharas(): any
	/**
	* Unknown
	*/
	getBossChara(a: any): any
	/**
	* Unknown
	*/
	maoushutsugen(a: any, b: any): any
	/**
	* Unknown
	*/
	updateMaouAction(): any
	/**
	* Unknown
	*/
	updateMaouTimeOver(a: any, b: any): any
	/**
	* Unknown
	*/
	updateRivalAction(): any
	/**
	* Unknown
	*/
	updateTownsConnect(a: any): any
	/**
	* Unknown
	*/
	isHendo(): any
	/**
	* Unknown
	*/
	createFaithLowDungeon(): any
	/**
	* Unknown
	*/
	createStartFloor(a: any, b: any): any
	/**
	* Unknown
	*/
	createHaikaiFloor(a: any, b: any): any
	/**
	* Unknown
	*/
	createSuiminFloor(a: any, b: any): any
	/**
	* Unknown
	*/
	setRandomHone(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_faithlowhaikaichikai(a: any, b: any): any
	/**
	* Unknown
	*/
	viewShuki(a: any, b: any): any
	/**
	* Unknown
	*/
	createOtasuke(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	createBossFloor(a: any, b: any): any
	/**
	* Unknown
	*/
	bossEvent(a: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_faithlowbossgekiha(a: any, b: any): any
	/**
	* Unknown
	*/
	removeHone(): any
	/**
	* Unknown
	*/
	clearTargetFaith(a: any, b: any): any
	/**
	* Unknown
	*/
	shukka(a: any): any
	/**
	* Unknown
	*/
	viewFaithHoshu(a: any, b: any): any
}
