/**
 * tGameStoryWindow.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameStoryWindow
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	fontSize: any
	/**
	* Unknown
	*/
	textSpace: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	clearCanvas(): any
	/**
	* Unknown
	*/
	view(a: any): any
	/**
	* Unknown
	*/
	drawDetail(a: any): any
	/**
	* Unknown
	*/
	getDetail_god(): any
	/**
	* Unknown
	*/
	getDetail_megamiev(): any
	/**
	* Unknown
	*/
	getDetail_kaichoev(): any
	/**
	* Unknown
	*/
	getDetail_yushaev(): any
	/**
	* Unknown
	*/
	getDetail_sozaiev(): any
	/**
	* Unknown
	*/
	getDetail_kingev(): any
	/**
	* Unknown
	*/
	getDetail_kenkyuevent(): any
	/**
	* Unknown
	*/
	getDetail_elfevent(): any
	/**
	* Unknown
	*/
	getDetail_magicalgirl(): any
	/**
	* Unknown
	*/
	getDetail_guildev(): any
	/**
	* Unknown
	*/
	getDetail_gakushaev(): any
	/**
	* Unknown
	*/
	getDetail_byoinev(): any
	/**
	* Unknown
	*/
	getDetail_yureigl(): any
	/**
	* Unknown
	*/
	getDetail_oujiev(): any
	/**
	* Unknown
	*/
	getDetail_tenshokudn(): any
	/**
	* Unknown
	*/
	getDetail_oshitsuke(): any
	/**
	* Unknown
	*/
	getDetail_jashin(): any
}
