/**
 * tGameMapResource.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameMapResource
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	mapData: any
	/**
	* Unknown
	*/
	mapBaseData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	loadData(a: any, b: any): any
	/**
	* Unknown
	*/
	loadDataWithMyData(a: any, b: any): any
	/**
	* Unknown
	*/
	getDrawMapData(a: any, b: any): any
}
