/**
 * tGameMyTownRuleWindow.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameMyTownRuleWindow
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	isEnableCharactor(a: any): any
	/**
	* Unknown
	*/
	viewCharactorRuleWindow(a: any, b: any): any
}
