/**
 * tGameEtcTown.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameEtcTown
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	actionPattern(a: any): any
	/**
	* Unknown
	*/
	updateActionPattern(a: any): any
	/**
	* Unknown
	*/
	actionPatternOne(a: any): any
}
