/**
 * tGameTableTalk.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameTableTalk
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	view(a: any, b: any): any
	/**
	* Unknown
	*/
	viewSelectChara(): any
	/**
	* Unknown
	*/
	talk(a: any): any
	/**
	* Unknown
	*/
	talkStart(a: any): any
}
