/**
 * tGameMaou.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameMaou
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	data: any
	/**
	* Unknown
	*/
	images: any
	/**
	* Unknown
	*/
	tobatsuLvs: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	createMap(a: any, b: any): any
	/**
	* Unknown
	*/
	createAlly(a: any, b: any): any
	/**
	* Unknown
	*/
	setMaou(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	createEnemy(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getMaouMapAll(a: any): any
	/**
	* Unknown
	*/
	getMaouMaps(a: any): any
	/**
	* Unknown
	*/
	getMaouObject(a: any): any
	/**
	* Unknown
	*/
	getMaouBarriers(a: any, b: any): any
	/**
	* Unknown
	*/
	getRandomMaouId(a: any): any
	/**
	* Unknown
	*/
	getPayment(a: any): any
	/**
	* Unknown
	*/
	getNextPaymentTime(a: any): any
	/**
	* Unknown
	*/
	createFieldData(): any
	/**
	* Unknown
	*/
	setTimeOverFaith(a: any, b: any): any
	/**
	* Unknown
	*/
	checkTimeOver(a: any): any
	/**
	* Unknown
	*/
	destroyWorld(a: any, b: any): any
	/**
	* Unknown
	*/
	getFreeCollaborator(a: any): any
	/**
	* Unknown
	*/
	getSetsumei(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getItemSetsumei(a: any): any
	/**
	* Unknown
	*/
	viewAdventureGuildBoard(a: any, b: any): any
	/**
	* Unknown
	*/
	getPayItems(a: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_maougekiha(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_maouteshitashutsugen(a: any, b: any): any
}
