/**
 * tGameFukidashiResource.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameFukidashiResource
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	fukidashiLink: any
	/**
	* Unknown
	*/
	cvs: any
	/**
	* Unknown
	*/
	ctx: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	createFukidashi(a: any): any
}
