/**
 * tGameSelectFovTarget.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameSelectFovTarget
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	modes: any
	/**
	* Unknown
	*/
	mode: any
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	cursor: any
	/**
	* Unknown
	*/
	hiddenCanvases: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	viewSelectTarget(a: any, b: any): any
	/**
	* Unknown
	*/
	setFrameEvent(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_dispose(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_frame(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_draw(a: any): any
	/**
	* Unknown
	*/
	changeTarget(a: any): any
}
