/**
 * tGameExMapData.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameExMapData
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	version: any
	/**
	* Unknown
	*/
	importData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	exportMapData(a: any, b: any): any
	/**
	* Unknown
	*/
	createOutputMapData(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	importMapData(a: any, b: any): any
	/**
	* Unknown
	*/
	clearImportMapDataFile(a: any): any
	/**
	* Unknown
	*/
	selectedImportMapDataFile(a: any): any
	/**
	* Unknown
	*/
	selectedImportMapDataFileCommon(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	exportK1up(a: any, b: any): any
}
