/**
 * tGameHikyo.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameHikyo
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	loadLinkJson(a: any): any
	/**
	* Unknown
	*/
	setHikyoDummyObjects(a: any): any
	/**
	* Unknown
	*/
	setHikyoDummyObjects_act(a: any, b: any): any
	/**
	* Unknown
	*/
	hakken(a: any, b: any): any
	/**
	* Unknown
	*/
	matakita(a: any, b: any): any
	/**
	* Unknown
	*/
	drawHikyo(a: any, b: any): any
}
