/**
 * tGameNw.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameNw
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	isEnabled: any
	/**
	* Unknown
	*/
	callObj: any
	/**
	* Unknown
	*/
	callObj_screen: any
	/**
	* Unknown
	*/
	callBacks: any
	/**
	* Unknown
	*/
	requires: any
	/**
	* Unknown
	*/
	selectFileDatas: any
	/**
	* Unknown
	*/
	currentDir: any
	/**
	* Unknown
	*/
	currentDir2: any
	/**
	* Unknown
	*/
	pwd: any
	/**
	* Unknown
	*/
	myAdvTmpData: any
	/**
	* Unknown
	*/
	greenworks: any
	/**
	* Unknown
	*/
	activeAchievementCache: any
	/**
	* Unknown
	*/
	isInitError: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initError(): any
	/**
	* Unknown
	*/
	refreshWindowsFnc(a: any): any
	/**
	* Unknown
	*/
	loadRequire(a: any): any
	/**
	* Unknown
	*/
	initDir(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	pageClose(): any
	/**
	* Unknown
	*/
	pageReload(): any
	/**
	* Unknown
	*/
	getSaveList(a: any): any
	/**
	* Unknown
	*/
	getSaveData(a: any, b: any): any
	/**
	* Unknown
	*/
	setSaveData(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	setSaveDataBackup(a: any, b: any): any
	/**
	* Unknown
	*/
	deleteSaveData(a: any, b: any): any
	/**
	* Unknown
	*/
	changeContentSize(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	changeContentSize__resize(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	changeContentSize__fullscreen(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	sendJsSysError(a: any, b: any): any
	/**
	* Unknown
	*/
	exportMyAdventurerCharactor(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	getExportMyAdventurerCharactorK1upData(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	importMyAdventurerCharactor(a: any): any
	/**
	* Unknown
	*/
	importMyAdventurerCharactor2FromBase64Data0(a: any, b: any): any
	/**
	* Unknown
	*/
	importMyAdventurerCharactor2FromData0(a: any, b: any): any
	/**
	* Unknown
	*/
	overwriteMyAdventurerCharactorData(a: any, b: any, c: any, d: any, e: any, f: any): any
	/**
	* Unknown
	*/
	sendIsTr(): any
	/**
	* Unknown
	*/
	exportMpaData(a: any, b: any): any
	/**
	* Unknown
	*/
	importMapData(a: any): any
	/**
	* Unknown
	*/
	closeGame(): any
	/**
	* Unknown
	*/
	setSelectFile(a: any): any
	/**
	* Unknown
	*/
	activeAchievement(a: any, b: any): any
	/**
	* Unknown
	*/
	initMydata(a: any): any
	/**
	* Unknown
	*/
	getControllerType(a: any): any
	/**
	* Unknown
	*/
	isSteamInBigPictureMode(a: any): any
	/**
	* Unknown
	*/
	overwriteMydataFace(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	overwriteMydataItem(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	overwriteMydataChipset(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	overwriteMydataTalk(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	getTargetImageBase64(a: any, b: any): any
	/**
	* Unknown
	*/
	openBrowser(a: any, b: any): any
	/**
	* Unknown
	*/
	outputFile(a: any, b: any): any
}
