/**
 * tGameSkillAction.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameSkillAction
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	iconData: any
	/**
	* Unknown
	*/
	askillData: any
	/**
	* Unknown
	*/
	rankMagics: any
	/**
	* Unknown
	*/
	rankPhysics: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	setRankAskills(): any
	/**
	* Unknown
	*/
	setRankAskills2(): any
	/**
	* Unknown
	*/
	getSkillName(a: any): any
	/**
	* Unknown
	*/
	convertSkillData(a: any): any
	/**
	* Unknown
	*/
	getSkillLanges(a: any, b: any): any
	/**
	* Unknown
	*/
	calSkillArea(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	viewEffect(a: any, b: any, c: any, d: any, e: any, f: any, g: any, h: any): any
	/**
	* Unknown
	*/
	getSkillType(a: any): any
	/**
	* Unknown
	*/
	getTakeSkillActionResult(): any
	/**
	* Unknown
	*/
	takeSkillAction_summon(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_summonboss(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_summonanimal(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_battlereset(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_teamonmitsu(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_allkanpa(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_alerm(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_cure(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_rcure(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_removecondition(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_badcondition(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_badcondition2(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_badcondition3(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_badcondition4(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_goodcondition(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_addcounter(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_bukizokusei(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_grantup(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_grantdown(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_grantrateup(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_tetsuya(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_grantratedown(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_cdtdamage(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_mcure(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_mmcure(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_mcureremovecondition(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_mcurebadcondition(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_statusupbadcondition(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_attack(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_food(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_light(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_weatherchange(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_warmeirei(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_warbomb(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_teleport(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_teleport2(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_poschange(a: any, b: any, c: any, d: any, e: any, f: any): any
	/**
	* Unknown
	*/
	takeSkillAction_possekkin(a: any, b: any, c: any, d: any, e: any, f: any): any
	/**
	* Unknown
	*/
	takeSkillAction_poschikaduke(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_chohatsu(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_shugo(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_mitoosenu(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_breaktrap(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_tagayasu(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_farmsodatsu(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_farmoishiku(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_mizumaki(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_seed(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_cookstart(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_chogostart(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_enchantmentstart(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_blacksmithstart(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_equiprankupstart(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_nejitaku(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_agechange(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_fspplus(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_fspminus(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_fspplus2(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_fspminus2(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_statusgrowth(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_statusgrowthlimit(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	createID(): any
	/**
	* Unknown
	*/
	updateSkill(a: any, b: any): any
	/**
	* Unknown
	*/
	createSkill(a: any): any
	/**
	* Unknown
	*/
	getExp(a: any, b: any): any
	/**
	* Unknown
	*/
	takeSkillAction_remote(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_shindou(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_bougen(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_remotebomb(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_statusup(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_statusdown(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_nanimoshinai(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	getDescription(a: any, b: any): any
	/**
	* Unknown
	*/
	takeSkillAction_bakuhatsu(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_bakuhatsu2(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_yubaku(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_bombbakuhatsu(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_music(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_hungry(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_damage(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_curse(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_rust(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_equipreinforce(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_equipkeiryoka(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_equipjuryoka(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_sennotobashi(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_sekkinattack(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_shuryo(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_setreuse(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_poschangeattack(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_haisuiattack(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_mettazashi(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_gaichu(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_nantokaball(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_nantokabomb(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_setsuri(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_shittoattack(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_yumekuiattack(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_noroiattack(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_daichiattack(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_seimeisui(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_wariaidamage(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_randomspd(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_chokasoku(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_jigenyugami(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_pandorabox(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_zentaishiji(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_skillexp(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_randomkantei(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_randomnoroikeshi(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_noroitaiseiplus(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_jakukataiseiplus(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_noroitaiseiminus(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_jakukataiseiminus(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_enemykanyu(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_bomb(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_fukitobasu(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_tosshin(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_createtrap(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_newskill(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_droprandomskill(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_skilllevelup(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_souden(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_henshin(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_hbook(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	takeSkillAction_askillwakuplus(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	shokujiResult(a: any, b: any): any
	/**
	* Unknown
	*/
	getMusicCondition(): any
	/**
	* Unknown
	*/
	getMusicActionCondition(): any
	/**
	* Unknown
	*/
	getScrollCondition(): any
	/**
	* Unknown
	*/
	getMagicCondition(): any
	/**
	* Unknown
	*/
	getActionCondition(): any
	/**
	* Unknown
	*/
	getLevelToRank(a: any, b: any): any
	/**
	* Unknown
	*/
	judgeCreateSkill(a: any): any
	/**
	* Unknown
	*/
	getKeishoRate(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	getVal(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	checkTargetEquipment(a: any, b: any): any
	/**
	* Unknown
	*/
	createItemSkill(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	judgeAttackDamageAction(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	judgeAttackKaihiAction(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	getLuckRate(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	judgeAttackKaihiAction_kaihiToTargetChara(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	judgeAttackDamageAction_toTargetChara(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	judgeAttackDamageAction_toTargetCharaPhysicsLong(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	judgeAttackDamageAction_toTargetCharaElementalCounter(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	judgeAttackDamageAction_toTargetCharaElemental2Counter(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	judgeAttackDamageAction_toMyself(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	judgeAttackDamageAction_toMyselfDying(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	isUseAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getNewSkillLevel(a: any, b: any): any
	/**
	* Unknown
	*/
	updateNantokaBall(a: any): any
	/**
	* Unknown
	*/
	updateNantokaBomb(a: any): any
	/**
	* Unknown
	*/
	useSkillActionBefore(a: any, b: any, c: any, d: any, e: any, f: any, g: any, h: any, i: any, j: any, k: any): any
}
