/**
 * tGameCasino.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameCasino
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	data: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	exCoin(a: any): any
	/**
	* Unknown
	*/
	exItem(a: any, b: any): any
	/**
	* Unknown
	*/
	createExItems(): any
}
