/**
 * tGameHoridashimono.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameHoridashimono
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	nextUpdateTime: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	view(a: any): any
	/**
	* Unknown
	*/
	tryRefresh(a: any): any
	/**
	* Unknown
	*/
	createItem(): any
}
