/**
 * tGameSpecialMap.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameSpecialMap
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	createQuest1Map(a: any, b: any): any
	/**
	* Unknown
	*/
	createQuest9Map(a: any, b: any): any
	/**
	* Unknown
	*/
	createFreeMap(a: any): any
	/**
	* Unknown
	*/
	createFreeMap_act(a: any): any
	/**
	* Unknown
	*/
	setWood(a: any): any
	/**
	* Unknown
	*/
	setStone(a: any): any
	/**
	* Unknown
	*/
	setToboku(a: any): any
	/**
	* Unknown
	*/
	setSaboten(a: any): any
	/**
	* Unknown
	*/
	setKirikabu(a: any): any
	/**
	* Unknown
	*/
	setItem(a: any): any
	/**
	* Unknown
	*/
	getFreeMapStartPosition(a: any, b: any): any
}
