/**
 * tGameTougijo.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameTougijo
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	data: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	gotoBattleMap(a: any, b: any): any
	/**
	* Unknown
	*/
	createMap(): any
	/**
	* Unknown
	*/
	entry(a: any): any
	/**
	* Unknown
	*/
	escapeBattle(a: any): any
	/**
	* Unknown
	*/
	setBackMapData(): any
	/**
	* Unknown
	*/
	setEnemy(a: any, b: any): any
	/**
	* Unknown
	*/
	victoryBattle(a: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_victorybattle(a: any, b: any): any
	/**
	* Unknown
	*/
	getHoshu(a: any, b: any): any
	/**
	* Unknown
	*/
	getRankToLevel(a: any): any
	/**
	* Unknown
	*/
	getRankToMoney(a: any, b: any): any
	/**
	* Unknown
	*/
	updateHoshu(): any
}
