/**
 * tGameLoading.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameLoading
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	targets: any
	/**
	* Unknown
	*/
	objs: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	addLoading(a: any): any
	/**
	* Unknown
	*/
	removeLoading(a: any): any
	/**
	* Unknown
	*/
	viewLoadingError(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getErrorNum(): any
	/**
	* Unknown
	*/
	viewLoading(): any
	/**
	* Unknown
	*/
	hiddenLoading(): any
	/**
	* Unknown
	*/
	viewLoadingErrorFrame(): any
	/**
	* Unknown
	*/
	hiddenLoadingErrorFrame(): any
	/**
	* Unknown
	*/
	retry(): any
}
