/**
 * tGameCreateCharactor.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameCreateCharactor
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	data: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	view(a: any, b: any): any
	/**
	* Unknown
	*/
	changeView(a: any, b: any): any
	/**
	* Unknown
	*/
	viewProfile(): any
	/**
	* Unknown
	*/
	viewProfile2(): any
	/**
	* Unknown
	*/
	viewJob(): any
	/**
	* Unknown
	*/
	viewBonus(): any
	/**
	* Unknown
	*/
	viewConfirm(a: any): any
	/**
	* Unknown
	*/
	updateCharaData(a: any): any
	/**
	* Unknown
	*/
	cancelConfirm(): any
	/**
	* Unknown
	*/
	viewBuyWindow(a: any): any
}
