/**
 * tGameMain.ts
 * Autogenerated by WaahTool v2.1.3 >:3
 */

import { tGameAcn } from "./tGameAcn";
import { tGameAdventurerGuild } from "./tGameAdventurerGuild";
import { tGameAdventurerGuildConfirmWindow } from "./tGameAdventurerGuildConfirmWindow";
import { tGameAdventurerGuildWindow } from "./tGameAdventurerGuildWindow";
import { tGameAffectMap } from "./tGameAffectMap";
import { tGameAkumuDungeon } from "./tGameAkumuDungeon";
import { tGameAllocateStatusWindow } from "./tGameAllocateStatusWindow";
import { tGameAnimalWood } from "./tGameAnimalWood";
import { tGameBaby } from "./tGameBaby";
import { tGameBazaarGenerator } from "./tGameBazaarGenerator";
import { tGameBgmResource } from "./tGameBgmResource";
import { tGameBlacksmith } from "./tGameBlacksmith";
import { tGameButsu } from "./tGameButsu";
import { tGameCalc } from "./tGameCalc";
import { tGameCasino } from "./tGameCasino";
import { tGameCastleGenerator } from "./tGameCastleGenerator";
import { tGameChangeProfile } from "./tGameChangeProfile";
import { tGameCharactor } from "./tGameCharactor";
import { tGameCharactorData } from "./tGameCharactorData";
import { tGameCharactorEquipRuleWindow } from "./tGameCharactorEquipRuleWindow";
import { tGameCharactorRuleWindow } from "./tGameCharactorRuleWindow";
import { tGameChikaMakyo } from "./tGameChikaMakyo";
import { tGameChipsetResource } from "./tGameChipsetResource";
import { tGameCommand } from "./tGameCommand";
import { tGameCooking } from "./tGameCooking";
import { tGameCreateCharactor } from "./tGameCreateCharactor";
import { tGameCreateUniqueCharactor } from "./tGameCreateUniqueCharactor";
import { tGameCreateWindow } from "./tGameCreateWindow";
import { tGameCriminalRouya } from "./tGameCriminalRouya";
import { tGameCriminalWindow } from "./tGameCriminalWindow";
import { tGameDairyQuest } from "./tGameDairyQuest";
import { tGameData } from "./tGameData";
import { tGameDesignedMap } from "./tGameDesignedMap";
import { tGameDialog } from "./tGameDialog";
import { tGameDungeonGenerator } from "./tGameDungeonGenerator";
import { tGameEditMember } from "./tGameEditMember";
import { tGameEffect } from "./tGameEffect";
import { tGameEmotionResource } from "./tGameEmotionResource";
import { tGameEnchantment } from "./tGameEnchantment";
import { tGameEnsei } from "./tGameEnsei";
import { tGameEquipRankup } from "./tGameEquipRankup";
import { tGameEquipmentWindow } from "./tGameEquipmentWindow";
import { tGameEtc } from "./tGameEtc";
import { tGameEtcTown } from "./tGameEtcTown";
import { tGameEvent } from "./tGameEvent";
import { tGameEventAnimation } from "./tGameEventAnimation";
import { tGameEventFrame } from "./tGameEventFrame";
import { tGameExMapData } from "./tGameExMapData";
import { tGameFaceResource } from "./tGameFaceResource";
import { tGameFaith } from "./tGameFaith";
import { tGameFaithWindow } from "./tGameFaithWindow";
import { tGameFarm } from "./tGameFarm";
import { tGameFieldGenerator } from "./tGameFieldGenerator";
import { tGameFieldMaterial } from "./tGameFieldMaterial";
import { tGameFishing } from "./tGameFishing";
import { tGameFukidashiResource } from "./tGameFukidashiResource";
import { tGameFullscreenLog } from "./tGameFullscreenLog";
import { tGameGameClear } from "./tGameGameClear";
import { tGameGameOptionWindow } from "./tGameGameOptionWindow";
import { tGameGameOver } from "./tGameGameOver";
import { tGameGamePad } from "./tGameGamePad";
import { tGameGamePadBase } from "./tGameGamePadBase";
import { tGameGamePadEditor } from "./tGameGamePadEditor";
import { tGameGod } from "./tGameGod";
import { tGameGoodTrap } from "./tGameGoodTrap";
import { tGameGuide } from "./tGameGuide";
import { tGameHelp } from "./tGameHelp";
import { tGameHikitsugi } from "./tGameHikitsugi";
import { tGameHikitsugiNakama } from "./tGameHikitsugiNakama";
import { tGameHikyo } from "./tGameHikyo";
import { tGameHoridashimono } from "./tGameHoridashimono";
import { tGameHyk } from "./tGameHyk";
import { tGameIcon24Resource } from "./tGameIcon24Resource";
import { tGameIconResource } from "./tGameIconResource";
import { tGameIdRecycle } from "./tGameIdRecycle";
import { tGameIkesu } from "./tGameIkesu";
import { tGameItem } from "./tGameItem";
import { tGameItemInfoWindow } from "./tGameItemInfoWindow";
import { tGameItemWindow } from "./tGameItemWindow";
import { tGameJashin } from "./tGameJashin";
import { tGameJinja } from "./tGameJinja";
import { tGameJob } from "./tGameJob";
import { tGameJobChange } from "./tGameJobChange";
import { tGameK1up } from "./tGameK1up";
import { tGameKeyboard } from "./tGameKeyboard";
import { tGameLakeZou } from "./tGameLakeZou";
import { tGameLoading } from "./tGameLoading";
import { tGameLoading2 } from "./tGameLoading2";
import { tGameLog } from "./tGameLog";
import { tGameMagicalGirl } from "./tGameMagicalGirl";
import { tGameMaigo } from "./tGameMaigo";
import { tGameMamonoJisho } from "./tGameMamonoJisho";
import { tGameMaou } from "./tGameMaou";
import { tGameMap } from "./tGameMap";
import { tGameMapCharaCommonAction } from "./tGameMapCharaCommonAction";
import { tGameMapEditor } from "./tGameMapEditor";
import { tGameMapResource } from "./tGameMapResource";
import { tGameMatsuri } from "./tGameMatsuri";
import { tGameMeiro } from "./tGameMeiro";
import { tGameMenu } from "./tGameMenu";
import { tGameMenuShortcutWindow } from "./tGameMenuShortcutWindow";
import { tGameMessageWindow } from "./tGameMessageWindow";
import { tGameMyAdventurerCharactor } from "./tGameMyAdventurerCharactor";
import { tGameMyShop } from "./tGameMyShop";
import { tGameMyTown } from "./tGameMyTown";
import { tGameMyTownMeibo } from "./tGameMyTownMeibo";
import { tGameMyTownRuleWindow } from "./tGameMyTownRuleWindow";
import { tGameNakamaHaken } from "./tGameNakamaHaken";
import { tGameName } from "./tGameName";
import { tGameNaraku } from "./tGameNaraku";
import { tGameNoriai } from "./tGameNoriai";
import { tGameNouchi } from "./tGameNouchi";
import { tGameNumWindow } from "./tGameNumWindow";
import { tGameNumWindow2 } from "./tGameNumWindow2";
import { tGameNw } from "./tGameNw";
import { tGameObjectResource } from "./tGameObjectResource";
import { tGameOnsen } from "./tGameOnsen";
import { tGameOpening } from "./tGameOpening";
import { tGameOption } from "./tGameOption";
import { tGameOptionWindow } from "./tGameOptionWindow";
import { tGameOverMapResource } from "./tGameOverMapResource";
import { tGameParts } from "./tGameParts";
import { tGamePlayerPartyInfo } from "./tGamePlayerPartyInfo";
import { tGamePoker } from "./tGamePoker";
import { tGameRecipe } from "./tGameRecipe";
import { tGameRecord } from "./tGameRecord";
import { tGameRectArea } from "./tGameRectArea";
import { tGameRefresh } from "./tGameRefresh";
import { tGameRoom } from "./tGameRoom";
import { tGameRoutineMap } from "./tGameRoutineMap";
import { tGameRoutineMapMove } from "./tGameRoutineMapMove";
import { tGameRyourifukuro } from "./tGameRyourifukuro";
import { tGameSave } from "./tGameSave";
import { tGameSchoolGenerator } from "./tGameSchoolGenerator";
import { tGameSelectBgmWindow } from "./tGameSelectBgmWindow";
import { tGameSelectFovTarget } from "./tGameSelectFovTarget";
import { tGameSelectFovTargetSkill } from "./tGameSelectFovTargetSkill";
import { tGameSelectImageTarget } from "./tGameSelectImageTarget";
import { tGameSelectTarget } from "./tGameSelectTarget";
import { tGameSelectWindow } from "./tGameSelectWindow";
import { tGameSfpc } from "./tGameSfpc";
import { tGameShitaiasari } from "./tGameShitaiasari";
import { tGameShokuzaifukuro } from "./tGameShokuzaifukuro";
import { tGameShop } from "./tGameShop";
import { tGameShortCut } from "./tGameShortCut";
import { tGameShortEvent } from "./tGameShortEvent";
import { tGameShukkabako } from "./tGameShukkabako";
import { tGameSkill } from "./tGameSkill";
import { tGameSkillAction } from "./tGameSkillAction";
import { tGameSkillActionBook } from "./tGameSkillActionBook";
import { tGameSkillActionInfoWindow } from "./tGameSkillActionInfoWindow";
import { tGameSkillActionWindow } from "./tGameSkillActionWindow";
import { tGameSkillInfoWindow } from "./tGameSkillInfoWindow";
import { tGameSkillShop } from "./tGameSkillShop";
import { tGameSkillWindow } from "./tGameSkillWindow";
import { tGameSlaveShop } from "./tGameSlaveShop";
import { tGameSleep } from "./tGameSleep";
import { tGameSlot } from "./tGameSlot";
import { tGameSlumGenerator } from "./tGameSlumGenerator";
import { tGameSoubifukuro } from "./tGameSoubifukuro";
import { tGameSoundResource } from "./tGameSoundResource";
import { tGameSozaifukuro } from "./tGameSozaifukuro";
import { tGameSpecialMap } from "./tGameSpecialMap";
import { tGameStatusWindow } from "./tGameStatusWindow";
import { tGameSteal } from "./tGameSteal";
import { tGameStg } from "./tGameStg";
import { tGameStorage } from "./tGameStorage";
import { tGameStoryWindow } from "./tGameStoryWindow";
import { tGameSubTown } from "./tGameSubTown";
import { tGameTableTalk } from "./tGameTableTalk";
import { tGameTalkResource } from "./tGameTalkResource";
import { tGameText } from "./tGameText";
import { tGameTextInputWindow } from "./tGameTextInputWindow";
import { tGameTextInputWindow2 } from "./tGameTextInputWindow2";
import { tGameTime } from "./tGameTime";
import { tGameTitle } from "./tGameTitle";
import { tGameTitleWindow } from "./tGameTitleWindow";
import { tGameTougijo } from "./tGameTougijo";
import { tGameTownGenerator } from "./tGameTownGenerator";
import { tGameTrap } from "./tGameTrap";
import { tGameTutorial } from "./tGameTutorial";
import { tGameUniqueQuest } from "./tGameUniqueQuest";
import { tGameVersion } from "./tGameVersion";
import { tGameWar } from "./tGameWar";
import { tGameWeading } from "./tGameWeading";
import { tGameWeather } from "./tGameWeather";
import { tGameWindowResource } from "./tGameWindowResource";
import { tGameWindows } from "./tGameWindows";
import { tGameYagi } from "./tGameYagi";
import { tGameYubiwadukuri } from "./tGameYubiwadukuri";
import { tGameYukigassen } from "./tGameYukigassen";

export interface tGameMain
{
    /** See also: {@link tGameLoading} */
    tGameLoading: tGameLoading;

    /** See also: {@link tGameSave} */
    tGameSave: tGameSave;

    /** See also: {@link tGameOption} */
    tGameOption: tGameOption;

    /** See also: {@link tGameNw} */
    tGameNw: tGameNw;

    /** See also: {@link tGameWindows} */
    tGameWindows: tGameWindows;

    /** See also: {@link tGameTalkResource} */
    tGameTalkResource: tGameTalkResource;

    /** See also: {@link tGameMyAdventurerCharactor} */
    tGameMyAdventurerCharactor: tGameMyAdventurerCharactor;

    /** See also: {@link tGameHyk} */
    tGameHyk: tGameHyk;

    /** See also: {@link tGameKeyboard} */
    tGameKeyboard: tGameKeyboard;

    /** See also: {@link tGameMap} */
    tGameMap: tGameMap;

    /** See also: {@link tGameRefresh} */
    tGameRefresh: tGameRefresh;

    /** See also: {@link tGameMapResource} */
    tGameMapResource: tGameMapResource;

    /** See also: {@link tGameObjectResource} */
    tGameObjectResource: tGameObjectResource;

    /** See also: {@link tGameChipsetResource} */
    tGameChipsetResource: tGameChipsetResource;

    /** See also: {@link tGameFaceResource} */
    tGameFaceResource: tGameFaceResource;

    /** See also: {@link tGameWindowResource} */
    tGameWindowResource: tGameWindowResource;

    /** See also: {@link tGameSoundResource} */
    tGameSoundResource: tGameSoundResource;

    /** See also: {@link tGameBgmResource} */
    tGameBgmResource: tGameBgmResource;

    /** See also: {@link tGameIconResource} */
    tGameIconResource: tGameIconResource;

    /** See also: {@link tGameIcon24Resource} */
    tGameIcon24Resource: tGameIcon24Resource;

    /** See also: {@link tGameCharactor} */
    tGameCharactor: tGameCharactor;

    /** See also: {@link tGameCharactorData} */
    tGameCharactorData: tGameCharactorData;

    /** See also: {@link tGameMessageWindow} */
    tGameMessageWindow: tGameMessageWindow;

    /** See also: {@link tGameData} */
    tGameData: tGameData;

    /** See also: {@link tGameRoutineMap} */
    tGameRoutineMap: tGameRoutineMap;

    /** See also: {@link tGameRoutineMapMove} */
    tGameRoutineMapMove: tGameRoutineMapMove;

    /** See also: {@link tGameSelectTarget} */
    tGameSelectTarget: tGameSelectTarget;

    /** See also: {@link tGameText} */
    tGameText: tGameText;

    /** See also: {@link tGameDungeonGenerator} */
    tGameDungeonGenerator: tGameDungeonGenerator;

    /** See also: {@link tGameTownGenerator} */
    tGameTownGenerator: tGameTownGenerator;

    /** See also: {@link tGameSchoolGenerator} */
    tGameSchoolGenerator: tGameSchoolGenerator;

    /** See also: {@link tGameCastleGenerator} */
    tGameCastleGenerator: tGameCastleGenerator;

    /** See also: {@link tGameFieldGenerator} */
    tGameFieldGenerator: tGameFieldGenerator;

    /** See also: {@link tGameAffectMap} */
    tGameAffectMap: tGameAffectMap;

    /** See also: {@link tGameLog} */
    tGameLog: tGameLog;

    /** See also: {@link tGameTime} */
    tGameTime: tGameTime;

    /** See also: {@link tGameMenu} */
    tGameMenu: tGameMenu;

    /** See also: {@link tGameName} */
    tGameName: tGameName;

    /** See also: {@link tGameSkill} */
    tGameSkill: tGameSkill;

    /** See also: {@link tGameItem} */
    tGameItem: tGameItem;

    /** See also: {@link tGameItemWindow} */
    tGameItemWindow: tGameItemWindow;

    /** See also: {@link tGameTitle} */
    tGameTitle: tGameTitle;

    /** See also: {@link tGameTitleWindow} */
    tGameTitleWindow: tGameTitleWindow;

    /** See also: {@link tGameParts} */
    tGameParts: tGameParts;

    /** See also: {@link tGamePlayerPartyInfo} */
    tGamePlayerPartyInfo: tGamePlayerPartyInfo;

    /** See also: {@link tGameFukidashiResource} */
    tGameFukidashiResource: tGameFukidashiResource;

    /** See also: {@link tGameEmotionResource} */
    tGameEmotionResource: tGameEmotionResource;

    /** See also: {@link tGameCalc} */
    tGameCalc: tGameCalc;

    /** See also: {@link tGameEquipmentWindow} */
    tGameEquipmentWindow: tGameEquipmentWindow;

    /** See also: {@link tGameSelectFovTarget} */
    tGameSelectFovTarget: tGameSelectFovTarget;

    /** See also: {@link tGameSelectFovTargetSkill} */
    tGameSelectFovTargetSkill: tGameSelectFovTargetSkill;

    /** See also: {@link tGameSkillAction} */
    tGameSkillAction: tGameSkillAction;

    /** See also: {@link tGameSkillActionWindow} */
    tGameSkillActionWindow: tGameSkillActionWindow;

    /** See also: {@link tGameEffect} */
    tGameEffect: tGameEffect;

    /** See also: {@link tGameOverMapResource} */
    tGameOverMapResource: tGameOverMapResource;

    /** See also: {@link tGameTrap} */
    tGameTrap: tGameTrap;

    /** See also: {@link tGameGoodTrap} */
    tGameGoodTrap: tGameGoodTrap;

    /** See also: {@link tGameNumWindow} */
    tGameNumWindow: tGameNumWindow;

    /** See also: {@link tGameShop} */
    tGameShop: tGameShop;

    /** See also: {@link tGameItemInfoWindow} */
    tGameItemInfoWindow: tGameItemInfoWindow;

    /** See also: {@link tGameSkillActionInfoWindow} */
    tGameSkillActionInfoWindow: tGameSkillActionInfoWindow;

    /** See also: {@link tGameAdventurerGuild} */
    tGameAdventurerGuild: tGameAdventurerGuild;

    /** See also: {@link tGameAdventurerGuildWindow} */
    tGameAdventurerGuildWindow: tGameAdventurerGuildWindow;

    /** See also: {@link tGameAdventurerGuildConfirmWindow} */
    tGameAdventurerGuildConfirmWindow: tGameAdventurerGuildConfirmWindow;

    /** See also: {@link tGameWeather} */
    tGameWeather: tGameWeather;

    /** See also: {@link tGameShortCut} */
    tGameShortCut: tGameShortCut;

    /** See also: {@link tGameFarm} */
    tGameFarm: tGameFarm;

    /** See also: {@link tGameCooking} */
    tGameCooking: tGameCooking;

    /** See also: {@link tGameJob} */
    tGameJob: tGameJob;

    /** See also: {@link tGameSleep} */
    tGameSleep: tGameSleep;

    /** See also: {@link tGameSpecialMap} */
    tGameSpecialMap: tGameSpecialMap;

    /** See also: {@link tGameSkillWindow} */
    tGameSkillWindow: tGameSkillWindow;

    /** See also: {@link tGameSkillInfoWindow} */
    tGameSkillInfoWindow: tGameSkillInfoWindow;

    /** See also: {@link tGameSkillShop} */
    tGameSkillShop: tGameSkillShop;

    /** See also: {@link tGameStatusWindow} */
    tGameStatusWindow: tGameStatusWindow;

    /** See also: {@link tGameSlaveShop} */
    tGameSlaveShop: tGameSlaveShop;

    /** See also: {@link tGameTextInputWindow} */
    tGameTextInputWindow: tGameTextInputWindow;

    /** See also: {@link tGameRecipe} */
    tGameRecipe: tGameRecipe;

    /** See also: {@link tGameCreateWindow} */
    tGameCreateWindow: tGameCreateWindow;

    /** See also: {@link tGameCharactorRuleWindow} */
    tGameCharactorRuleWindow: tGameCharactorRuleWindow;

    /** See also: {@link tGameSelectWindow} */
    tGameSelectWindow: tGameSelectWindow;

    /** See also: {@link tGameOptionWindow} */
    tGameOptionWindow: tGameOptionWindow;

    /** See also: {@link tGameStorage} */
    tGameStorage: tGameStorage;

    /** See also: {@link tGameShukkabako} */
    tGameShukkabako: tGameShukkabako;

    /** See also: {@link tGameEnchantment} */
    tGameEnchantment: tGameEnchantment;

    /** See also: {@link tGameBlacksmith} */
    tGameBlacksmith: tGameBlacksmith;

    /** See also: {@link tGameYubiwadukuri} */
    tGameYubiwadukuri: tGameYubiwadukuri;

    /** See also: {@link tGameFishing} */
    tGameFishing: tGameFishing;

    /** See also: {@link tGameMapEditor} */
    tGameMapEditor: tGameMapEditor;

    /** See also: {@link tGameMyTown} */
    tGameMyTown: tGameMyTown;

    /** See also: {@link tGameNouchi} */
    tGameNouchi: tGameNouchi;

    /** See also: {@link tGameEditMember} */
    tGameEditMember: tGameEditMember;

    /** See also: {@link tGameSteal} */
    tGameSteal: tGameSteal;

    /** See also: {@link tGameChangeProfile} */
    tGameChangeProfile: tGameChangeProfile;

    /** See also: {@link tGameCriminalWindow} */
    tGameCriminalWindow: tGameCriminalWindow;

    /** See also: {@link tGameTableTalk} */
    tGameTableTalk: tGameTableTalk;

    /** See also: {@link tGameAllocateStatusWindow} */
    tGameAllocateStatusWindow: tGameAllocateStatusWindow;

    /** See also: {@link tGameMapCharaCommonAction} */
    tGameMapCharaCommonAction: tGameMapCharaCommonAction;

    /** See also: {@link tGameJobChange} */
    tGameJobChange: tGameJobChange;

    /** See also: {@link tGameSlumGenerator} */
    tGameSlumGenerator: tGameSlumGenerator;

    /** See also: {@link tGameRectArea} */
    tGameRectArea: tGameRectArea;

    /** See also: {@link tGameRoom} */
    tGameRoom: tGameRoom;

    /** See also: {@link tGameSkillActionBook} */
    tGameSkillActionBook: tGameSkillActionBook;

    /** See also: {@link tGameMyShop} */
    tGameMyShop: tGameMyShop;

    /** See also: {@link tGameFullscreenLog} */
    tGameFullscreenLog: tGameFullscreenLog;

    /** See also: {@link tGameSelectImageTarget} */
    tGameSelectImageTarget: tGameSelectImageTarget;

    /** See also: {@link tGameCreateCharactor} */
    tGameCreateCharactor: tGameCreateCharactor;

    /** See also: {@link tGameEventAnimation} */
    tGameEventAnimation: tGameEventAnimation;

    /** See also: {@link tGameDesignedMap} */
    tGameDesignedMap: tGameDesignedMap;

    /** See also: {@link tGameEtc} */
    tGameEtc: tGameEtc;

    /** See also: {@link tGameMaou} */
    tGameMaou: tGameMaou;

    /** See also: {@link tGameMagicalGirl} */
    tGameMagicalGirl: tGameMagicalGirl;

    /** See also: {@link tGameEventFrame} */
    tGameEventFrame: tGameEventFrame;

    /** See also: {@link tGameGameOver} */
    tGameGameOver: tGameGameOver;

    /** See also: {@link tGameEvent} */
    tGameEvent: tGameEvent;

    /** See also: {@link tGameGuide} */
    tGameGuide: tGameGuide;

    /** See also: {@link tGameEtcTown} */
    tGameEtcTown: tGameEtcTown;

    /** See also: {@link tGameCreateUniqueCharactor} */
    tGameCreateUniqueCharactor: tGameCreateUniqueCharactor;

    /** See also: {@link tGameTougijo} */
    tGameTougijo: tGameTougijo;

    /** See also: {@link tGameSlot} */
    tGameSlot: tGameSlot;

    /** See also: {@link tGamePoker} */
    tGamePoker: tGamePoker;

    /** See also: {@link tGameCasino} */
    tGameCasino: tGameCasino;

    /** See also: {@link tGameCharactorEquipRuleWindow} */
    tGameCharactorEquipRuleWindow: tGameCharactorEquipRuleWindow;

    /** See also: {@link tGameEnsei} */
    tGameEnsei: tGameEnsei;

    /** See also: {@link tGameEquipRankup} */
    tGameEquipRankup: tGameEquipRankup;

    /** See also: {@link tGameHikitsugi} */
    tGameHikitsugi: tGameHikitsugi;

    /** See also: {@link tGameNoriai} */
    tGameNoriai: tGameNoriai;

    /** See also: {@link tGameFieldMaterial} */
    tGameFieldMaterial: tGameFieldMaterial;

    /** See also: {@link tGameWar} */
    tGameWar: tGameWar;

    /** See also: {@link tGameAkumuDungeon} */
    tGameAkumuDungeon: tGameAkumuDungeon;

    /** See also: {@link tGameTutorial} */
    tGameTutorial: tGameTutorial;

    /** See also: {@link tGameHelp} */
    tGameHelp: tGameHelp;

    /** See also: {@link tGameBazaarGenerator} */
    tGameBazaarGenerator: tGameBazaarGenerator;

    /** See also: {@link tGameMaigo} */
    tGameMaigo: tGameMaigo;

    /** See also: {@link tGameButsu} */
    tGameButsu: tGameButsu;

    /** See also: {@link tGameNaraku} */
    tGameNaraku: tGameNaraku;

    /** See also: {@link tGameShitaiasari} */
    tGameShitaiasari: tGameShitaiasari;

    /** See also: {@link tGameGod} */
    tGameGod: tGameGod;

    /** See also: {@link tGameFaithWindow} */
    tGameFaithWindow: tGameFaithWindow;

    /** See also: {@link tGameFaith} */
    tGameFaith: tGameFaith;

    /** See also: {@link tGameCommand} */
    tGameCommand: tGameCommand;

    /** See also: {@link tGameWeading} */
    tGameWeading: tGameWeading;

    /** See also: {@link tGameSozaifukuro} */
    tGameSozaifukuro: tGameSozaifukuro;

    /** See also: {@link tGameBaby} */
    tGameBaby: tGameBaby;

    /** See also: {@link tGameIdRecycle} */
    tGameIdRecycle: tGameIdRecycle;

    /** See also: {@link tGameStoryWindow} */
    tGameStoryWindow: tGameStoryWindow;

    /** See also: {@link tGameOpening} */
    tGameOpening: tGameOpening;

    /** See also: {@link tGameGamePad} */
    tGameGamePad: tGameGamePad;

    /** See also: {@link tGameGameClear} */
    tGameGameClear: tGameGameClear;

    /** See also: {@link tGameGamePadEditor} */
    tGameGamePadEditor: tGameGamePadEditor;

    /** See also: {@link tGameGamePadBase} */
    tGameGamePadBase: tGameGamePadBase;

    /** See also: {@link tGameRecord} */
    tGameRecord: tGameRecord;

    /** See also: {@link tGameOnsen} */
    tGameOnsen: tGameOnsen;

    /** See also: {@link tGameSfpc} */
    tGameSfpc: tGameSfpc;

    /** See also: {@link tGameYagi} */
    tGameYagi: tGameYagi;

    /** See also: {@link tGameLakeZou} */
    tGameLakeZou: tGameLakeZou;

    /** See also: {@link tGameStg} */
    tGameStg: tGameStg;

    /** See also: {@link tGameYukigassen} */
    tGameYukigassen: tGameYukigassen;

    /** See also: {@link tGameHoridashimono} */
    tGameHoridashimono: tGameHoridashimono;

    /** See also: {@link tGameDairyQuest} */
    tGameDairyQuest: tGameDairyQuest;

    /** See also: {@link tGameAnimalWood} */
    tGameAnimalWood: tGameAnimalWood;

    /** See also: {@link tGameChikaMakyo} */
    tGameChikaMakyo: tGameChikaMakyo;

    /** See also: {@link tGameHikyo} */
    tGameHikyo: tGameHikyo;

    /** See also: {@link tGameUniqueQuest} */
    tGameUniqueQuest: tGameUniqueQuest;

    /** See also: {@link tGameShortEvent} */
    tGameShortEvent: tGameShortEvent;

    /** See also: {@link tGameJashin} */
    tGameJashin: tGameJashin;

    /** See also: {@link tGameVersion} */
    tGameVersion: tGameVersion;

    /** See also: {@link tGameMyTownRuleWindow} */
    tGameMyTownRuleWindow: tGameMyTownRuleWindow;

    /** See also: {@link tGameSubTown} */
    tGameSubTown: tGameSubTown;

    /** See also: {@link tGameMyTownMeibo} */
    tGameMyTownMeibo: tGameMyTownMeibo;

    /** See also: {@link tGameExMapData} */
    tGameExMapData: tGameExMapData;

    /** See also: {@link tGameSelectBgmWindow} */
    tGameSelectBgmWindow: tGameSelectBgmWindow;

    /** See also: {@link tGameMenuShortcutWindow} */
    tGameMenuShortcutWindow: tGameMenuShortcutWindow;

    /** See also: {@link tGameGameOptionWindow} */
    tGameGameOptionWindow: tGameGameOptionWindow;

    /** See also: {@link tGameRyourifukuro} */
    tGameRyourifukuro: tGameRyourifukuro;

    /** See also: {@link tGameShokuzaifukuro} */
    tGameShokuzaifukuro: tGameShokuzaifukuro;

    /** See also: {@link tGameHikitsugiNakama} */
    tGameHikitsugiNakama: tGameHikitsugiNakama;

    /** See also: {@link tGameAcn} */
    tGameAcn: tGameAcn;

    /** See also: {@link tGameSoubifukuro} */
    tGameSoubifukuro: tGameSoubifukuro;

    /** See also: {@link tGameCriminalRouya} */
    tGameCriminalRouya: tGameCriminalRouya;

    /** See also: {@link tGameMeiro} */
    tGameMeiro: tGameMeiro;

    /** See also: {@link tGameMatsuri} */
    tGameMatsuri: tGameMatsuri;

    /** See also: {@link tGameIkesu} */
    tGameIkesu: tGameIkesu;

    /** See also: {@link tGameTextInputWindow2} */
    tGameTextInputWindow2: tGameTextInputWindow2;

    /** See also: {@link tGameNumWindow2} */
    tGameNumWindow2: tGameNumWindow2;

    /** See also: {@link tGameJinja} */
    tGameJinja: tGameJinja;

    /** See also: {@link tGameK1up} */
    tGameK1up: tGameK1up;

    /** See also: {@link tGameLoading2} */
    tGameLoading2: tGameLoading2;

    /** See also: {@link tGameDialog} */
    tGameDialog: tGameDialog;

    /** See also: {@link tGameMamonoJisho} */
    tGameMamonoJisho: tGameMamonoJisho;

    /** See also: {@link tGameNakamaHaken} */
    tGameNakamaHaken: tGameNakamaHaken;
}