/**
 * tGameJob.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameJob
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	jobData: any
	/**
	* Unknown
	*/
	groups: any
	/**
	* Unknown
	*/
	jobNameMax: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	loadJob(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	getJobName(a: any, b: any): any
	/**
	* Unknown
	*/
	getCharactorJobName(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getJobChangeTargets(a: any): any
	/**
	* Unknown
	*/
	initGroups(): any
	/**
	* Unknown
	*/
	getRandomJob(a: any): any
}
