/**
 * tGameStatusWindow.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameStatusWindow
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	textMaxWidth: any
	/**
	* Unknown
	*/
	views: any
	/**
	* Unknown
	*/
	ccvs: any
	/**
	* Unknown
	*/
	cctx: any
	/**
	* Unknown
	*/
	fontSize: any
	/**
	* Unknown
	*/
	textSpace: any
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	cursor: any
	/**
	* Unknown
	*/
	pagesMaster: any
	/**
	* Unknown
	*/
	pages: any
	/**
	* Unknown
	*/
	dcvs: any
	/**
	* Unknown
	*/
	dctx: any
	/**
	* Unknown
	*/
	pcvs: any
	/**
	* Unknown
	*/
	pctx: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	clear(): any
	/**
	* Unknown
	*/
	viewStatusWindow(a: any, b: any): any
	/**
	* Unknown
	*/
	drawTable(a: any): any
	/**
	* Unknown
	*/
	drawProfile(): any
	/**
	* Unknown
	*/
	drawDefcdt(): any
	/**
	* Unknown
	*/
	drawCondition(): any
	/**
	* Unknown
	*/
	drawNpcEtc(): any
	/**
	* Unknown
	*/
	drawPage(a: any): any
	/**
	* Unknown
	*/
	drawPage_main(a: any): any
	/**
	* Unknown
	*/
	drawPage_defcdt(a: any): any
	/**
	* Unknown
	*/
	drawPage_condition(a: any): any
	/**
	* Unknown
	*/
	drawPage_npcetc(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_dispose(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_frame(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_draw(a: any): any
	/**
	* Unknown
	*/
	clearCanvas(): any
	/**
	* Unknown
	*/
	updateStatus(): any
	/**
	* Unknown
	*/
	isNpcEtc(a: any): any
}
