/**
 * tGameOverMapResource.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameOverMapResource
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	chipsize: any
	/**
	* Unknown
	*/
	omapData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	getOrderMap(a: any): any
	/**
	* Unknown
	*/
	getRoundMap(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getEdgeChipset(a: any): any
	/**
	* Unknown
	*/
	getChipsetIndex(a: any, b: any): any
	/**
	* Unknown
	*/
	drawChipset(a: any): any
}
