/**
 * tGameFaceResource.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameFaceResource
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	size: any
	/**
	* Unknown
	*/
	faceLink: any
	/**
	* Unknown
	*/
	faceData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	getSomeFace(a: any): any
	/**
	* Unknown
	*/
	getFace(a: any): any
	/**
	* Unknown
	*/
	getChipsetFace(a: any): any
	/**
	* Unknown
	*/
	loadImage(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	loadAllImage(a: any): any
	/**
	* Unknown
	*/
	loadLinkJson(a: any): any
	/**
	* Unknown
	*/
	getRandomCharactor(a: any, b: any, c: any, d: any, e: any, f: any): any
	/**
	* Unknown
	*/
	getRandomObjectId(a: any): any
	/**
	* Unknown
	*/
	getRandomFaceId(a: any): any
	/**
	* Unknown
	*/
	loadOverwrite(a: any): any
	/**
	* Unknown
	*/
	loadOverwrite__face(a: any): any
}
