/**
 * tGameNakamaHaken.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameNakamaHaken
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	view(a: any, b: any): any
	/**
	* Unknown
	*/
	viewMenu(a: any): any
	/**
	* Unknown
	*/
	viewSelectHakenNakama(a: any): any
	/**
	* Unknown
	*/
	getHakenKanouCharas(): any
	/**
	* Unknown
	*/
	getHakenchuCharas(): any
	/**
	* Unknown
	*/
	isHakenKanouChara(a: any): any
	/**
	* Unknown
	*/
	refreshDungeonLevel(a: any): any
	/**
	* Unknown
	*/
	initCharaValue(a: any): any
	/**
	* Unknown
	*/
	getDungeonNanido(a: any, b: any): any
	/**
	* Unknown
	*/
	isHakenNow(a: any): any
	/**
	* Unknown
	*/
	getHakenTime(a: any, b: any): any
	/**
	* Unknown
	*/
	registHaken(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	setHakenClose(a: any): any
	/**
	* Unknown
	*/
	registHakenCancel(a: any, b: any): any
	/**
	* Unknown
	*/
	viewHakenchuNakama(a: any): any
	/**
	* Unknown
	*/
	setResultInfo(a: any): any
	/**
	* Unknown
	*/
	getHoshuBUnkatsu(a: any): any
	/**
	* Unknown
	*/
	viewResult(a: any, b: any): any
	/**
	* Unknown
	*/
	unlockRandomMamono(a: any): any
}
