/**
 * tGameJinja.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameJinja
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	affectSaisenbako(a: any, b: any): any
	/**
	* Unknown
	*/
	kau(a: any, b: any): any
	/**
	* Unknown
	*/
	kau2(a: any, b: any): any
}
