/**
 * tGameTime.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameTime
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	cvs: any
	/**
	* Unknown
	*/
	ctx: any
	/**
	* Unknown
	*/
	isRequireRefresh: any
	/**
	* Unknown
	*/
	lastRect: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	setRefreshFlg(): any
	/**
	* Unknown
	*/
	getNow(): any
	/**
	* Unknown
	*/
	viewAmpm(a: any): any
	/**
	* Unknown
	*/
	getTimeToWaitTime(a: any): any
	/**
	* Unknown
	*/
	addTime(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getZeroDate(a: any): any
	/**
	* Unknown
	*/
	getDate(a: any): any
	/**
	* Unknown
	*/
	calAge(a: any, b: any): any
	/**
	* Unknown
	*/
	getBirthDayToTime(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	createBiarthday(a: any, b: any): any
	/**
	* Unknown
	*/
	drawTime(): any
	/**
	* Unknown
	*/
	drawTime_en(): any
	/**
	* Unknown
	*/
	viewTime(): any
	/**
	* Unknown
	*/
	frameActionDraw(a: any): any
	/**
	* Unknown
	*/
	getTimeGroup(a: any): any
	/**
	* Unknown
	*/
	get6Time(a: any): any
	/**
	* Unknown
	*/
	setPlayTime(a: any): any
	/**
	* Unknown
	*/
	getTargetTimeText(a: any): any
	/**
	* Unknown
	*/
	setTimeBgm(a: any, b: any): any
	/**
	* Unknown
	*/
	setAdvanceTime(a: any): any
}
