/**
 * tGameMap.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameMap
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	data: any
	/**
	* Unknown
	*/
	maps: any
	/**
	* Unknown
	*/
	cvs: any
	/**
	* Unknown
	*/
	ctx: any
	/**
	* Unknown
	*/
	scvs: any
	/**
	* Unknown
	*/
	sctx: any
	/**
	* Unknown
	*/
	obcvs: any
	/**
	* Unknown
	*/
	obctx: any
	/**
	* Unknown
	*/
	o1cvs: any
	/**
	* Unknown
	*/
	o1ctx: any
	/**
	* Unknown
	*/
	o2cvs: any
	/**
	* Unknown
	*/
	o2ctx: any
	/**
	* Unknown
	*/
	vcvs: any
	/**
	* Unknown
	*/
	vctx: any
	/**
	* Unknown
	*/
	pcvs: any
	/**
	* Unknown
	*/
	pctx: any
	/**
	* Unknown
	*/
	cache: any
	/**
	* Unknown
	*/
	init(): any
	/**
	* Unknown
	*/
	getChipDataByFieldChip(a: any): any
	/**
	* Unknown
	*/
	getChipData(a: any): any
	/**
	* Unknown
	*/
	getYukaChip(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	addMap(a: any): any
	/**
	* Unknown
	*/
	removeMap(a: any): any
	/**
	* Unknown
	*/
	drawSmallMap(a: any): any
	/**
	* Unknown
	*/
	getSmallMapData(a: any): any
	/**
	* Unknown
	*/
	drawGroundOver(a: any, b: any): any
	/**
	* Unknown
	*/
	drawGround(a: any, b: any): any
	/**
	* Unknown
	*/
	drawOutSightGround(a: any): any
	/**
	* Unknown
	*/
	drawObject(a: any, b: any): any
	/**
	* Unknown
	*/
	drawOver(a: any, b: any): any
	/**
	* Unknown
	*/
	getFovCharactors(a: any): any
	/**
	* Unknown
	*/
	convertMapData(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	convertMapData2(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	getFov(a: any): any
	/**
	* Unknown
	*/
	getAroundCanMove(a: any): any
	/**
	* Unknown
	*/
	dropItem(a: any): any
	/**
	* Unknown
	*/
	removeObject(a: any, b: any): any
	/**
	* Unknown
	*/
	initSaveData(): any
	/**
	* Unknown
	*/
	getSaveData(): any
	/**
	* Unknown
	*/
	setSaveData(a: any): any
	/**
	* Unknown
	*/
	getMap(a: any): any
	/**
	* Unknown
	*/
	getRoute(a: any, b: any, c: any, d: any, e: any, f: any, g: any): any
	/**
	* Unknown
	*/
	nextTrunFukidashi(a: any): any
	/**
	* Unknown
	*/
	nextTrunEmotion(a: any): any
	/**
	* Unknown
	*/
	getFreeSpaces(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	checkObjectSpace(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	searchMapObject(a: any, b: any): any
	/**
	* Unknown
	*/
	searchMapObjectType(a: any, b: any): any
	/**
	* Unknown
	*/
	getObjectSmap(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	checkAdjacentCharactor(a: any, b: any): any
	/**
	* Unknown
	*/
	getRandomSpace(a: any): any
	/**
	* Unknown
	*/
	getRandomSpace2(a: any): any
	/**
	* Unknown
	*/
	getDistance(a: any, b: any): any
	/**
	* Unknown
	*/
	getDistance2(a: any, b: any): any
	/**
	* Unknown
	*/
	getCharactorDistances(a: any, b: any): any
	/**
	* Unknown
	*/
	getDirection(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getMapSpData(a: any, b: any): any
	/**
	* Unknown
	*/
	removeMapObjects(a: any): any
	/**
	* Unknown
	*/
	takeSkillAction(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	clearCacheViewMap(): any
	/**
	* Unknown
	*/
	cloneMap(a: any): any
	/**
	* Unknown
	*/
	getInMapPosition(a: any, b: any): any
	/**
	* Unknown
	*/
	dropMap(a: any, b: any): any
	/**
	* Unknown
	*/
	setCommonObjectCharactors(a: any): any
	/**
	* Unknown
	*/
	getIncludeAreas(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getTargetAreaCanvas(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	removeOneActionFinishAction(a: any, b: any): any
	/**
	* Unknown
	*/
	setGroundOverTarget(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getAroundFreePositions(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getCalMoveMap(a: any): any
	/**
	* Unknown
	*/
	drawLevel(a: any): any
	/**
	* Unknown
	*/
	createFieldRoad(a: any): any
	/**
	* Unknown
	*/
	cacheFieldRoadData(a: any): any
	/**
	* Unknown
	*/
	drawFieldRoad(a: any): any
}
