/**
 * tGamePoker.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGamePoker
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	data: any
	/**
	* Unknown
	*/
	objs: any
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	waits: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	getPlayerCoin(): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	loadLinkJson(a: any): any
	/**
	* Unknown
	*/
	initFrame(a: any): any
	/**
	* Unknown
	*/
	getShuffleCards(): any
	/**
	* Unknown
	*/
	getCardPosition(a: any): any
	/**
	* Unknown
	*/
	setCardImage(a: any, b: any): any
	/**
	* Unknown
	*/
	updateMymoney(): any
	/**
	* Unknown
	*/
	view(a: any): any
	/**
	* Unknown
	*/
	initBetView(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	setMode(a: any, b: any): any
	/**
	* Unknown
	*/
	clear(): any
	/**
	* Unknown
	*/
	startGame(): any
	/**
	* Unknown
	*/
	dealCards(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	checkMatch(): any
	/**
	* Unknown
	*/
	finishGame(): any
	/**
	* Unknown
	*/
	hit(a: any): any
	/**
	* Unknown
	*/
	animationGetCoin(a: any): any
	/**
	* Unknown
	*/
	changeCards(): any
	/**
	* Unknown
	*/
	throwCards(a: any, b: any): any
	/**
	* Unknown
	*/
	setFrameEvent(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_dispose(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_frame(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_draw(a: any): any
	/**
	* Unknown
	*/
	drawLock(): any
	/**
	* Unknown
	*/
	drawCursor(a: any): any
	/**
	* Unknown
	*/
	drawBet(): any
	/**
	* Unknown
	*/
	affect(a: any): any
}
