/**
 * tGameCriminalRouya.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameCriminalRouya
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	criminalRouyaMaxNum: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	changeCtype(a: any): any
	/**
	* Unknown
	*/
	affect(a: any, b: any): any
	/**
	* Unknown
	*/
	viewList(a: any, b: any): any
	/**
	* Unknown
	*/
	nakamani(a: any): any
	/**
	* Unknown
	*/
	mytownhe(a: any): any
	/**
	* Unknown
	*/
	boukenshahe(a: any): any
}
