/**
 * tGameAkumuDungeon.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameAkumuDungeon
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	isSetAkumu(a: any): any
	/**
	* Unknown
	*/
	getDungeonLevel(a: any): any
	/**
	* Unknown
	*/
	akumuidomu(a: any): any
	/**
	* Unknown
	*/
	createDungeon(a: any): any
	/**
	* Unknown
	*/
	bossGekiha(a: any, b: any): any
}
