/**
 * tGameIconResource.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameIconResource
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	iconData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	loadIcon(a: any): any
	/**
	* Unknown
	*/
	getIconData(a: any): any
}
