/**
 * tGameLog.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameLog
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	logs: any
	/**
	* Unknown
	*/
	logMaxNum: any
	/**
	* Unknown
	*/
	textMaxWidth: any
	/**
	* Unknown
	*/
	fontSize: any
	/**
	* Unknown
	*/
	lineHeight: any
	/**
	* Unknown
	*/
	cvs: any
	/**
	* Unknown
	*/
	ctx: any
	/**
	* Unknown
	*/
	tcvs: any
	/**
	* Unknown
	*/
	tctx: any
	/**
	* Unknown
	*/
	lastRect: any
	/**
	* Unknown
	*/
	isRequireRefresh: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	addAndViewLog(a: any, b: any): any
	/**
	* Unknown
	*/
	addLog(a: any, b: any): any
	/**
	* Unknown
	*/
	clearLog(): any
	/**
	* Unknown
	*/
	drawLog(): any
	/**
	* Unknown
	*/
	viewLog(): any
	/**
	* Unknown
	*/
	viewOverlookLog(a: any): any
	/**
	* Unknown
	*/
	drawOverlookLog(a: any): any
	/**
	* Unknown
	*/
	frameActionDraw(a: any): any
}
