/**
 * tGameStg.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameStg
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	data: any
	/**
	* Unknown
	*/
	img: any
	/**
	* Unknown
	*/
	objs: any
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	tGameStgBg: any
	/**
	* Unknown
	*/
	tGameStgShoot: any
	/**
	* Unknown
	*/
	tGameStgObject: any
	/**
	* Unknown
	*/
	tGameStgScene: any
	/**
	* Unknown
	*/
	tGameStgEnemy: any
	/**
	* Unknown
	*/
	tGameStgPoint: any
	/**
	* Unknown
	*/
	size: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	loadLinkJson(a: any): any
	/**
	* Unknown
	*/
	initFrame(a: any): any
	/**
	* Unknown
	*/
	view(a: any): any
	/**
	* Unknown
	*/
	clear(): any
	/**
	* Unknown
	*/
	setFrameEvent(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_dispose(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_frame(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_draw(a: any): any
	/**
	* Unknown
	*/
	inputKey(a: any): any
	/**
	* Unknown
	*/
	gameOver(): any
	/**
	* Unknown
	*/
	gameClear(): any
}
