/**
 * tGameOption.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameOption
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	masterData: any
	/**
	* Unknown
	*/
	myData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	initData(a: any): any
	/**
	* Unknown
	*/
	getDataValue(a: any): any
	/**
	* Unknown
	*/
	setDataValue(a: any, b: any): any
	/**
	* Unknown
	*/
	initSaveData(): any
	/**
	* Unknown
	*/
	getSaveData(): any
	/**
	* Unknown
	*/
	setSaveData(a: any): any
	/**
	* Unknown
	*/
	getKey(): any
	/**
	* Unknown
	*/
	save(a: any): any
	/**
	* Unknown
	*/
	load(a: any): any
	/**
	* Unknown
	*/
	getLocalStorageData(a: any): any
	/**
	* Unknown
	*/
	reflect(): any
	/**
	* Unknown
	*/
	updateLoadIndex(a: any, b: any): any
	/**
	* Unknown
	*/
	loadEx(a: any): any
}
