/**
 * tGameItemWindow.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameItemWindow
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	textMaxWidth: any
	/**
	* Unknown
	*/
	textMaxWidth2: any
	/**
	* Unknown
	*/
	views: any
	/**
	* Unknown
	*/
	ccvs: any
	/**
	* Unknown
	*/
	cctx: any
	/**
	* Unknown
	*/
	fontSize: any
	/**
	* Unknown
	*/
	textSpace: any
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	viewItemMaxNum: any
	/**
	* Unknown
	*/
	cursor: any
	/**
	* Unknown
	*/
	clearBottomData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	clear(): any
	/**
	* Unknown
	*/
	updateBottomData(a: any): any
	/**
	* Unknown
	*/
	getCharactorBottomData(a: any, b: any): any
	/**
	* Unknown
	*/
	getStorageBottomData(a: any): any
	/**
	* Unknown
	*/
	getMyShopBottomData(a: any): any
	/**
	* Unknown
	*/
	getMoneyIcon(a: any): any
	/**
	* Unknown
	*/
	viewItemWindow(a: any, b: any): any
	/**
	* Unknown
	*/
	drawPage(a: any): any
	/**
	* Unknown
	*/
	getCursor(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_dispose(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_frame(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_draw(a: any): any
	/**
	* Unknown
	*/
	clearCanvas(): any
	/**
	* Unknown
	*/
	setCursor(a: any): any
	/**
	* Unknown
	*/
	updateItems(a: any): any
	/**
	* Unknown
	*/
	viewBottomWindow(a: any, b: any): any
	/**
	* Unknown
	*/
	getItemShortCuts(): any
}
