/**
 * tGameMyTownMeibo.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameMyTownMeibo
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	viewWindow(a: any): any
	/**
	* Unknown
	*/
	getItemDescription(a: any, b: any): any
	/**
	* Unknown
	*/
	changeCharaTown(a: any, b: any): any
	/**
	* Unknown
	*/
	isEnableChangeJuninToNakama(a: any, b: any): any
	/**
	* Unknown
	*/
	isEnableChangeNakamaToJunin(a: any): any
	/**
	* Unknown
	*/
	changeJuninToNakama(a: any, b: any): any
	/**
	* Unknown
	*/
	changeNakamaToJunin(a: any): any
}
