/**
 * tGameSelectWindow.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameSelectWindow
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	textMaxWidth: any
	/**
	* Unknown
	*/
	views: any
	/**
	* Unknown
	*/
	ccvs: any
	/**
	* Unknown
	*/
	cctx: any
	/**
	* Unknown
	*/
	fontSize: any
	/**
	* Unknown
	*/
	textSpace: any
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	viewCharactorRuleMaxNum: any
	/**
	* Unknown
	*/
	cursor: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	clear(): any
	/**
	* Unknown
	*/
	viewWindow(a: any, b: any): any
	/**
	* Unknown
	*/
	drawPage(a: any): any
	/**
	* Unknown
	*/
	getCursor(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_dispose(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_frame(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_draw(a: any): any
	/**
	* Unknown
	*/
	clearCanvas(): any
	/**
	* Unknown
	*/
	setCursor(a: any): any
	/**
	* Unknown
	*/
	drawTextColumnData(a: any, b: any): any
	/**
	* Unknown
	*/
	drawSelectColumnData(a: any, b: any): any
	/**
	* Unknown
	*/
	drawFaceColumnData(a: any, b: any): any
	/**
	* Unknown
	*/
	drawChipsetColumnData(a: any, b: any): any
	/**
	* Unknown
	*/
	drawChipsetItemColumnData(a: any, b: any): any
	/**
	* Unknown
	*/
	changeSelectColumnItem(a: any): any
	/**
	* Unknown
	*/
	changeFaceColumnItem(a: any): any
	/**
	* Unknown
	*/
	changeChipsetColumnItem(a: any): any
	/**
	* Unknown
	*/
	changeChipsetItemColumnItem(a: any): any
	/**
	* Unknown
	*/
	getColumnLabelHeight(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	drawColumnData(a: any, b: any): any
	/**
	* Unknown
	*/
	okButtonColumnItem(a: any): any
}
