/**
 * tGamePlayerPartyInfo.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGamePlayerPartyInfo
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	cvs: any
	/**
	* Unknown
	*/
	ctx: any
	/**
	* Unknown
	*/
	isRequireRefresh: any
	/**
	* Unknown
	*/
	init(): any
	/**
	* Unknown
	*/
	setRefreshFlg(): any
	/**
	* Unknown
	*/
	viewPartyInfo(): any
	/**
	* Unknown
	*/
	viewCharactorInfo(a: any): any
	/**
	* Unknown
	*/
	frameActionDraw(a: any): any
}
