/**
 * tGameOpening.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameOpening
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	talkData: any
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	hiddenCanvases: any
	/**
	* Unknown
	*/
	cvs: any
	/**
	* Unknown
	*/
	ctx: any
	/**
	* Unknown
	*/
	init(): any
	/**
	* Unknown
	*/
	view(a: any, b: any): any
	/**
	* Unknown
	*/
	view_k1(): any
	/**
	* Unknown
	*/
	view_k2(): any
	/**
	* Unknown
	*/
	view_k3(): any
	/**
	* Unknown
	*/
	view_k4(): any
	/**
	* Unknown
	*/
	view_k5(): any
	/**
	* Unknown
	*/
	viewMessage(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	createNohara(a: any): any
	/**
	* Unknown
	*/
	createAnkoku(a: any): any
	/**
	* Unknown
	*/
	createField(a: any): any
	/**
	* Unknown
	*/
	createTown(a: any): any
	/**
	* Unknown
	*/
	createDungeon(a: any): any
}
