/**
 * tGameHikitsugiNakama.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameHikitsugiNakama
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	max: any
	/**
	* Unknown
	*/
	version: any
	/**
	* Unknown
	*/
	myData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	initData(): any
	/**
	* Unknown
	*/
	initSaveData(): any
	/**
	* Unknown
	*/
	getSaveData(): any
	/**
	* Unknown
	*/
	setSaveData(a: any): any
	/**
	* Unknown
	*/
	save(a: any): any
	/**
	* Unknown
	*/
	load(a: any): any
	/**
	* Unknown
	*/
	getLocalStorageData(a: any): any
	/**
	* Unknown
	*/
	setWindow(a: any): any
	/**
	* Unknown
	*/
	view(a: any): any
	/**
	* Unknown
	*/
	convertChara2Data(a: any): any
	/**
	* Unknown
	*/
	viewYobidasu(a: any): any
	/**
	* Unknown
	*/
	getItemDescription(a: any, b: any): any
}
