/**
 * tGameGamePadBase.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameGamePadBase
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	isEnableGamePad: any
	/**
	* Unknown
	*/
	targetGamePadIndex: any
	/**
	* Unknown
	*/
	pressedButtons: any
	/**
	* Unknown
	*/
	simplePressKeys: any
	/**
	* Unknown
	*/
	pressKeyLimitTime: any
	/**
	* Unknown
	*/
	pressKeyClickTime: any
	/**
	* Unknown
	*/
	pressKeyDoubleClickTime: any
	/**
	* Unknown
	*/
	pressKeyPressTime: any
	/**
	* Unknown
	*/
	longPressKeyPressTime: any
	/**
	* Unknown
	*/
	pressKeys: any
	/**
	* Unknown
	*/
	isBlock: any
	/**
	* Unknown
	*/
	init(): any
	/**
	* Unknown
	*/
	frameAction(a: any): any
	/**
	* Unknown
	*/
	calKey(): any
	/**
	* Unknown
	*/
	sendKeyDown(a: any): any
	/**
	* Unknown
	*/
	sendKeyUp(a: any): any
	/**
	* Unknown
	*/
	clearPressKeys(): any
	/**
	* Unknown
	*/
	isDown(a: any): any
	/**
	* Unknown
	*/
	isDoubleDown(a: any): any
	/**
	* Unknown
	*/
	isClick(a: any): any
	/**
	* Unknown
	*/
	isDoubleClick(a: any): any
	/**
	* Unknown
	*/
	isPress(a: any): any
	/**
	* Unknown
	*/
	isDoublePress(a: any): any
	/**
	* Unknown
	*/
	isLongPress(a: any): any
	/**
	* Unknown
	*/
	setBlock(a: any): any
}
