/**
 * tGameYubiwadukuri.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameYubiwadukuri
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	kisekiMaxNum: any
	/**
	* Unknown
	*/
	gineikesshoMaxNum: any
	/**
	* Unknown
	*/
	size: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	getKisekiMaxNum(): any
	/**
	* Unknown
	*/
	getGineikesshoMaxNum(): any
	/**
	* Unknown
	*/
	getSoukesshoNeedNum(): any
	/**
	* Unknown
	*/
	create(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	createMember(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	selectMaterial(a: any, b: any): any
	/**
	* Unknown
	*/
	selectSoukessho(a: any): any
	/**
	* Unknown
	*/
	getMaxRank(): any
	/**
	* Unknown
	*/
	actYubiwadukuri(): any
	/**
	* Unknown
	*/
	getExp(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getSoukesshoItems(): any
	/**
	* Unknown
	*/
	getGineikesshoItems(): any
}
