/**
 * tGameDungeonGenerator.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameDungeonGenerator
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	bossFloors: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	getBaseAttr(): any
	/**
	* Unknown
	*/
	getAppearAttr(): any
	/**
	* Unknown
	*/
	convertData(a: any): any
	/**
	* Unknown
	*/
	createDungeonName(a: any, b: any): any
	/**
	* Unknown
	*/
	getDungeonNameFromDungeonData(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	getDungeonName(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	getKaidanObjectId(a: any, b: any): any
	/**
	* Unknown
	*/
	createEntrance(a: any, b: any): any
	/**
	* Unknown
	*/
	createBossFloor(a: any, b: any): any
	/**
	* Unknown
	*/
	setEntranceEventData(a: any, b: any): any
	/**
	* Unknown
	*/
	setRoad(a: any): any
	/**
	* Unknown
	*/
	jumpDungeonFloor(a: any, b: any, c: any, d: any, e: any, f: any): any
	/**
	* Unknown
	*/
	nextDungeonFloor(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	prevDungeonFloor(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	checkEmptyPosition(a: any, b: any): any
	/**
	* Unknown
	*/
	createFloor(a: any, b: any): any
	/**
	* Unknown
	*/
	isCloseRoom(a: any, b: any): any
	/**
	* Unknown
	*/
	createFloor_field(a: any, b: any): any
	/**
	* Unknown
	*/
	createFloor_maze(a: any, b: any): any
	/**
	* Unknown
	*/
	createFloor_long(a: any, b: any): any
	/**
	* Unknown
	*/
	setMonstorHouse(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	setRestRoom(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	setHogyokuRoom(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	setFishingRoom(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	setOtakaraRoom(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	setShopRoom(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	getRectSpace(a: any, b: any): any
	/**
	* Unknown
	*/
	getRectSpace2(a: any, b: any): any
	/**
	* Unknown
	*/
	getRectSpace2FreeSpace(a: any, b: any): any
	/**
	* Unknown
	*/
	selectItemType(a: any): any
	/**
	* Unknown
	*/
	getFloorItemRank(a: any): any
	/**
	* Unknown
	*/
	setDungeonItem(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	setDungeonPortalEdgeAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	setDungeonChest(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	setDungeonMonsterChest(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	setDungeonHibi(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	setDungeonTrap(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	setDungeonGoodTrap(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	setDungeonJumpTrap(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	setDungeonEnemy(a: any, b: any, c: any, d: any, e: any, f: any, g: any): any
	/**
	* Unknown
	*/
	setDungeonMaterial(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	setDungeonObject(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	setDungeonCantMoveFloor(a: any, b: any, c: any, d: any, e: any, f: any): any
	/**
	* Unknown
	*/
	setDungeonCanMoveFloor(a: any, b: any, c: any, d: any, e: any, f: any): any
	/**
	* Unknown
	*/
	setDungeonDamageFloor(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	setDungeonAdventurerCharactor(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	setDungeonCriminalCharactor(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_crdungeonteleport(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_monsterhouse(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_dungeonautocdt(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_crdungeon3turn(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_yatoboss(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_crdungeon3boss(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_crdungeon7boss(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_crdungeon7boss_bosshp(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_bossgekiha(a: any, b: any): any
	/**
	* Unknown
	*/
	bossgekihaEvent(a: any, b: any): any
	/**
	* Unknown
	*/
	isEnableSetObject(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	isEnableSetObject2(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getMapGimmickFloorInfo(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	getMapGimmickSpace(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	setDungeonTypeMap(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	viewInfoWindow(a: any, b: any): any
	/**
	* Unknown
	*/
	viewViewMapFukidashi(): any
	/**
	* Unknown
	*/
	createSaveFloor(a: any, b: any): any
	/**
	* Unknown
	*/
	createSaveJumpEscFloor(a: any, b: any): any
	/**
	* Unknown
	*/
	changeMap(a: any): any
	/**
	* Unknown
	*/
	getBassgekihaHoushu(a: any): any
	/**
	* Unknown
	*/
	setAutoCdt(a: any, b: any): any
	/**
	* Unknown
	*/
	setSpecialEvent(a: any, b: any): any
	/**
	* Unknown
	*/
	setDungeonEnemy_god2dungeon2(a: any, b: any, c: any, d: any, e: any, f: any): any
	/**
	* Unknown
	*/
	addTargetDungeon(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	loadDungeonJs(a: any, b: any): any
}
