/**
 * tGameRectArea.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameRectArea
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	getRectsOuterPoints(a: any): any
	/**
	* Unknown
	*/
	getRandomRectPosition(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getMoveXY(a: any, b: any): any
	/**
	* Unknown
	*/
	getCoverRect(a: any, b: any): any
	/**
	* Unknown
	*/
	isCrossRect(a: any, b: any): any
	/**
	* Unknown
	*/
	isCrossLine(a: any, b: any, c: any, d: any, e: any, f: any, g: any, h: any, i: any): any
	/**
	* Unknown
	*/
	getCrossPosition(a: any, b: any, c: any, d: any, e: any, f: any, g: any, h: any): any
}
