/**
 * tGameGameOver.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameGameOver
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	setLastInTown(a: any): any
	/**
	* Unknown
	*/
	view(): any
	/**
	* Unknown
	*/
	setPenalty(): any
	/**
	* Unknown
	*/
	revival(): any
	/**
	* Unknown
	*/
	setFrameEvent(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_dispose(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_frame(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_draw(a: any): any
	/**
	* Unknown
	*/
	gameClose(): any
}
