/**
 * tGameK1up.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameK1up
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	hcvs: any
	/**
	* Unknown
	*/
	hctx: any
	/**
	* Unknown
	*/
	uploadMyTownData: any
	/**
	* Unknown
	*/
	listMyTownData: any
	/**
	* Unknown
	*/
	uploadMyAdventurerCharactorData: any
	/**
	* Unknown
	*/
	listMyAdventurerCharactorData: any
	/**
	* Unknown
	*/
	importFaceData: any
	/**
	* Unknown
	*/
	uploadFaceData: any
	/**
	* Unknown
	*/
	listFaceData: any
	/**
	* Unknown
	*/
	importItemData: any
	/**
	* Unknown
	*/
	uploadItemData: any
	/**
	* Unknown
	*/
	listItemData: any
	/**
	* Unknown
	*/
	importChipsetData: any
	/**
	* Unknown
	*/
	uploadChipsetData: any
	/**
	* Unknown
	*/
	listChipsetData: any
	/**
	* Unknown
	*/
	importTalkData: any
	/**
	* Unknown
	*/
	uploadTalkData: any
	/**
	* Unknown
	*/
	listTalkData: any
	/**
	* Unknown
	*/
	manualData: any
	/**
	* Unknown
	*/
	scrollEventData: any
	/**
	* Unknown
	*/
	apiUrl: any
	/**
	* Unknown
	*/
	key: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	getApiUrl(): any
	/**
	* Unknown
	*/
	setText(a: any, b: any): any
	/**
	* Unknown
	*/
	setErrorView(a: any): any
	/**
	* Unknown
	*/
	viewUploadMyTown(a: any, b: any): any
	/**
	* Unknown
	*/
	viewListMyTown(a: any, b: any): any
	/**
	* Unknown
	*/
	viewUploadFace(a: any, b: any): any
	/**
	* Unknown
	*/
	viewListFace(a: any, b: any): any
	/**
	* Unknown
	*/
	viewUploadItem(a: any, b: any): any
	/**
	* Unknown
	*/
	viewListItem(a: any, b: any): any
	/**
	* Unknown
	*/
	viewUploadChipset(a: any, b: any): any
	/**
	* Unknown
	*/
	viewListChipset(a: any, b: any): any
	/**
	* Unknown
	*/
	viewUploadTalk(a: any, b: any): any
	/**
	* Unknown
	*/
	viewListTalk(a: any, b: any): any
	/**
	* Unknown
	*/
	viewImportFace(a: any, b: any): any
	/**
	* Unknown
	*/
	viewImportItem(a: any, b: any): any
	/**
	* Unknown
	*/
	viewImportChipset(a: any, b: any): any
	/**
	* Unknown
	*/
	viewImportTalk(a: any, b: any): any
	/**
	* Unknown
	*/
	viewTitleMenu(a: any): any
	/**
	* Unknown
	*/
	viewUploadMyAdventurerCharactor(a: any, b: any): any
	/**
	* Unknown
	*/
	viewUploadMyAdventurerCharactor2(a: any, b: any): any
	/**
	* Unknown
	*/
	viewListMyAdventurerCharactor(a: any, b: any): any
	/**
	* Unknown
	*/
	initScrollEvent(a: any): any
	/**
	* Unknown
	*/
	setScrollEvent(a: any): any
	/**
	* Unknown
	*/
	isMove(a: any, b: any): any
	/**
	* Unknown
	*/
	viewManualFace(a: any, b: any): any
	/**
	* Unknown
	*/
	viewManualItem(a: any, b: any): any
	/**
	* Unknown
	*/
	viewManualChipset1(a: any, b: any): any
	/**
	* Unknown
	*/
	viewManualChipset2(a: any, b: any): any
	/**
	* Unknown
	*/
	viewManualTalk(a: any, b: any): any
	/**
	* Unknown
	*/
	getOverwriteItemList(): any
	/**
	* Unknown
	*/
	refreshOverwriteItem(a: any, b: any): any
	/**
	* Unknown
	*/
	initSearchBox(a: any): any
	/**
	* Unknown
	*/
	updateSearchForm(a: any): any
}
