/**
 * tGameEquipmentWindow.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameEquipmentWindow
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	textMaxWidth: any
	/**
	* Unknown
	*/
	views: any
	/**
	* Unknown
	*/
	ccvs: any
	/**
	* Unknown
	*/
	cctx: any
	/**
	* Unknown
	*/
	labelFontSize: any
	/**
	* Unknown
	*/
	fontSize: any
	/**
	* Unknown
	*/
	textSpace: any
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	viewItemMaxNum: any
	/**
	* Unknown
	*/
	cursor: any
	/**
	* Unknown
	*/
	equipTypes: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	viewEquipmentWindow(a: any, b: any): any
	/**
	* Unknown
	*/
	drawObject(): any
	/**
	* Unknown
	*/
	getCursor(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_dispose(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_frame(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_draw(a: any): any
	/**
	* Unknown
	*/
	clearCanvas(): any
	/**
	* Unknown
	*/
	setCursor(a: any): any
	/**
	* Unknown
	*/
	viewEquipmentWindowContinue(): any
	/**
	* Unknown
	*/
	selectItem(): any
	/**
	* Unknown
	*/
	viewEquipHikaku(a: any, b: any): any
}
