/**
 * tGameTitleWindow.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameTitleWindow
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	textMaxWidth: any
	/**
	* Unknown
	*/
	views: any
	/**
	* Unknown
	*/
	ccvs: any
	/**
	* Unknown
	*/
	cctx: any
	/**
	* Unknown
	*/
	fontSize: any
	/**
	* Unknown
	*/
	textSpace: any
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	viewItemMaxNum: any
	/**
	* Unknown
	*/
	cursor: any
	/**
	* Unknown
	*/
	clearBottomData: any
	/**
	* Unknown
	*/
	optionClearData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	clear(): any
	/**
	* Unknown
	*/
	viewSaveWindow(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	drawPage(a: any): any
	/**
	* Unknown
	*/
	getCursor(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_dispose(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_frame(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_draw(a: any): any
	/**
	* Unknown
	*/
	clearCanvas(): any
	/**
	* Unknown
	*/
	setCursor(a: any): any
	/**
	* Unknown
	*/
	selectItem(a: any): any
	/**
	* Unknown
	*/
	deleteSave(a: any): any
	/**
	* Unknown
	*/
	updateItems(a: any): any
	/**
	* Unknown
	*/
	newGameBefore(a: any): any
	/**
	* Unknown
	*/
	newGame(a: any, b: any): any
	/**
	* Unknown
	*/
	startNewGame(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	viewError(a: any): any
	/**
	* Unknown
	*/
	checkMismatchSaveData(a: any): any
	/**
	* Unknown
	*/
	checkMismatchVersionSaveData(a: any): any
	/**
	* Unknown
	*/
	checkGameTypeSaveData(a: any): any
	/**
	* Unknown
	*/
	removeOptionInitButton(): any
	/**
	* Unknown
	*/
	setOptionInitButton(): any
	/**
	* Unknown
	*/
	viewOptionInitMenu(): any
}
