/**
 * tGameSlaveShop.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameSlaveShop
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	checkNewItem(a: any): any
	/**
	* Unknown
	*/
	createSlaveCharactor(a: any): any
	/**
	* Unknown
	*/
	buy(a: any): any
}
