/**
 * tGameGamePadEditor.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameGamePadEditor
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	objs: any
	/**
	* Unknown
	*/
	isInit: any
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	gamepadSvgSize: any
	/**
	* Unknown
	*/
	buttons: any
	/**
	* Unknown
	*/
	l2r2Data: any
	/**
	* Unknown
	*/
	init(): any
	/**
	* Unknown
	*/
	initFrame(a: any): any
	/**
	* Unknown
	*/
	viewKeyEditWindow(a: any): any
	/**
	* Unknown
	*/
	viewPressButtonWindow(a: any): any
}
