/**
 * tGameAffectMap.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameAffectMap
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
}
