/**
 * tGameFieldGenerator.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameFieldGenerator
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	csize: any
	/**
	* Unknown
	*/
	fieldEventData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	createMainField(a: any, b: any): any
	/**
	* Unknown
	*/
	createFieldWithLoad(a: any, b: any): any
	/**
	* Unknown
	*/
	dungeonAreasIndex(a: any, b: any): any
	/**
	* Unknown
	*/
	createField(a: any, b: any): any
	/**
	* Unknown
	*/
	setSpreadChipset(a: any, b: any, c: any, d: any, e: any, f: any): any
	/**
	* Unknown
	*/
	setRandomSpreadChipset(a: any): any
	/**
	* Unknown
	*/
	getDungeonAreas(a: any): any
	/**
	* Unknown
	*/
	getRandomTownPositions(a: any): any
	/**
	* Unknown
	*/
	getRandomFreePositions(a: any): any
	/**
	* Unknown
	*/
	inTown(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	inSlum(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	inMyTown(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	inSubTown(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	inNouchi(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	inIkesu(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	inSchool(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	inCastle(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	inEtcTown(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	inDungeon(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	inDungeonFloor1(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	inMaterial(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	updateAllField(): any
	/**
	* Unknown
	*/
	autoCreateTown(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	autoCreateSchool(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	autoCreateCastle(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	autoCreateSlum(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	autoCreateDungeon(a: any, b: any): any
	/**
	* Unknown
	*/
	getRandomDungeonType(a: any): any
	/**
	* Unknown
	*/
	createDungeon(a: any): any
	/**
	* Unknown
	*/
	inQuest1(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	inQuest9(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	inQuest10(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	inQuest12(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	searchTargetObject(a: any, b: any): any
	/**
	* Unknown
	*/
	initFieldEvent(a: any): any
	/**
	* Unknown
	*/
	checkMoveEvent(a: any): any
	/**
	* Unknown
	*/
	checkTalkBossArea(a: any): any
	/**
	* Unknown
	*/
	checkMoveEventForce(a: any): any
	/**
	* Unknown
	*/
	getPlayerPositionChipsetInfo(): any
	/**
	* Unknown
	*/
	getTargetPositionOnemapId(a: any, b: any): any
	/**
	* Unknown
	*/
	getPlayerPositionOnemapId(): any
	/**
	* Unknown
	*/
	emenyEncount(a: any): any
	/**
	* Unknown
	*/
	questEnemyEncount(a: any, b: any): any
	/**
	* Unknown
	*/
	peddlerEncount(a: any): any
	/**
	* Unknown
	*/
	slavetraderEncount(a: any): any
	/**
	* Unknown
	*/
	rescueEncount(a: any): any
	/**
	* Unknown
	*/
	escortEncount(a: any): any
	/**
	* Unknown
	*/
	restEncount(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	kanteiEncount(a: any): any
	/**
	* Unknown
	*/
	seishokushaEncount(a: any): any
	/**
	* Unknown
	*/
	viewFieldMapAction(a: any): any
	/**
	* Unknown
	*/
	choiseRescueCharactor(): any
	/**
	* Unknown
	*/
	choiseEscortCharactor(): any
	/**
	* Unknown
	*/
	clearEncountData(a: any): any
	/**
	* Unknown
	*/
	criminalEncount(a: any, b: any): any
	/**
	* Unknown
	*/
	viewMapCustomMenu(a: any): any
	/**
	* Unknown
	*/
	refreshDungeons(a: any): any
	/**
	* Unknown
	*/
	refreshDungeons2(a: any, b: any): any
	/**
	* Unknown
	*/
	refreshTowns(a: any): any
	/**
	* Unknown
	*/
	refreshSchools(a: any): any
	/**
	* Unknown
	*/
	refreshCastles(a: any): any
	/**
	* Unknown
	*/
	refreshSlums(a: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_checkfaithlow(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_faithlowdungeonfirst(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_maoushutsugen(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_bossareabossgekiha(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_bossareaenemygekiha(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_osoudeath(a: any, b: any): any
	/**
	* Unknown
	*/
	isMaouArea(a: any, b: any): any
	/**
	* Unknown
	*/
	inMaou(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	getTargetMap(a: any): any
	/**
	* Unknown
	*/
	inTargetMap(a: any, b: any): any
	/**
	* Unknown
	*/
	getMapName(a: any, b: any): any
	/**
	* Unknown
	*/
	setMaouTeshitaShutugen(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	createBuilding(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	expandMap(a: any, b: any): any
	/**
	* Unknown
	*/
	createFirstMap(a: any): any
	/**
	* Unknown
	*/
	getRangeMap(a: any): any
	/**
	* Unknown
	*/
	getKakuchoFame(a: any): any
	/**
	* Unknown
	*/
	viewFieldHenkaWindow(a: any): any
	/**
	* Unknown
	*/
	shokinkubidaEncount(a: any): any
	/**
	* Unknown
	*/
	getFieldHenkaBottomData(): any
	/**
	* Unknown
	*/
	createKodaiiseki(a: any, b: any): any
	/**
	* Unknown
	*/
	updateBossArea(a: any): any
	/**
	* Unknown
	*/
	bossAreaEncount(a: any): any
	/**
	* Unknown
	*/
	bossAreaEncount_boss(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	bossAreaEncount_enemy(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	viewBossareaBoard(a: any, b: any): any
	/**
	* Unknown
	*/
	refreshFaith(a: any): any
	/**
	* Unknown
	*/
	shukeiFaith(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	addMapTarget(a: any, b: any): any
	/**
	* Unknown
	*/
	removeMapTarget(a: any, b: any): any
	/**
	* Unknown
	*/
	clearConditionViewField(a: any): any
	/**
	* Unknown
	*/
	setKojiki(a: any): any
	/**
	* Unknown
	*/
	setOsouDeathAction(a: any): any
	/**
	* Unknown
	*/
	fieldCreateRoad(a: any): any
	/**
	* Unknown
	*/
	fixInEtcTown_hogyokuketsugo(a: any): any
}
