/**
 * tGameFaithWindow.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameFaithWindow
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	textMaxWidth: any
	/**
	* Unknown
	*/
	fontSize: any
	/**
	* Unknown
	*/
	textSpace: any
	/**
	* Unknown
	*/
	ccvs: any
	/**
	* Unknown
	*/
	cctx: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	clearCanvas(): any
	/**
	* Unknown
	*/
	view(a: any, b: any): any
}
