/**
 * tGameShortEvent.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameShortEvent
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	chips: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	loadLinkJson(a: any): any
	/**
	* Unknown
	*/
	initChipData(): any
	/**
	* Unknown
	*/
	encount(a: any): any
	/**
	* Unknown
	*/
	drawBackground(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	choise(a: any): any
	/**
	* Unknown
	*/
	choise_allmember(a: any): any
	/**
	* Unknown
	*/
	choise_default(a: any): any
	/**
	* Unknown
	*/
	choise_act(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_escape(a: any, b: any): any
	/**
	* Unknown
	*/
	statusHenka(a: any): any
	/**
	* Unknown
	*/
	escape(a: any): any
	/**
	* Unknown
	*/
	finishNokoru(a: any): any
	/**
	* Unknown
	*/
	finishMessage(a: any, b: any): any
	/**
	* Unknown
	*/
	finishMessage2(a: any, b: any): any
	/**
	* Unknown
	*/
	getRandomCharactor(): any
	/**
	* Unknown
	*/
	getAllMember(): any
	/**
	* Unknown
	*/
	getAroundSpaces(a: any, b: any): any
	/**
	* Unknown
	*/
	getAroundSpacesTargetNum(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getAroundSpace(a: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0001_0001(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0001_0002(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0001_0003(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0002_0001(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0002_0002(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0002_0003(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0003_0001(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0003_0002(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0003_0003(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0004_0001(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0004_0002(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0004_0003(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0005_0001(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0005_0002(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0006_0001(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0006_0002(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0007_0001(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0008_0001(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0009_0001(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0009_0002(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0010_0001(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0010_0002(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0011_0001(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0011_0002(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0012_0001(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0012_0002(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0013_0001(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0013_0002(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0013_0003(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0014_0001(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0015_0001(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0015_0002(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0016_0001(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0017_0001(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0018_0001(a: any, b: any): any
	/**
	* Unknown
	*/
	choise_act_original_act_0018_0002(a: any, b: any): any
}
