/**
 * tGameButsu.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameButsu
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	tryCreate(a: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_butsuevent1(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_butsubossgekiha(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_butsufirst(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_butsuchestopen(a: any, b: any): any
	/**
	* Unknown
	*/
	viewMap(a: any): any
	/**
	* Unknown
	*/
	deleteButsuCharactor(): any
	/**
	* Unknown
	*/
	selectAnswer(a: any): any
	/**
	* Unknown
	*/
	affectAnswer(a: any): any
	/**
	* Unknown
	*/
	calBasho(): any
	/**
	* Unknown
	*/
	affectObject(a: any): any
	/**
	* Unknown
	*/
	inTargetMap(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	createTargetMap(a: any, b: any): any
	/**
	* Unknown
	*/
	setTargetEvent(a: any, b: any): any
	/**
	* Unknown
	*/
	action_playerAffect(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	action_playerAffect2(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	keibiKaiwa(a: any, b: any): any
	/**
	* Unknown
	*/
	keibiEncount(a: any): any
}
