/**
 * tGameCreateWindow.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameCreateWindow
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	viewCreateWindowWithMember(a: any, b: any): any
	/**
	* Unknown
	*/
	viewCreateWindow(a: any, b: any): any
	/**
	* Unknown
	*/
	isCreate(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	viewBottomData(a: any): any
	/**
	* Unknown
	*/
	getSuccessRate(a: any): any
	/**
	* Unknown
	*/
	actCreate(): any
	/**
	* Unknown
	*/
	createResult(a: any, b: any): any
	/**
	* Unknown
	*/
	getExp(a: any, b: any, c: any): any
}
