/**
 * tGameRecipe.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameRecipe
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	masterData: any
	/**
	* Unknown
	*/
	myData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	getLearn(a: any): any
	/**
	* Unknown
	*/
	setLearn(a: any): any
	/**
	* Unknown
	*/
	initData(): any
	/**
	* Unknown
	*/
	initSaveData(): any
	/**
	* Unknown
	*/
	getSaveData(): any
	/**
	* Unknown
	*/
	setSaveData(a: any): any
	/**
	* Unknown
	*/
	getUnlearnedList(a: any): any
}
