/**
 * tGameChikaMakyo.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameChikaMakyo
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	refreshDungeon(): any
	/**
	* Unknown
	*/
	createDungeon(a: any): any
	/**
	* Unknown
	*/
	createChikaMakyo(a: any, b: any): any
	/**
	* Unknown
	*/
	firstGmAccess(a: any): any
	/**
	* Unknown
	*/
	setMaxFloor(a: any): any
	/**
	* Unknown
	*/
	resultGmAccess(a: any): any
	/**
	* Unknown
	*/
	createDungeonFloorEnd(a: any, b: any): any
	/**
	* Unknown
	*/
	getHoshuConvert(a: any): any
}
