/**
 * tGameNaraku.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameNaraku
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	getDungeonLevel(a: any): any
	/**
	* Unknown
	*/
	getDungeonFloorFix(a: any): any
	/**
	* Unknown
	*/
	refreshDungeon(a: any, b: any): any
	/**
	* Unknown
	*/
	createDungeon(a: any): any
	/**
	* Unknown
	*/
	createNaraku(a: any, b: any): any
	/**
	* Unknown
	*/
	getEscapeNextData(): any
}
