/**
 * tGameMamonoJisho.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameMamonoJisho
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	getDungeonTypes(): any
	/**
	* Unknown
	*/
	getDungeonEnemyIds(a: any): any
	/**
	* Unknown
	*/
	getDungeonObjectId(a: any): any
	/**
	* Unknown
	*/
	getTargetEnemyLevel(a: any): any
	/**
	* Unknown
	*/
	getTargetEnemyBaseData(a: any): any
	/**
	* Unknown
	*/
	createcharactor(a: any): any
	/**
	* Unknown
	*/
	getDropItems(a: any): any
	/**
	* Unknown
	*/
	view(a: any, b: any): any
	/**
	* Unknown
	*/
	viewMamonoInfo(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	viewDropItems(a: any, b: any): any
	/**
	* Unknown
	*/
	unlock(a: any, b: any): any
}
