/**
 * tGameData.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameData
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	masterData: any
	/**
	* Unknown
	*/
	myData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	initData(a: any): any
	/**
	* Unknown
	*/
	getDataFlg(a: any): any
	/**
	* Unknown
	*/
	setDataFlg(a: any, b: any): any
	/**
	* Unknown
	*/
	getDataValue(a: any, b: any): any
	/**
	* Unknown
	*/
	setDataValue(a: any, b: any): any
	/**
	* Unknown
	*/
	initSaveData(): any
	/**
	* Unknown
	*/
	getSaveData(): any
	/**
	* Unknown
	*/
	setSaveData(a: any): any
	/**
	* Unknown
	*/
	initFirstDatas(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	addPlayerGiftInfo(a: any): any
}
