/**
 * tGameMyAdventurerCharactor.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameMyAdventurerCharactor
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	max: any
	/**
	* Unknown
	*/
	myData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	initData(): any
	/**
	* Unknown
	*/
	initSaveData(): any
	/**
	* Unknown
	*/
	getSaveData(): any
	/**
	* Unknown
	*/
	setSaveData(a: any): any
	/**
	* Unknown
	*/
	save(a: any): any
	/**
	* Unknown
	*/
	load(a: any): any
	/**
	* Unknown
	*/
	getLocalStorageData(a: any): any
	/**
	* Unknown
	*/
	view(a: any, b: any): any
	/**
	* Unknown
	*/
	convertChara2Mydata(a: any, b: any): any
	/**
	* Unknown
	*/
	convertImport2Mydata(a: any): any
	/**
	* Unknown
	*/
	getItemDescription(a: any, b: any): any
	/**
	* Unknown
	*/
	viewError(a: any): any
	/**
	* Unknown
	*/
	export(a: any, b: any): any
	/**
	* Unknown
	*/
	exportK1up(a: any, b: any): any
	/**
	* Unknown
	*/
	convertTextB64(a: any, b: any): any
	/**
	* Unknown
	*/
	confirmImport(a: any): any
	/**
	* Unknown
	*/
	refreshOverwriteTargets(a: any, b: any): any
	/**
	* Unknown
	*/
	getOverwriteFaceList(): any
	/**
	* Unknown
	*/
	getOverwriteChipsetList(a: any): any
	/**
	* Unknown
	*/
	viewSelectOverwriteTalkTargetWindow(a: any): any
	/**
	* Unknown
	*/
	enableNew(): any
}
