/**
 * tGameGoodTrap.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameGoodTrap
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	convertData(a: any): any
	/**
	* Unknown
	*/
	getTrapToObject(a: any, b: any): any
	/**
	* Unknown
	*/
	getTrapObjectId(a: any): any
	/**
	* Unknown
	*/
	getTrapName(a: any): any
	/**
	* Unknown
	*/
	oneActionTrap(a: any): any
	/**
	* Unknown
	*/
	affect(a: any): any
	/**
	* Unknown
	*/
	runTrap(a: any, b: any): any
	/**
	* Unknown
	*/
	tryBreak(a: any): any
}
