/**
 * tGameEquipRankup.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameEquipRankup
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	getAddRank(): any
	/**
	* Unknown
	*/
	getMaxRank(a: any): any
	/**
	* Unknown
	*/
	getRankupRequireMaterials(a: any): any
	/**
	* Unknown
	*/
	fromEquipment(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	fromEquipmentMember(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	getCanEquipRankup(a: any): any
	/**
	* Unknown
	*/
	selectEquipment(a: any, b: any): any
	/**
	* Unknown
	*/
	getItemIndex(a: any, b: any): any
	/**
	* Unknown
	*/
	getSuccessRate(a: any): any
	/**
	* Unknown
	*/
	actEquipRankup(): any
	/**
	* Unknown
	*/
	equiprankupResult(a: any, b: any): any
	/**
	* Unknown
	*/
	getExp(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	viewBottomData(a: any): any
	/**
	* Unknown
	*/
	isCreate(a: any, b: any, c: any): any
}
