/**
 * tGameHyk.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameHyk
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	targetFont: any
	/**
	* Unknown
	*/
	textMode: any
	/**
	* Unknown
	*/
	timeViewMode: any
	/**
	* Unknown
	*/
	cnvData: any
	/**
	* Unknown
	*/
	logoFileName: any
	/**
	* Unknown
	*/
	textLengthMode: any
	/**
	* Unknown
	*/
	list: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any, b: any): any
	/**
	* Unknown
	*/
	loadLinkJson(a: any): any
	/**
	* Unknown
	*/
	loadLOADDATA(a: any, b: any): any
	/**
	* Unknown
	*/
	getTableStrings(a: any, b: any): any
	/**
	* Unknown
	*/
	getTableString__default(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getTableString__talk(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getTableString__talkevent(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getTableString__askill(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getTableString__charactor(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getTableString__kucho(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getTableString__item(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getTableString__job(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getTableString__map(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getTableString__mapeditor(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getTableString__name(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getTableString__poker(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getTableString__shortevent(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getTableString__skill(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getTableString__war(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getTableString__help(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	addExCsvs(a: any, b: any): any
	/**
	* Unknown
	*/
	importLanguageCsv(a: any): any
	/**
	* Unknown
	*/
	reflectLanguageLOADDATA(a: any, b: any): any
	/**
	* Unknown
	*/
	createMonsterList(): any
}
