/**
 * tGameMyTown.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameMyTown
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	getTargetMapCharaNum(a: any, b: any): any
	/**
	* Unknown
	*/
	isHomeMyTownSubTown(a: any): any
	/**
	* Unknown
	*/
	isInHomeMyTownSubTown(a: any): any
	/**
	* Unknown
	*/
	getMyTownName(): any
	/**
	* Unknown
	*/
	getChipData(a: any): any
	/**
	* Unknown
	*/
	setMyTown(a: any, b: any): any
	/**
	* Unknown
	*/
	createMyTownWithLoad(a: any, b: any): any
	/**
	* Unknown
	*/
	moveMyTown(a: any): any
	/**
	* Unknown
	*/
	createMyTown(a: any, b: any): any
	/**
	* Unknown
	*/
	actionPattern(a: any): any
	/**
	* Unknown
	*/
	updateActionPattern(a: any): any
	/**
	* Unknown
	*/
	actionPatternOne(a: any): any
	/**
	* Unknown
	*/
	viewMenuWindow(a: any): any
	/**
	* Unknown
	*/
	gotoMyTown(a: any, b: any): any
	/**
	* Unknown
	*/
	checkUpdateMap(a: any): any
	/**
	* Unknown
	*/
	affectCharactor(a: any): any
	/**
	* Unknown
	*/
	joinReleaseRecipe(a: any): any
	/**
	* Unknown
	*/
	isMyTownNakamaType(a: any): any
	/**
	* Unknown
	*/
	getMyTownNakamaType(a: any): any
	/**
	* Unknown
	*/
	getMyTownNakamaCtype(a: any): any
	/**
	* Unknown
	*/
	setNightBgmMenu(a: any): any
}
