/**
 * tGameMapEditor.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameMapEditor
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	objs: any
	/**
	* Unknown
	*/
	data: any
	/**
	* Unknown
	*/
	isInit: any
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	scrollBarMinSize: any
	/**
	* Unknown
	*/
	screenSize: any
	/**
	* Unknown
	*/
	objectPos: any
	/**
	* Unknown
	*/
	templateData: any
	/**
	* Unknown
	*/
	events: any
	/**
	* Unknown
	*/
	myData: any
	/**
	* Unknown
	*/
	historyMax: any
	/**
	* Unknown
	*/
	editorHeight: any
	/**
	* Unknown
	*/
	selectTargetCharactorCache: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	getLearnObject(a: any): any
	/**
	* Unknown
	*/
	setLearnObject(a: any): any
	/**
	* Unknown
	*/
	getLearnTemplate(a: any): any
	/**
	* Unknown
	*/
	setLearnTemplate(a: any): any
	/**
	* Unknown
	*/
	initSaveData(): any
	/**
	* Unknown
	*/
	getSaveData(): any
	/**
	* Unknown
	*/
	setSaveData(a: any): any
	/**
	* Unknown
	*/
	initData(): any
	/**
	* Unknown
	*/
	viewEditor(a: any): any
	/**
	* Unknown
	*/
	updateConvertMapData(): any
	/**
	* Unknown
	*/
	setFrameEvent(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_dispose(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_frame(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_draw(a: any): any
	/**
	* Unknown
	*/
	keyEvent(): any
	/**
	* Unknown
	*/
	viewCanvasCursor(a: any, b: any): any
	/**
	* Unknown
	*/
	getCanvasCursorPosition(): any
	/**
	* Unknown
	*/
	setBackground(a: any, b: any): any
	/**
	* Unknown
	*/
	setObject(a: any, b: any): any
	/**
	* Unknown
	*/
	moveObject(a: any): any
	/**
	* Unknown
	*/
	viewEditorBackgroundCursor(): any
	/**
	* Unknown
	*/
	setScrollBar(): any
	/**
	* Unknown
	*/
	getScrollBarInfo(): any
	/**
	* Unknown
	*/
	addScrollBarPosition(a: any, b: any): any
	/**
	* Unknown
	*/
	setScrollBarPosition(a: any): any
	/**
	* Unknown
	*/
	setScrollPosition(): any
	/**
	* Unknown
	*/
	setScale(a: any): any
	/**
	* Unknown
	*/
	setMode(a: any): any
	/**
	* Unknown
	*/
	viewEditorObjectCursor(): any
	/**
	* Unknown
	*/
	viewObjectMenu(a: any): any
	/**
	* Unknown
	*/
	hiddenObjectMenu(): any
	/**
	* Unknown
	*/
	actionCancel(): any
	/**
	* Unknown
	*/
	actionRegist(): any
	/**
	* Unknown
	*/
	viewLock(): any
	/**
	* Unknown
	*/
	hiddenLock(): any
	/**
	* Unknown
	*/
	selectTargetCharactor(a: any, b: any): any
	/**
	* Unknown
	*/
	isEnableObject(a: any): any
	/**
	* Unknown
	*/
	isEnableTemplate(a: any): any
	/**
	* Unknown
	*/
	drawEditorObject(): any
	/**
	* Unknown
	*/
	changeSelectTemplate(): any
	/**
	* Unknown
	*/
	setTemplate(a: any, b: any): any
	/**
	* Unknown
	*/
	selectObjectType(a: any, b: any): any
	/**
	* Unknown
	*/
	getHouses(): any
	/**
	* Unknown
	*/
	setLearnTemplateObject(a: any): any
	/**
	* Unknown
	*/
	initObjectSelectorPosition(): any
	/**
	* Unknown
	*/
	updateTemplateDisabled(): any
	/**
	* Unknown
	*/
	clearMap(a: any): any
	/**
	* Unknown
	*/
	viewConfirm(a: any): any
	/**
	* Unknown
	*/
	releaseAllRecipe(): any
	/**
	* Unknown
	*/
	addHistory(): any
	/**
	* Unknown
	*/
	changeHistory(a: any): any
	/**
	* Unknown
	*/
	updateHistoryButton(): any
	/**
	* Unknown
	*/
	callBackClearViewData(): any
	/**
	* Unknown
	*/
	editorToggle(a: any): any
	/**
	* Unknown
	*/
	actionRightClick(a: any): any
	/**
	* Unknown
	*/
	clearObjectLongTapTimer(): any
}
