/**
 * tGameYukigassen.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameYukigassen
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	tryMap(a: any): any
	/**
	* Unknown
	*/
	createMap(): any
	/**
	* Unknown
	*/
	affect(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	isHoshu(): any
	/**
	* Unknown
	*/
	hoshu(a: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_createyukigassen(a: any, b: any): any
}
