/**
 * tGameNumWindow.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameNumWindow
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	textMaxWidth: any
	/**
	* Unknown
	*/
	views: any
	/**
	* Unknown
	*/
	ccvs: any
	/**
	* Unknown
	*/
	cctx: any
	/**
	* Unknown
	*/
	fontSize: any
	/**
	* Unknown
	*/
	inputFontSize: any
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	cursor: any
	/**
	* Unknown
	*/
	textBox: any
	/**
	* Unknown
	*/
	keypadData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	isEnableKeypad(): any
	/**
	* Unknown
	*/
	inputKeypad(a: any): any
	/**
	* Unknown
	*/
	viewNumWindow(a: any, b: any): any
	/**
	* Unknown
	*/
	setFrameEvent(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_dispose(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_frame(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_draw(a: any): any
	/**
	* Unknown
	*/
	clearCanvas(): any
	/**
	* Unknown
	*/
	setNum(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getInputValue(): any
}
