/**
 * tGameParts.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameParts
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	cvs: any
	/**
	* Unknown
	*/
	ctx: any
	/**
	* Unknown
	*/
	init(): any
	/**
	* Unknown
	*/
	createProgressBar(a: any, b: any, c: any, d: any, e: any, f: any): any
}
