/**
 * tGameDairyQuest.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameDairyQuest
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	tryRefresh(): any
	/**
	* Unknown
	*/
	refreshQuest(): any
	/**
	* Unknown
	*/
	createQuest(a: any, b: any): any
	/**
	* Unknown
	*/
	viewWindow(a: any, b: any): any
	/**
	* Unknown
	*/
	getWindowData(a: any, b: any): any
	/**
	* Unknown
	*/
	addCount(a: any, b: any): any
}
