/**
 * tGameAllocateStatusWindow.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameAllocateStatusWindow
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	textMaxWidth: any
	/**
	* Unknown
	*/
	views: any
	/**
	* Unknown
	*/
	ccvs: any
	/**
	* Unknown
	*/
	cctx: any
	/**
	* Unknown
	*/
	fontSize: any
	/**
	* Unknown
	*/
	textSpace: any
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	cursor: any
	/**
	* Unknown
	*/
	targets: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	clear(): any
	/**
	* Unknown
	*/
	viewSetWindow(a: any, b: any): any
	/**
	* Unknown
	*/
	view(a: any, b: any): any
	/**
	* Unknown
	*/
	drawPage(a: any): any
	/**
	* Unknown
	*/
	getCursor(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_dispose(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_frame(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_draw(a: any): any
	/**
	* Unknown
	*/
	clearCanvas(): any
	/**
	* Unknown
	*/
	setCursor(a: any): any
	/**
	* Unknown
	*/
	drawSelectColumnData(a: any, b: any): any
	/**
	* Unknown
	*/
	changeSelectColumnItem(a: any): any
	/**
	* Unknown
	*/
	drawColumnData(a: any, b: any): any
	/**
	* Unknown
	*/
	okButtonColumnItem(a: any): any
	/**
	* Unknown
	*/
	viewPoint(): any
}
