/**
 * tGameEditMember.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameEditMember
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	hiddenCanvases: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	view(a: any): any
	/**
	* Unknown
	*/
	viewConfirm(a: any): any
}
