/**
 * tGameCharactorData.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameCharactorData
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	characotrData: any
	/**
	* Unknown
	*/
	allocateStatusData: any
	/**
	* Unknown
	*/
	allocateStatusVals: any
	/**
	* Unknown
	*/
	allocateStatusIdxs: any
	/**
	* Unknown
	*/
	randomEnemySheet: any
	/**
	* Unknown
	*/
	randomBossSheets: any
	/**
	* Unknown
	*/
	randomSlaveSheet: any
	/**
	* Unknown
	*/
	randomRaceEnemySheet: any
	/**
	* Unknown
	*/
	randomRaceBossSheets: any
	/**
	* Unknown
	*/
	skillExpRange: any
	/**
	* Unknown
	*/
	elv: any
	/**
	* Unknown
	*/
	elv2: any
	/**
	* Unknown
	*/
	belv: any
	/**
	* Unknown
	*/
	belv2: any
	/**
	* Unknown
	*/
	selv: any
	/**
	* Unknown
	*/
	selv2: any
	/**
	* Unknown
	*/
	bselv: any
	/**
	* Unknown
	*/
	bselv2: any
	/**
	* Unknown
	*/
	kelv: any
	/**
	* Unknown
	*/
	kelv2: any
	/**
	* Unknown
	*/
	kbelv: any
	/**
	* Unknown
	*/
	kbelv2: any
	/**
	* Unknown
	*/
	kselv: any
	/**
	* Unknown
	*/
	kselv2: any
	/**
	* Unknown
	*/
	kbselv: any
	/**
	* Unknown
	*/
	kbselv2: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	setLevel(a: any, b: any): any
	/**
	* Unknown
	*/
	isHiddenStatus(a: any): any
	/**
	* Unknown
	*/
	getCharactorData(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	getSkillName(a: any): any
	/**
	* Unknown
	*/
	getItem(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	setEquipment(a: any, b: any, c: any, d: any, e: any, f: any): any
	/**
	* Unknown
	*/
	getLevelToRank(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getRankToLevel(a: any): any
	/**
	* Unknown
	*/
	setEquipment_quality(a: any, b: any): any
	/**
	* Unknown
	*/
	setEquipment_weapons(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	setEquipment_lweapons(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	setEquipment_armors(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	setRandomEnemySheet(): any
	/**
	* Unknown
	*/
	setRandomRaceEnemySheet(): any
	/**
	* Unknown
	*/
	setRandomBossSheet(): any
	/**
	* Unknown
	*/
	setRandomRaceBossSheet(): any
	/**
	* Unknown
	*/
	setRandomSlaveSheet(): any
	/**
	* Unknown
	*/
	createRandomEnemy(a: any): any
	/**
	* Unknown
	*/
	createRandomRaceEnemy(a: any): any
	/**
	* Unknown
	*/
	getRandomBossId2(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getRandomBossId(a: any, b: any): any
	/**
	* Unknown
	*/
	createRandomSlaveId(a: any): any
	/**
	* Unknown
	*/
	getAllocateStatusSheet(a: any): any
	/**
	* Unknown
	*/
	setAllocateStatusTargetLevel(a: any): any
	/**
	* Unknown
	*/
	setAllocateStatusRandom(a: any, b: any): any
	/**
	* Unknown
	*/
	getAllocateStatusGetPoint(a: any): any
	/**
	* Unknown
	*/
	setSkills(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	setAskills(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	convertTypeToQuality(a: any): any
	/**
	* Unknown
	*/
	convertTypeToTarget(a: any): any
	/**
	* Unknown
	*/
	getJobBaseStatus(a: any): any
	/**
	* Unknown
	*/
	getFavoriteItems(): any
	/**
	* Unknown
	*/
	convertActionSkillLevel(a: any): any
	/**
	* Unknown
	*/
	setSpecialEquipment(a: any): any
	/**
	* Unknown
	*/
	getRaceNums(a: any): any
	/**
	* Unknown
	*/
	get_elv(): any
	/**
	* Unknown
	*/
	get_elv2(): any
	/**
	* Unknown
	*/
	get_belv(): any
	/**
	* Unknown
	*/
	get_belv2(): any
	/**
	* Unknown
	*/
	get_selv(): any
	/**
	* Unknown
	*/
	get_selv2(): any
	/**
	* Unknown
	*/
	get_bselv(): any
	/**
	* Unknown
	*/
	get_bselv2(): any
}
