/**
 * tGameSoundResource.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameSoundResource
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	soundData: any
	/**
	* Unknown
	*/
	playSounds: any
	/**
	* Unknown
	*/
	oggOrM4a: any
	/**
	* Unknown
	*/
	caches: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	loadSound(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	allLoad(a: any): any
	/**
	* Unknown
	*/
	getAudio(a: any): any
	/**
	* Unknown
	*/
	loadPreload(a: any): any
	/**
	* Unknown
	*/
	getPath(a: any): any
	/**
	* Unknown
	*/
	loadBuffer(a: any): any
	/**
	* Unknown
	*/
	play(a: any, b: any): any
	/**
	* Unknown
	*/
	setVolume(a: any): any
	/**
	* Unknown
	*/
	reflectOption(a: any): any
}
