/**
 * tGameItem.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameItem
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	masterData: any
	/**
	* Unknown
	*/
	egoMaxLength: any
	/**
	* Unknown
	*/
	rankItems: any
	/**
	* Unknown
	*/
	rankShopItems: any
	/**
	* Unknown
	*/
	rankEquips: any
	/**
	* Unknown
	*/
	rankShopEquips: any
	/**
	* Unknown
	*/
	rankCharactorEquips: any
	/**
	* Unknown
	*/
	rankChestEquips: any
	/**
	* Unknown
	*/
	rareRandomRates: any
	/**
	* Unknown
	*/
	spaceFraction: any
	/**
	* Unknown
	*/
	juryokaMax: any
	/**
	* Unknown
	*/
	itemNameMax: any
	/**
	* Unknown
	*/
	equipAbilities: any
	/**
	* Unknown
	*/
	atkIdxs: any
	/**
	* Unknown
	*/
	equipAbilityIds: any
	/**
	* Unknown
	*/
	equipMaxRank: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	setItemCharacteristic(): any
	/**
	* Unknown
	*/
	getItemCharactorUse(a: any): any
	/**
	* Unknown
	*/
	getItemCharacteristic(a: any): any
	/**
	* Unknown
	*/
	getItemMapType(a: any): any
	/**
	* Unknown
	*/
	getItemWatasu(a: any): any
	/**
	* Unknown
	*/
	getItemOshitsukeru(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getItemHikitsugi(a: any): any
	/**
	* Unknown
	*/
	getItemRare(a: any): any
	/**
	* Unknown
	*/
	getSimpleItemName(a: any): any
	/**
	* Unknown
	*/
	getItemName(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	getEnableGroupItem(a: any): any
	/**
	* Unknown
	*/
	getItemRank(a: any): any
	/**
	* Unknown
	*/
	getItemSpaceMaster(a: any): any
	/**
	* Unknown
	*/
	getItemPriceMaster(a: any, b: any): any
	/**
	* Unknown
	*/
	getItemPrice(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	getItemSpace(a: any): any
	/**
	* Unknown
	*/
	getItemDescriptionSub(a: any): any
	/**
	* Unknown
	*/
	getItemDescription(a: any): any
	/**
	* Unknown
	*/
	getItemData(a: any): any
	/**
	* Unknown
	*/
	convertData(a: any): any
	/**
	* Unknown
	*/
	convertDataFix(a: any): any
	/**
	* Unknown
	*/
	getFixCloneItem(a: any): any
	/**
	* Unknown
	*/
	getMoneyItem(a: any, b: any): any
	/**
	* Unknown
	*/
	getItemToObject(a: any, b: any): any
	/**
	* Unknown
	*/
	affect(a: any): any
	/**
	* Unknown
	*/
	getEnableEquipCalData(a: any): any
	/**
	* Unknown
	*/
	getEnableEquipItems(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	checkCompileItem(a: any, b: any): any
	/**
	* Unknown
	*/
	getItemSkill(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getItemSkill_1(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getItemSkill_2(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getItemSkill_3(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getItemSkill_5(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getItemSkill_6(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getItemSkill_9(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getItemSkill_14(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getItemSkill_17(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getItemSkill_19(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getItemSkill_21(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getItemSkill_22(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getRandomShikibetsu(a: any): any
	/**
	* Unknown
	*/
	createRandomItem(a: any): any
	/**
	* Unknown
	*/
	createRandomEquipment(a: any): any
	/**
	* Unknown
	*/
	createRandomChestItem(a: any): any
	/**
	* Unknown
	*/
	createRandomChestEquipment(a: any): any
	/**
	* Unknown
	*/
	createMeetItem(a: any): any
	/**
	* Unknown
	*/
	createRandomFoodItem(a: any): any
	/**
	* Unknown
	*/
	createItem(a: any): any
	/**
	* Unknown
	*/
	convertRankEquipment(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	setEquipmentAccessoryData(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	updateEquipmentName(a: any): any
	/**
	* Unknown
	*/
	updateEquipmentTargetName(a: any, b: any): any
	/**
	* Unknown
	*/
	getEnchantmentedItem(a: any): any
	/**
	* Unknown
	*/
	getEnchantmentValues(a: any, b: any): any
	/**
	* Unknown
	*/
	getEquipSkillValues(a: any, b: any): any
	/**
	* Unknown
	*/
	getEnchantmentTypeIndex(a: any): any
	/**
	* Unknown
	*/
	getEnableEnchantmentList(a: any, b: any): any
	/**
	* Unknown
	*/
	getEnableEquipSkillList(a: any, b: any): any
	/**
	* Unknown
	*/
	setEquipmentQualityEnchantment(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	setEquipmentQualitySkill(a: any, b: any): any
	/**
	* Unknown
	*/
	setEquipmentCounterAskill(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	createEquipment(a: any): any
	/**
	* Unknown
	*/
	useSpecialItem(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	noroitaiseiPlusItem(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	noroitaiseiMinusItem(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	jakukataiseiPlusItem(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	jakukataiseiMinusItem(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	equipmentPlus(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	equipmentMinus(a: any, b: any, c: any, d: any, e: any, f: any): any
	/**
	* Unknown
	*/
	kanteiItem(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	mikanteiItem(a: any, b: any): any
	/**
	* Unknown
	*/
	noroikeshiItem(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	noroiItem(a: any, b: any, c: any, d: any, e: any, f: any): any
	/**
	* Unknown
	*/
	getItemTextColorCode(a: any): any
	/**
	* Unknown
	*/
	getItemUseMessage(a: any): any
	/**
	* Unknown
	*/
	usedFootItem(a: any): any
	/**
	* Unknown
	*/
	removeFootItem(a: any, b: any): any
	/**
	* Unknown
	*/
	getEquipAbilitiesData(a: any): any
	/**
	* Unknown
	*/
	setRankItems(): any
	/**
	* Unknown
	*/
	createEquipmentQuality(): any
	/**
	* Unknown
	*/
	createShopEquipmentQuality(): any
	/**
	* Unknown
	*/
	selectItemType(a: any): any
	/**
	* Unknown
	*/
	getEquipItemMaster(a: any, b: any): any
	/**
	* Unknown
	*/
	getEquipmentEnchantmentPriceValues(a: any): any
	/**
	* Unknown
	*/
	getEquipmentSkillPriceValues(a: any): any
	/**
	* Unknown
	*/
	getEquipmentCounterAskillPriceValues(a: any): any
	/**
	* Unknown
	*/
	getEquipmentKyushuPriceValues(a: any): any
	/**
	* Unknown
	*/
	sortItem(a: any): any
	/**
	* Unknown
	*/
	createCharactorEquipmentItem(a: any): any
	/**
	* Unknown
	*/
	createCharactorEquipmentSpecialItem(a: any): any
	/**
	* Unknown
	*/
	getEquipmentPerformanceValue(a: any): any
	/**
	* Unknown
	*/
	createMaterialItems(a: any): any
	/**
	* Unknown
	*/
	getFootItemMessage(a: any): any
	/**
	* Unknown
	*/
	getItemNamesMessage(a: any): any
	/**
	* Unknown
	*/
	setRareRandomRates(): any
	/**
	* Unknown
	*/
	getRareRandomRateItem(): any
	/**
	* Unknown
	*/
	convertTargetRankEquipment(a: any, b: any): any
	/**
	* Unknown
	*/
	equipRankupItem(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	askillLevelupItem(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	equipmentRename(a: any, b: any): any
	/**
	* Unknown
	*/
	equipmentChangeChip(a: any, b: any): any
	/**
	* Unknown
	*/
	askillRename(a: any, b: any): any
	/**
	* Unknown
	*/
	askillRename_act(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	jobRename(a: any, b: any): any
	/**
	* Unknown
	*/
	zentaishiji(a: any, b: any): any
	/**
	* Unknown
	*/
	getEquipmentDiff(a: any, b: any): any
	/**
	* Unknown
	*/
	getCharaItemAskillRank(a: any, b: any): any
	/**
	* Unknown
	*/
	getKodaiisekiItem(a: any): any
	/**
	* Unknown
	*/
	equipmentKeiryoka(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	equipmentJuryoka(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	getHoseiLevel(a: any, b: any): any
	/**
	* Unknown
	*/
	getWeaponMainZokusei(a: any): any
	/**
	* Unknown
	*/
	createLockID(): any
	/**
	* Unknown
	*/
	setLock(a: any, b: any): any
	/**
	* Unknown
	*/
	clearLock(a: any, b: any): any
	/**
	* Unknown
	*/
	isLock(a: any, b: any): any
	/**
	* Unknown
	*/
	getLockId(a: any): any
	/**
	* Unknown
	*/
	setLockId(a: any): any
	/**
	* Unknown
	*/
	isEquipmentItem(a: any): any
	/**
	* Unknown
	*/
	getItemSkill_checkReuseItem(a: any): any
	/**
	* Unknown
	*/
	actEquipPlus(a: any, b: any): any
}
