/**
 * tGameJashin.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameJashin
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	createEventDungeon(): any
	/**
	* Unknown
	*/
	viewAdventureGuildBoard(a: any, b: any): any
	/**
	* Unknown
	*/
	viewAdventureGuildBoard2(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_jashinboss(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_jashinboss2(a: any, b: any): any
	/**
	* Unknown
	*/
	createBossFloor(a: any): any
	/**
	* Unknown
	*/
	affectZou(a: any, b: any): any
}
