/**
 * tGameCreateUniqueCharactor.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameCreateUniqueCharactor
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	addCharactors(): any
	/**
	* Unknown
	*/
	addMegamiCharactor(a: any): any
	/**
	* Unknown
	*/
	addShushin1Charactor(a: any): any
	/**
	* Unknown
	*/
	addShushin2Charactor(a: any): any
	/**
	* Unknown
	*/
	addYushaCharactor(a: any): any
	/**
	* Unknown
	*/
	addElfSisterCharactor(a: any): any
	/**
	* Unknown
	*/
	addElfBrotherCharactor(a: any): any
	/**
	* Unknown
	*/
	addKenkyujoShochoCharactor(a: any): any
	/**
	* Unknown
	*/
	addMagicalGirlCharactor(a: any): any
	/**
	* Unknown
	*/
	addMagicalGirl2Charactor(a: any): any
	/**
	* Unknown
	*/
	addJiiCharactor(a: any): any
	/**
	* Unknown
	*/
	addMikohimeCharactor(a: any): any
	/**
	* Unknown
	*/
	addOshitsukeCharactor(a: any): any
}
