/**
 * tGameRoutineMap.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameRoutineMap
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	isRequireCanvasRefresh: any
	/**
	* Unknown
	*/
	refreshData: any
	/**
	* Unknown
	*/
	viewMapData: any
	/**
	* Unknown
	*/
	mode: any
	/**
	* Unknown
	*/
	modeData: any
	/**
	* Unknown
	*/
	player: any
	/**
	* Unknown
	*/
	oneActionData: any
	/**
	* Unknown
	*/
	isAction: any
	/**
	* Unknown
	*/
	frameActionEvent: any
	/**
	* Unknown
	*/
	frameKey: any
	/**
	* Unknown
	*/
	isDisposeClearPressKeys: any
	/**
	* Unknown
	*/
	moveCache: any
	/**
	* Unknown
	*/
	beforeSmallMapSize: any
	/**
	* Unknown
	*/
	cutActionWaitTimeRate: any
	/**
	* Unknown
	*/
	isOverCanvasView: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initSaveData(): any
	/**
	* Unknown
	*/
	getSaveData(): any
	/**
	* Unknown
	*/
	setSaveData(a: any): any
	/**
	* Unknown
	*/
	setForceStopCallBack(a: any): any
	/**
	* Unknown
	*/
	deleteForceStopCallBack(a: any): any
	/**
	* Unknown
	*/
	issetForceStopCallBack(): any
	/**
	* Unknown
	*/
	setFrameAction(a: any): any
	/**
	* Unknown
	*/
	frameAction_dispose(a: any): any
	/**
	* Unknown
	*/
	frameAction_frame(a: any): any
	/**
	* Unknown
	*/
	frameAction_draw(a: any, b: any): any
	/**
	* Unknown
	*/
	updateLastConvertMapData(a: any): any
	/**
	* Unknown
	*/
	clearOneActionSyncAction(): any
	/**
	* Unknown
	*/
	oneAction(a: any, b: any, c: any, d: any, e: any, f: any): any
	/**
	* Unknown
	*/
	oneActionAfterFinishAction(a: any): any
	/**
	* Unknown
	*/
	oneActionAfter(a: any): any
	/**
	* Unknown
	*/
	viewEffectLog(a: any): any
	/**
	* Unknown
	*/
	oneActionForce(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionWalkAnimation(a: any): any
	/**
	* Unknown
	*/
	oneActionWalk(a: any): any
	/**
	* Unknown
	*/
	updateLookMap(a: any): any
	/**
	* Unknown
	*/
	convertObjectLookMap(a: any): any
	/**
	* Unknown
	*/
	updateLookMapTarget(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	updateLookMapAll(): any
	/**
	* Unknown
	*/
	updateLookMapDarkAll(): any
	/**
	* Unknown
	*/
	updateFovTargets(): any
	/**
	* Unknown
	*/
	viewSmallMap(a: any): any
	/**
	* Unknown
	*/
	affectTarget(a: any): any
	/**
	* Unknown
	*/
	clearDiaonalCanvas(): any
	/**
	* Unknown
	*/
	drawArrow(): any
	/**
	* Unknown
	*/
	setMode(a: any, b: any): any
	/**
	* Unknown
	*/
	getFootMessageData(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	viewPlayerPositionLog(): any
	/**
	* Unknown
	*/
	viewPlayerPositionOverlookLog(): any
	/**
	* Unknown
	*/
	getCanMovePositions(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	viewMap(a: any, b: any, c: any, d: any, e: any, f: any): any
	/**
	* Unknown
	*/
	viewMap_action(a: any, b: any, c: any, d: any, e: any, f: any): any
	/**
	* Unknown
	*/
	viewMapEvent(a: any): any
	/**
	* Unknown
	*/
	setPlayerPosition(a: any, b: any): any
	/**
	* Unknown
	*/
	drawForce(a: any): any
	/**
	* Unknown
	*/
	edgeMove(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getMapType(): any
	/**
	* Unknown
	*/
	actionPlayerAutoTurn(a: any): any
	/**
	* Unknown
	*/
	breakMap(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	checkPlayerTeamTimeLimit(a: any): any
	/**
	* Unknown
	*/
	getPositionAffectList(a: any, b: any): any
	/**
	* Unknown
	*/
	addFinishAction(a: any): any
	/**
	* Unknown
	*/
	yubakuAction(a: any, b: any): any
	/**
	* Unknown
	*/
	attackDamageAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	attackKaihiAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	etcAfterAction(a: any, b: any): any
	/**
	* Unknown
	*/
	updateMapCharactorStatus(): any
	/**
	* Unknown
	*/
	updateMapInfoAll(a: any): any
	/**
	* Unknown
	*/
	isInViewFrame(a: any, b: any): any
	/**
	* Unknown
	*/
	playerDeathEvent(): any
	/**
	* Unknown
	*/
	kanpaAction(a: any): any
	/**
	* Unknown
	*/
	viewLinkMap(a: any): any
	/**
	* Unknown
	*/
	viewBackLinkMap(a: any): any
	/**
	* Unknown
	*/
	playerAutoFootPickupItem(): any
	/**
	* Unknown
	*/
	checkSpecialFlg(a: any, b: any): any
	/**
	* Unknown
	*/
	getUtime(): any
	/**
	* Unknown
	*/
	setTurnTimeFrameAction(a: any, b: any): any
	/**
	* Unknown
	*/
	changeOverCanvasView(a: any): any
	/**
	* Unknown
	*/
	setAutoOnmitsu(a: any): any
}
