/**
 * tGameLoading2.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameLoading2
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	targets: any
	/**
	* Unknown
	*/
	errorHeightMin: any
	/**
	* Unknown
	*/
	init(): any
	/**
	* Unknown
	*/
	initObjs(a: any): any
	/**
	* Unknown
	*/
	searchTarget(a: any): any
	/**
	* Unknown
	*/
	view(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	hidden(a: any): any
}
