/**
 * tGameOptionWindow.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameOptionWindow
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	viewOptionWindow(a: any, b: any): any
	/**
	* Unknown
	*/
	viewOptionWindow2(a: any, b: any): any
	/**
	* Unknown
	*/
	viewOptionWindow3(a: any, b: any): any
	/**
	* Unknown
	*/
	viewSysOptWindow(a: any, b: any): any
}
