/**
 * tGameKeyboard.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameKeyboard
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	simplePressKeys: any
	/**
	* Unknown
	*/
	forcePressKeys: any
	/**
	* Unknown
	*/
	pressKeyLimitTime: any
	/**
	* Unknown
	*/
	pressKeyClickTime: any
	/**
	* Unknown
	*/
	pressKeyDoubleClickTime: any
	/**
	* Unknown
	*/
	pressKeyPressTime: any
	/**
	* Unknown
	*/
	longPressKeyPressTime: any
	/**
	* Unknown
	*/
	pressKeys: any
	/**
	* Unknown
	*/
	pressNaturalKeys: any
	/**
	* Unknown
	*/
	keymapData: any
	/**
	* Unknown
	*/
	keymapDataDefault: any
	/**
	* Unknown
	*/
	isPreventDefault: any
	/**
	* Unknown
	*/
	isEnableBlock: any
	/**
	* Unknown
	*/
	keydown: any
	/**
	* Unknown
	*/
	keyup: any
	/**
	* Unknown
	*/
	init(): any
	/**
	* Unknown
	*/
	loadKeyMap(a: any): any
	/**
	* Unknown
	*/
	initEvent(a: any): any
	/**
	* Unknown
	*/
	calKey(): any
	/**
	* Unknown
	*/
	frameAction(a: any): any
	/**
	* Unknown
	*/
	isForceDown(a: any): any
	/**
	* Unknown
	*/
	isDown(a: any): any
	/**
	* Unknown
	*/
	isDoubleDown(a: any): any
	/**
	* Unknown
	*/
	isClick(a: any): any
	/**
	* Unknown
	*/
	isDoubleClick(a: any): any
	/**
	* Unknown
	*/
	isPress(a: any): any
	/**
	* Unknown
	*/
	isDoublePress(a: any): any
	/**
	* Unknown
	*/
	isLongPress(a: any): any
	/**
	* Unknown
	*/
	isWordClick(a: any): any
	/**
	* Unknown
	*/
	clearPressKeys(): any
	/**
	* Unknown
	*/
	getDownKeys(): any
	/**
	* Unknown
	*/
	setEnablePreventDefault(): any
	/**
	* Unknown
	*/
	setDisablePreventDefault(): any
	/**
	* Unknown
	*/
	sendKeyDown(a: any): any
	/**
	* Unknown
	*/
	sendKeyUp(a: any): any
}
