/**
 * tGameUniqueQuest.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameUniqueQuest
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	viewMap(a: any): any
	/**
	* Unknown
	*/
	tryCreate(a: any): any
	/**
	* Unknown
	*/
	tryCreate_kantei(a: any): any
	/**
	* Unknown
	*/
	tryCreate_guild(a: any): any
	/**
	* Unknown
	*/
	tryCreate_ryoriya(a: any): any
	/**
	* Unknown
	*/
	tryCreate_mahouten(a: any): any
	/**
	* Unknown
	*/
	tryCreate_sakaba(a: any): any
	/**
	* Unknown
	*/
	tryCreate_seishokusha(a: any): any
	/**
	* Unknown
	*/
	tryCreate_nouka(a: any): any
	/**
	* Unknown
	*/
	tryCreate_kyoushi(a: any): any
	/**
	* Unknown
	*/
	tryCreate_kajiya(a: any): any
	/**
	* Unknown
	*/
	tryCreate_shonin(a: any): any
	/**
	* Unknown
	*/
	tryCreate_yadoya(a: any): any
	/**
	* Unknown
	*/
	tryCreate_shinan(a: any): any
	/**
	* Unknown
	*/
	getTargetChara(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	isCreate(a: any, b: any): any
	/**
	* Unknown
	*/
	actEventFinish(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	isEventNow(a: any, b: any): any
	/**
	* Unknown
	*/
	initEvEmptyData(a: any, b: any): any
	/**
	* Unknown
	*/
	setEvData(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_first(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_finish(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_ryoriya_enemy_nigetaka(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_uniquequestbossgekiha(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_seishokusha_hakahenka(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_kyoushi_wana(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_kajiya_hakai(a: any, b: any): any
	/**
	* Unknown
	*/
	getQuestKeys(a: any): any
	/**
	* Unknown
	*/
	getAffectAnswerKey(a: any): any
	/**
	* Unknown
	*/
	addAffectNonBattleAnswers(a: any): any
	/**
	* Unknown
	*/
	selectedAnswer(a: any, b: any): any
	/**
	* Unknown
	*/
	gotoQuestMap(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	gotoQuestMap_kantei(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	gotoQuestMap_guild(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	gotoQuestMap_ryoriya(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	gotoQuestMap_mahouten(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	gotoQuestMap_sakaba(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	gotoQuestMap_seishokusha(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	gotoQuestMap_nouka(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	gotoQuestMap_kyoushi(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	gotoQuestMap_kajiya(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	gotoQuestMap_shonin(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	gotoQuestMap_yadoya(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	gotoQuestMap_shinan(a: any, b: any, c: any): any
}
