/**
 * tGameHikitsugi.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameHikitsugi
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	version: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	getHikitsugiData(a: any): any
	/**
	* Unknown
	*/
	setHikitsugiData(a: any): any
	/**
	* Unknown
	*/
	getStorage(): any
	/**
	* Unknown
	*/
	getSozaifukuro(): any
	/**
	* Unknown
	*/
	getShokuzaifukuro(): any
	/**
	* Unknown
	*/
	getRyourifukuro(): any
	/**
	* Unknown
	*/
	getActionSkills(a: any, b: any): any
	/**
	* Unknown
	*/
	getSkills(a: any): any
	/**
	* Unknown
	*/
	getGift(): any
	/**
	* Unknown
	*/
	getRecipe(): any
	/**
	* Unknown
	*/
	getMapEditor(): any
	/**
	* Unknown
	*/
	getItemRecord(): any
	/**
	* Unknown
	*/
	getMamonoRecord(): any
	/**
	* Unknown
	*/
	setWindow(a: any): any
	/**
	* Unknown
	*/
	save(a: any, b: any): any
	/**
	* Unknown
	*/
	load(a: any): any
}
