/**
 * tGameCriminalWindow.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameCriminalWindow
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	textMaxWidth: any
	/**
	* Unknown
	*/
	views: any
	/**
	* Unknown
	*/
	ccvs: any
	/**
	* Unknown
	*/
	cctx: any
	/**
	* Unknown
	*/
	fontSize: any
	/**
	* Unknown
	*/
	textSpace: any
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	viewCharaMaxNum: any
	/**
	* Unknown
	*/
	cursor: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	clear(): any
	/**
	* Unknown
	*/
	viewWindow(a: any, b: any): any
	/**
	* Unknown
	*/
	drawPage(a: any): any
	/**
	* Unknown
	*/
	getCursor(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_dispose(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_frame(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_draw(a: any): any
	/**
	* Unknown
	*/
	clearCanvas(): any
	/**
	* Unknown
	*/
	setCursor(a: any): any
	/**
	* Unknown
	*/
	viewInfoWindow(a: any): any
}
