/**
 * tGameRefresh.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameRefresh
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	tug: any
	/**
	* Unknown
	*/
	refreshCallBack: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	setCallBack(a: any): any
	/**
	* Unknown
	*/
	callAnimationFrame(): any
}
