/**
 * tGameHelp.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameHelp
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	data: any
	/**
	* Unknown
	*/
	itemlink: any
	/**
	* Unknown
	*/
	textMaxWidth: any
	/**
	* Unknown
	*/
	views: any
	/**
	* Unknown
	*/
	ccvs: any
	/**
	* Unknown
	*/
	cctx: any
	/**
	* Unknown
	*/
	hcvs: any
	/**
	* Unknown
	*/
	hctx: any
	/**
	* Unknown
	*/
	iframe: any
	/**
	* Unknown
	*/
	iframeOver: any
	/**
	* Unknown
	*/
	hpcvs: any
	/**
	* Unknown
	*/
	hpctx: any
	/**
	* Unknown
	*/
	fontSize: any
	/**
	* Unknown
	*/
	textSpace: any
	/**
	* Unknown
	*/
	viewDocumentData: any
	/**
	* Unknown
	*/
	viewItemMaxNum: any
	/**
	* Unknown
	*/
	cursor: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	viewHelp(a: any): any
	/**
	* Unknown
	*/
	viewCategoryWindow(a: any, b: any): any
	/**
	* Unknown
	*/
	viewCategoryItemWindow(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	viewSelectWindow(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	getCategories(): any
	/**
	* Unknown
	*/
	getCategoryItems(a: any): any
	/**
	* Unknown
	*/
	viewDocument(a: any, b: any): any
	/**
	* Unknown
	*/
	setMessage(): any
	/**
	* Unknown
	*/
	convertButtonLabel(): any
}
