/**
 * tGameSkillInfoWindow.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameSkillInfoWindow
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	cvs: any
	/**
	* Unknown
	*/
	ctx: any
	/**
	* Unknown
	*/
	fontSize: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	viewInfoWindow(a: any): any
}
