/**
 * tGameSkill.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameSkill
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	skillData: any
	/**
	* Unknown
	*/
	npcSkills: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	getExp(a: any, b: any): any
	/**
	* Unknown
	*/
	getLevelToExp(a: any, b: any, c: any): any
}
