/**
 * tGameCooking.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameCooking
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	cooking(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	cookingMember(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	selectFood(a: any): any
	/**
	* Unknown
	*/
	selectCmr(a: any): any
	/**
	* Unknown
	*/
	getSuccessRate(a: any, b: any): any
	/**
	* Unknown
	*/
	actCooking(): any
	/**
	* Unknown
	*/
	cookResult(a: any, b: any): any
	/**
	* Unknown
	*/
	getExp(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	selectNum(a: any): any
	/**
	* Unknown
	*/
	viewOutdoor(a: any): any
}
