/**
 * tGameTutorial.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameTutorial
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	talkData: any
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	hiddenCanvases: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	updateLock(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	confirmView(a: any): any
	/**
	* Unknown
	*/
	createMap(a: any): any
	/**
	* Unknown
	*/
	viewPage1(): any
	/**
	* Unknown
	*/
	viewPage2(): any
	/**
	* Unknown
	*/
	viewPage3(): any
	/**
	* Unknown
	*/
	viewPage4(): any
	/**
	* Unknown
	*/
	viewPage5(): any
	/**
	* Unknown
	*/
	viewPage6(): any
	/**
	* Unknown
	*/
	viewPage7(): any
	/**
	* Unknown
	*/
	viewPage8(): any
	/**
	* Unknown
	*/
	viewPage9(): any
	/**
	* Unknown
	*/
	oneActionFinishAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_p1move(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_tutorialp5gekiha(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_tutorialp6gekiha(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_tutorialp7gekiha(a: any, b: any): any
	/**
	* Unknown
	*/
	createCharactor(): any
	/**
	* Unknown
	*/
	affectCharactor(a: any): any
	/**
	* Unknown
	*/
	affectCharactor_p2(a: any, b: any): any
	/**
	* Unknown
	*/
	affectCharactor_p3(a: any, b: any): any
	/**
	* Unknown
	*/
	affectCharactor_p4(a: any, b: any): any
	/**
	* Unknown
	*/
	edgeActionCallBack(a: any): any
}
