/**
 * tGameShop.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameShop
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	checkNewItem(a: any, b: any): any
	/**
	* Unknown
	*/
	buy(a: any): any
	/**
	* Unknown
	*/
	sell(a: any): any
	/**
	* Unknown
	*/
	newItem(a: any): any
	/**
	* Unknown
	*/
	getLevelToStoreLevel(a: any, b: any): any
	/**
	* Unknown
	*/
	getStoreMaxLevel(a: any): any
	/**
	* Unknown
	*/
	isStoreLevelAnswer(a: any): any
	/**
	* Unknown
	*/
	getShopRankPlus(a: any): any
	/**
	* Unknown
	*/
	getRankUpPrice(a: any, b: any): any
	/**
	* Unknown
	*/
	shopLevelUp(a: any): any
	/**
	* Unknown
	*/
	getStoreScaleSpace(a: any): any
	/**
	* Unknown
	*/
	isStoreScaleAnswer(a: any): any
	/**
	* Unknown
	*/
	shopScaleUp(a: any): any
}
