/**
 * tGameWar.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameWar
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	data: any
	/**
	* Unknown
	*/
	fukidashi: any
	/**
	* Unknown
	*/
	myData: any
	/**
	* Unknown
	*/
	hiddenCanvases: any
	/**
	* Unknown
	*/
	objs: any
	/**
	* Unknown
	*/
	turnActionIdx: any
	/**
	* Unknown
	*/
	battleData: any
	/**
	* Unknown
	*/
	getSkillRates: any
	/**
	* Unknown
	*/
	buySkillRates: any
	/**
	* Unknown
	*/
	getSkillMax: any
	/**
	* Unknown
	*/
	cvs: any
	/**
	* Unknown
	*/
	ctx: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	initSaveData(): any
	/**
	* Unknown
	*/
	getSaveData(): any
	/**
	* Unknown
	*/
	setSaveData(a: any): any
	/**
	* Unknown
	*/
	initFrame(a: any): any
	/**
	* Unknown
	*/
	createMap(a: any): any
	/**
	* Unknown
	*/
	setObject(a: any, b: any): any
	/**
	* Unknown
	*/
	createUnits(a: any): any
	/**
	* Unknown
	*/
	createUnit(a: any): any
	/**
	* Unknown
	*/
	viewQuest(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	test(a: any): any
	/**
	* Unknown
	*/
	setSubFrameEvent(a: any): any
	/**
	* Unknown
	*/
	setSubFrameEvent_dispose(a: any): any
	/**
	* Unknown
	*/
	setSubFrameEvent_frame(a: any): any
	/**
	* Unknown
	*/
	setSubFrameEvent_draw(a: any): any
	/**
	* Unknown
	*/
	viewMessage(a: any): any
	/**
	* Unknown
	*/
	hiddenMessage(): any
	/**
	* Unknown
	*/
	action(a: any): any
	/**
	* Unknown
	*/
	getTekiTeamId(a: any): any
	/**
	* Unknown
	*/
	getTekiMembers(a: any): any
	/**
	* Unknown
	*/
	getTargetTeamMembers(a: any): any
	/**
	* Unknown
	*/
	getTargetTeamTypeMembers(a: any, b: any): any
	/**
	* Unknown
	*/
	getTargetTeamTairetsuMembers(a: any, b: any): any
	/**
	* Unknown
	*/
	getForwardMembers(a: any, b: any): any
	/**
	* Unknown
	*/
	getCharasArea(a: any): any
	/**
	* Unknown
	*/
	getTargetArea(a: any): any
	/**
	* Unknown
	*/
	action_dokugiri(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_setturnmessage(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_zenshin(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_zenshinforce(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_koutai(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_taiki(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_dokugiri(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	turnAction_shubi(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_shubiforce(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_kobu(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_odosu(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_kaihi(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_taiatari(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_hikiyose(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_jump(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_jump2(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_hikiyose2(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_oshidashi(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_kaifuku(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_zcchange(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_bomb(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_bomb2(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_kosan(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_turn(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_warteki(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_edgeMikataMae(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_edgeTekiMae(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_edgeMikataUshiro(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_edgeTekiUshiro(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_shikiup(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_shikiup2(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_meireiblock(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction_turnOshidashi(a: any, b: any): any
	/**
	* Unknown
	*/
	turnAction(a: any): any
	/**
	* Unknown
	*/
	createFukidashi(a: any): any
	/**
	* Unknown
	*/
	stopViewMessage(a: any): any
	/**
	* Unknown
	*/
	viewSelectSkillWindow(a: any): any
	/**
	* Unknown
	*/
	addTurnActions(a: any): any
	/**
	* Unknown
	*/
	clearMeireiStatus(a: any): any
	/**
	* Unknown
	*/
	tekiAct(a: any): any
	/**
	* Unknown
	*/
	updateShiki(): any
	/**
	* Unknown
	*/
	updateHP(): any
	/**
	* Unknown
	*/
	getCharaHP(a: any): any
	/**
	* Unknown
	*/
	getHP(): any
	/**
	* Unknown
	*/
	getFinish(): any
	/**
	* Unknown
	*/
	finishAction(): any
	/**
	* Unknown
	*/
	edgeMaeAct(a: any, b: any): any
	/**
	* Unknown
	*/
	addShiki(a: any, b: any): any
	/**
	* Unknown
	*/
	addMeireiBlock(a: any, b: any): any
	/**
	* Unknown
	*/
	back(a: any): any
	/**
	* Unknown
	*/
	setQuestData(a: any): any
	/**
	* Unknown
	*/
	isMeireiBlock(a: any): any
	/**
	* Unknown
	*/
	setBuySkillRates(): any
	/**
	* Unknown
	*/
	getBuySkillRateSkill(): any
	/**
	* Unknown
	*/
	setGetSkillRates(): any
	/**
	* Unknown
	*/
	getGetSkillRateSkill(): any
	/**
	* Unknown
	*/
	getNewSkill(a: any, b: any): any
	/**
	* Unknown
	*/
	setTeamStatus(a: any, b: any): any
	/**
	* Unknown
	*/
	getStatusTurn(a: any): any
	/**
	* Unknown
	*/
	getLastActionTurn(a: any): any
	/**
	* Unknown
	*/
	setLastActionTurn(a: any): any
	/**
	* Unknown
	*/
	checkLastActionTurn(a: any, b: any): any
	/**
	* Unknown
	*/
	checkWartekiAction(a: any, b: any): any
	/**
	* Unknown
	*/
	checkWartekiAction_zenshin(a: any): any
	/**
	* Unknown
	*/
	checkWartekiAction_koutai(a: any): any
	/**
	* Unknown
	*/
	checkWartekiAction_dokugiri(a: any): any
	/**
	* Unknown
	*/
	checkWartekiAction_shubi(a: any): any
	/**
	* Unknown
	*/
	checkWartekiAction_taiki(a: any): any
	/**
	* Unknown
	*/
	checkWartekiAction_kobu(a: any): any
	/**
	* Unknown
	*/
	checkWartekiAction_odosu(a: any): any
	/**
	* Unknown
	*/
	checkWartekiAction_shikiup(a: any): any
	/**
	* Unknown
	*/
	checkWartekiAction_shikiup2(a: any): any
	/**
	* Unknown
	*/
	checkWartekiAction_meireiblock(a: any): any
	/**
	* Unknown
	*/
	checkWartekiAction_zenshinforce(a: any): any
	/**
	* Unknown
	*/
	checkWartekiAction_shubiforce(a: any): any
	/**
	* Unknown
	*/
	checkWartekiAction_jump2(a: any): any
	/**
	* Unknown
	*/
	checkWartekiAction_bomb2(a: any): any
	/**
	* Unknown
	*/
	checkWartekiAction_hikiyose2(a: any): any
	/**
	* Unknown
	*/
	checkWartekiAction_oshidashi(a: any): any
	/**
	* Unknown
	*/
	checkWartekiAction_zcchange(a: any): any
	/**
	* Unknown
	*/
	checkWartekiAction_kaifuku(a: any): any
	/**
	* Unknown
	*/
	checkWartekiAction_common1(a: any): any
	/**
	* Unknown
	*/
	warskillkau(a: any, b: any): any
	/**
	* Unknown
	*/
	checkTurnOshidashi(a: any): any
}
