/**
 * tGameFarm.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameFarm
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	farmData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	loadFarm(a: any): any
	/**
	* Unknown
	*/
	createObject(a: any): any
	/**
	* Unknown
	*/
	checkGrow(a: any): any
	/**
	* Unknown
	*/
	getExp(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	updateWaterAll(a: any): any
	/**
	* Unknown
	*/
	updateFarmObjects(a: any, b: any): any
	/**
	* Unknown
	*/
	isWaterWeather(a: any): any
}
