/**
 * tGameSelectBgmWindow.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameSelectBgmWindow
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	getBgmItems(a: any): any
	/**
	* Unknown
	*/
	view(a: any): any
}
