/**
 * tGameRoutineMapMove.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameRoutineMapMove
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	isAction: any
	/**
	* Unknown
	*/
	callBack: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	move(a: any): any
	/**
	* Unknown
	*/
	setFrameAction(a: any): any
	/**
	* Unknown
	*/
	frameAction_dispose(a: any): any
	/**
	* Unknown
	*/
	frameAction_frame(a: any, b: any): any
	/**
	* Unknown
	*/
	frameAction_draw(a: any, b: any): any
}
