/**
 * tGameDialog.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameDialog
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	objs: any
	/**
	* Unknown
	*/
	initFlg: any
	/**
	* Unknown
	*/
	bg2CloseTimer: any
	/**
	* Unknown
	*/
	init(): any
	/**
	* Unknown
	*/
	setBg2CloseTimer(): any
	/**
	* Unknown
	*/
	setEvent(): any
	/**
	* Unknown
	*/
	isView(): any
	/**
	* Unknown
	*/
	view(a: any): any
	/**
	* Unknown
	*/
	close(): any
	/**
	* Unknown
	*/
	getMessageBoxFrame(): any
}
