/**
 * tGameName.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameName
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	nameData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	createCharactorName(a: any): any
	/**
	* Unknown
	*/
	createTownName(a: any): any
	/**
	* Unknown
	*/
	createSchoolName(): any
	/**
	* Unknown
	*/
	createCastleName(): any
	/**
	* Unknown
	*/
	createSlumName(): any
}
