/**
 * tGameTownGenerator.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameTownGenerator
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	townTypes: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	createTownWithLoad(a: any, b: any): any
	/**
	* Unknown
	*/
	createTown(a: any, b: any): any
	/**
	* Unknown
	*/
	actionPattern(a: any): any
	/**
	* Unknown
	*/
	updateActionPattern(a: any): any
	/**
	* Unknown
	*/
	actionPatternOne(a: any): any
	/**
	* Unknown
	*/
	setYukiObjects(a: any): any
}
