/**
 * tGameEffect.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameEffect
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	effectLink: any
	/**
	* Unknown
	*/
	effectData: any
	/**
	* Unknown
	*/
	canvases: any
	/**
	* Unknown
	*/
	effectTextPositionHistories: any
	/**
	* Unknown
	*/
	aY: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	addEffect(a: any): any
	/**
	* Unknown
	*/
	frameActionDraw(a: any): any
	/**
	* Unknown
	*/
	draw(a: any): any
	/**
	* Unknown
	*/
	drawEffectMap(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	effectSimple(a: any, b: any): any
	/**
	* Unknown
	*/
	effectBottomText(a: any, b: any): any
	/**
	* Unknown
	*/
	getEffectTextDelay(a: any): any
	/**
	* Unknown
	*/
	effectText(a: any, b: any): any
	/**
	* Unknown
	*/
	effectSmallText(a: any, b: any): any
	/**
	* Unknown
	*/
	viewMapName(a: any, b: any): any
	/**
	* Unknown
	*/
	clear(): any
	/**
	* Unknown
	*/
	effectDeath(a: any, b: any): any
	/**
	* Unknown
	*/
	effectVanish(a: any, b: any): any
	/**
	* Unknown
	*/
	effectUpObject(a: any, b: any): any
	/**
	* Unknown
	*/
	effectSimpleCut(a: any): any
	/**
	* Unknown
	*/
	effectLine(a: any, b: any): any
	/**
	* Unknown
	*/
	viewBigText(a: any, b: any): any
}
