/**
 * tGameSelectImageTarget.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameSelectImageTarget
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	cvs: any
	/**
	* Unknown
	*/
	ctx: any
	/**
	* Unknown
	*/
	cucvs: any
	/**
	* Unknown
	*/
	cuctx: any
	/**
	* Unknown
	*/
	cursor: any
	/**
	* Unknown
	*/
	margin: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	viewSelectTargetWindow(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	clear(): any
	/**
	* Unknown
	*/
	getOnePageData(a: any): any
	/**
	* Unknown
	*/
	getOneSize(a: any): any
	/**
	* Unknown
	*/
	drawPage(): any
	/**
	* Unknown
	*/
	setFrameEvent(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_dispose(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_frame(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_draw(a: any): any
	/**
	* Unknown
	*/
	changeTarget(a: any): any
	/**
	* Unknown
	*/
	drawCursor(): any
	/**
	* Unknown
	*/
	mousemoveEvent(a: any): any
	/**
	* Unknown
	*/
	mousedownEvent(a: any, b: any): any
}
