/**
 * tGameShukkabako.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameShukkabako
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	data: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initSaveData(): any
	/**
	* Unknown
	*/
	getSaveData(): any
	/**
	* Unknown
	*/
	setSaveData(a: any): any
	/**
	* Unknown
	*/
	createShukkabako(a: any): any
	/**
	* Unknown
	*/
	viewWindow(a: any): any
	/**
	* Unknown
	*/
	viewDefault(a: any, b: any): any
	/**
	* Unknown
	*/
	uru(a: any): any
	/**
	* Unknown
	*/
	addShopSeed(a: any): any
	/**
	* Unknown
	*/
	kau(a: any): any
	/**
	* Unknown
	*/
	hoju(): any
}
