/**
 * tGameNouchi.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameNouchi
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	getNouchiName(): any
	/**
	* Unknown
	*/
	getChipData(a: any): any
	/**
	* Unknown
	*/
	setNouchi(a: any, b: any): any
	/**
	* Unknown
	*/
	createNouchiWithLoad(a: any, b: any): any
	/**
	* Unknown
	*/
	moveNouchi(a: any): any
	/**
	* Unknown
	*/
	createNouchi(a: any, b: any): any
	/**
	* Unknown
	*/
	actionPattern(a: any): any
	/**
	* Unknown
	*/
	updateActionPattern(a: any): any
	/**
	* Unknown
	*/
	actionPatternOne(a: any): any
	/**
	* Unknown
	*/
	viewMenuWindow(a: any): any
	/**
	* Unknown
	*/
	checkUpdateMap(a: any): any
}
