/**
 * tGameBaby.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameBaby
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	data: any
	/**
	* Unknown
	*/
	range: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initSaveData(): any
	/**
	* Unknown
	*/
	getSaveData(): any
	/**
	* Unknown
	*/
	setSaveData(a: any): any
	/**
	* Unknown
	*/
	clearDatas(): any
	/**
	* Unknown
	*/
	createBaby(a: any, b: any): any
	/**
	* Unknown
	*/
	getTogetherCharas(): any
	/**
	* Unknown
	*/
	sleepTogether(a: any): any
	/**
	* Unknown
	*/
	seicho(a: any, b: any): any
	/**
	* Unknown
	*/
	setHikitsugiData(a: any, b: any): any
}
