/**
 * tGameSoubifukuro.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameSoubifukuro
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	max: any
	/**
	* Unknown
	*/
	nameMaxLength: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	getEquipList(): any
	/**
	* Unknown
	*/
	searchTargetEquipment(a: any): any
	/**
	* Unknown
	*/
	view(a: any, b: any): any
	/**
	* Unknown
	*/
	isEnableRegistEquips(): any
	/**
	* Unknown
	*/
	registEquips(a: any): any
	/**
	* Unknown
	*/
	soubihazusu(a: any): any
	/**
	* Unknown
	*/
	soubiyobidasu(a: any, b: any): any
	/**
	* Unknown
	*/
	getItemDescription(a: any, b: any): any
}
