/**
 * tGameEnsei.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameEnsei
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	nextUpdateTime: any
	/**
	* Unknown
	*/
	bokenshaMaxLevel: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	updateKouho(): any
	/**
	* Unknown
	*/
	convertItem(a: any): any
	/**
	* Unknown
	*/
	viewWindow(a: any): any
	/**
	* Unknown
	*/
	createEnseiField(a: any, b: any): any
	/**
	* Unknown
	*/
	createKyoten(a: any, b: any): any
	/**
	* Unknown
	*/
	createBoukensha(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	createDungeon(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	deleteEnseiData(): any
	/**
	* Unknown
	*/
	backToHome(a: any): any
	/**
	* Unknown
	*/
	enseiExit(a: any): any
}
