/**
 * tGameVersion.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameVersion
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	versions: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	checkEnableTargetSave(a: any): any
}
