/**
 * tGameIkesu.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameIkesu
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	data: any
	/**
	* Unknown
	*/
	maxNum: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initSaveData(): any
	/**
	* Unknown
	*/
	getSaveData(): any
	/**
	* Unknown
	*/
	setSaveData(a: any): any
	/**
	* Unknown
	*/
	getIkesuName(): any
	/**
	* Unknown
	*/
	getChipData(a: any): any
	/**
	* Unknown
	*/
	setIkesu(a: any, b: any): any
	/**
	* Unknown
	*/
	createIkesuWithLoad(a: any, b: any): any
	/**
	* Unknown
	*/
	moveIkesu(a: any): any
	/**
	* Unknown
	*/
	createIkesu(a: any, b: any): any
	/**
	* Unknown
	*/
	actionPattern(a: any): any
	/**
	* Unknown
	*/
	updateActionPattern(a: any): any
	/**
	* Unknown
	*/
	actionPatternOne(a: any): any
	/**
	* Unknown
	*/
	viewWindow(a: any): any
	/**
	* Unknown
	*/
	viewDefault(a: any, b: any): any
	/**
	* Unknown
	*/
	ireru(a: any): any
	/**
	* Unknown
	*/
	dasu(a: any): any
	/**
	* Unknown
	*/
	addItem(a: any, b: any): any
	/**
	* Unknown
	*/
	sortItems(): any
	/**
	* Unknown
	*/
	convertItem(a: any): any
	/**
	* Unknown
	*/
	seicho(): any
	/**
	* Unknown
	*/
	getAddNumRate(a: any): any
}
