/**
 * tGameText.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameText
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	colorData: any
	/**
	* Unknown
	*/
	cvs: any
	/**
	* Unknown
	*/
	ctx: any
	/**
	* Unknown
	*/
	cvs2: any
	/**
	* Unknown
	*/
	ctx2: any
	/**
	* Unknown
	*/
	textSpace: any
	/**
	* Unknown
	*/
	lineHeight: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	setFont(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	createTextSingleLine(a: any): any
	/**
	* Unknown
	*/
	createText(a: any): any
	/**
	* Unknown
	*/
	createText_en(a: any): any
	/**
	* Unknown
	*/
	createDamageText(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
}
