/**
 * tGameBgmResource.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameBgmResource
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	soundData: any
	/**
	* Unknown
	*/
	playSounds: any
	/**
	* Unknown
	*/
	oggOrM4a: any
	/**
	* Unknown
	*/
	fadeTime: any
	/**
	* Unknown
	*/
	fadeCount: any
	/**
	* Unknown
	*/
	caches: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	loadSound(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	getAudio(a: any): any
	/**
	* Unknown
	*/
	loadPreload(a: any): any
	/**
	* Unknown
	*/
	getPath(a: any): any
	/**
	* Unknown
	*/
	loadBuffer(a: any): any
	/**
	* Unknown
	*/
	stopSound(a: any): any
	/**
	* Unknown
	*/
	startSound(a: any): any
	/**
	* Unknown
	*/
	removeSound(a: any, b: any): any
	/**
	* Unknown
	*/
	insertPlay(a: any, b: any): any
	/**
	* Unknown
	*/
	insertPlay2(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	removeAllSound(a: any): any
	/**
	* Unknown
	*/
	play(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	setVolume(a: any): any
	/**
	* Unknown
	*/
	frameAction(a: any): any
	/**
	* Unknown
	*/
	reflectOption(a: any): any
	/**
	* Unknown
	*/
	overwriteBgm(a: any): any
}
