/**
 * tGameEtc.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameEtc
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	linkData: any
	/**
	* Unknown
	*/
	data: any
	/**
	* Unknown
	*/
	images: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initSaveData(): any
	/**
	* Unknown
	*/
	getSaveData(): any
	/**
	* Unknown
	*/
	setSaveData(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	loadAllImage(a: any): any
	/**
	* Unknown
	*/
	loadImage(a: any, b: any): any
}
