/**
 * tGameOnsen.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameOnsen
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	view(a: any, b: any): any
	/**
	* Unknown
	*/
	view2(a: any, b: any): any
	/**
	* Unknown
	*/
	hairu(a: any): any
	/**
	* Unknown
	*/
	kyoka(a: any, b: any): any
}
