/**
 * tGameSchoolGenerator.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameSchoolGenerator
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	createSchoolWithLoad(a: any, b: any): any
	/**
	* Unknown
	*/
	createSchool(a: any, b: any): any
	/**
	* Unknown
	*/
	actionPattern(a: any): any
	/**
	* Unknown
	*/
	updateActionPattern(a: any): any
	/**
	* Unknown
	*/
	actionPatternOne(a: any): any
	/**
	* Unknown
	*/
	setGaito(a: any): any
}
