/**
 * tGameSubTown.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameSubTown
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	max: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	getSubTownName(a: any): any
	/**
	* Unknown
	*/
	getChipData(a: any): any
	/**
	* Unknown
	*/
	setSubTown(a: any, b: any): any
	/**
	* Unknown
	*/
	createSubTownWithLoad(a: any, b: any): any
	/**
	* Unknown
	*/
	moveSubTown(a: any): any
	/**
	* Unknown
	*/
	createSubTown(a: any, b: any): any
	/**
	* Unknown
	*/
	actionPattern(a: any): any
	/**
	* Unknown
	*/
	updateActionPattern(a: any): any
	/**
	* Unknown
	*/
	actionPatternOne(a: any): any
	/**
	* Unknown
	*/
	viewMenuWindow(a: any): any
	/**
	* Unknown
	*/
	gotoSubTown(a: any, b: any): any
	/**
	* Unknown
	*/
	checkUpdateMap(a: any): any
	/**
	* Unknown
	*/
	affectCharactor(a: any): any
}
