/**
 * tGameEventAnimation.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameEventAnimation
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	animationData: any
	/**
	* Unknown
	*/
	moveSpeed: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	animation(a: any, b: any): any
	/**
	* Unknown
	*/
	convertAnimationData_chara(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_dispose(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_frame(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_draw(a: any): any
	/**
	* Unknown
	*/
	convertRouteToMove(a: any): any
}
