/**
 * tGameRecord.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameRecord
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	view(a: any, b: any): any
	/**
	* Unknown
	*/
	view_chara(a: any, b: any): any
	/**
	* Unknown
	*/
	view_item(a: any, b: any): any
	/**
	* Unknown
	*/
	view_hikyo(a: any, b: any): any
	/**
	* Unknown
	*/
	view_item2(a: any, b: any): any
}
