/**
 * tGameDesignedMap.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameDesignedMap
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	data: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	loadMapJs(a: any, b: any): any
	/**
	* Unknown
	*/
	addInitMaps(a: any, b: any): any
	/**
	* Unknown
	*/
	addTargetMap(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	addInitMaps_etc(a: any, b: any): any
	/**
	* Unknown
	*/
	getTargetChipsetPosition(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	autoCreateExpand(a: any, b: any, c: any, d: any): any
}
