/**
 * tGameTalkResource.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameTalkResource
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	talkData: any
	/**
	* Unknown
	*/
	talkDataCache: any
	/**
	* Unknown
	*/
	emptyMsg: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	getCharaPlayerRelationKey(a: any): any
	/**
	* Unknown
	*/
	convertTalk(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getChoiseMessage(a: any, b: any): any
	/**
	* Unknown
	*/
	getChoiseJoinTeamMessage(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	getChoiseRequestMyTownMessage(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	getChoiseRemoveTeamMessage(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	getChoiseQuestMessage(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	getChoiseQuestConfirmMessage(a: any, b: any): any
	/**
	* Unknown
	*/
	getChoiseQuestFinishMessage(a: any, b: any): any
	/**
	* Unknown
	*/
	getChoiseQuestFailureMessage(a: any, b: any): any
	/**
	* Unknown
	*/
	getChoiseNotItemMessage(a: any, b: any): any
	/**
	* Unknown
	*/
	getChoiseNohinItemMessage(a: any, b: any): any
	/**
	* Unknown
	*/
	getFukidashiMssage(a: any, b: any): any
	/**
	* Unknown
	*/
	getCommonFukidashiMssage(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getChoiseCondition(a: any, b: any): any
	/**
	* Unknown
	*/
	convertValue(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	loadEventTalk(a: any, b: any): any
	/**
	* Unknown
	*/
	getRescueChoiseMessage(a: any): any
	/**
	* Unknown
	*/
	getRescueSuccessChoiseMessage(a: any): any
	/**
	* Unknown
	*/
	getFreeChoiseMessage(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getFreeChoiseMessage2(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	getFreeChoiseMessage3(a: any, b: any, c: any, d: any, e: any): any
	/**
	* Unknown
	*/
	getFreeChoiseMessageList(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	viewKnockDownChoiseMessage(a: any, b: any): any
	/**
	* Unknown
	*/
	viewKnockDownCheerChoiseMessage(a: any, b: any): any
	/**
	* Unknown
	*/
	getQuest4SuccessChoiseMessage(a: any): any
	/**
	* Unknown
	*/
	getQuest4FailureChoiseMessage(a: any): any
	/**
	* Unknown
	*/
	getChoiseRequestRemoveMyTownMessage(a: any, b: any): any
	/**
	* Unknown
	*/
	getChoiseRequestRelationMessage(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	getCommonTalk(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getTalkMessage(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getAroundTalks(a: any): any
	/**
	* Unknown
	*/
	encodeMyTalkData(a: any): any
	/**
	* Unknown
	*/
	decodeMyTalkData(a: any): any
	/**
	* Unknown
	*/
	removeMyTlkDataToTalkData(a: any): any
	/**
	* Unknown
	*/
	setMyTlkDataToTalkData(a: any, b: any): any
	/**
	* Unknown
	*/
	loadMyTalkDataRange(a: any): any
	/**
	* Unknown
	*/
	loadMyTalkData(a: any): any
	/**
	* Unknown
	*/
	loadTargetMyTalkData(a: any, b: any): any
	/**
	* Unknown
	*/
	getTextTalkData(a: any, b: any): any
	/**
	* Unknown
	*/
	getTableTalkMessage(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	getSleepTogetherMessage(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	updateButtonKeyLabel(): any
}
