/**
 * tGameRoom.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameRoom
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	isSizeOver(a: any): any
	/**
	* Unknown
	*/
	wideRoad(a: any): any
	/**
	* Unknown
	*/
	createRoad(a: any): any
	/**
	* Unknown
	*/
	createRoomsMap(a: any): any
	/**
	* Unknown
	*/
	setObject(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_1(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_2(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_3(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_4(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_5(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_6(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_7(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_8(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_9(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_10(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_11(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_12(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_13(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_14(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_15(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_16(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_17(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_19(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_20(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_21(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_23(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_30(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_31(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_32(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_33(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_34(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_35(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_37(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_38(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_50(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_51(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_52(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_53(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_54(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_55(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_56(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_57(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon_58(a: any): any
	/**
	* Unknown
	*/
	getCreateRoomCon(a: any): any
	/**
	* Unknown
	*/
	createMap(a: any): any
	/**
	* Unknown
	*/
	copyObjectLinks(a: any): any
	/**
	* Unknown
	*/
	createCharactor(a: any): any
	/**
	* Unknown
	*/
	setOCharabject(a: any): any
	/**
	* Unknown
	*/
	createAnimals(a: any): any
	/**
	* Unknown
	*/
	setOutFloorSubs(a: any, b: any): any
	/**
	* Unknown
	*/
	getShops(): any
	/**
	* Unknown
	*/
	setRandomShopTypes(a: any, b: any): any
	/**
	* Unknown
	*/
	updateHmapTypes(a: any, b: any): any
	/**
	* Unknown
	*/
	setDimensionStorage(a: any, b: any): any
	/**
	* Unknown
	*/
	refillStorage(a: any): any
	/**
	* Unknown
	*/
	getRandomTargetData(a: any, b: any): any
	/**
	* Unknown
	*/
	convertCounterPos(a: any, b: any): any
	/**
	* Unknown
	*/
	getRandomKyotenRoom(): any
	/**
	* Unknown
	*/
	setAroundMap(a: any): any
	/**
	* Unknown
	*/
	getTownRandomPosition(a: any): any
	/**
	* Unknown
	*/
	setRoomBoroiMap(a: any): any
	/**
	* Unknown
	*/
	convertTatemonoKabe(a: any, b: any, c: any): any
}
