/**
 * tGameWindowResource.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameWindowResource
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	wcvs: any
	/**
	* Unknown
	*/
	wctx: any
	/**
	* Unknown
	*/
	windowData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	loadWindow(a: any): any
	/**
	* Unknown
	*/
	createWindowFrame(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	createPixelWindowFrame(a: any, b: any, c: any): any
}
