/**
 * tGameAdventurerGuildWindow.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameAdventurerGuildWindow
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	textMaxWidth: any
	/**
	* Unknown
	*/
	views: any
	/**
	* Unknown
	*/
	ccvs: any
	/**
	* Unknown
	*/
	cctx: any
	/**
	* Unknown
	*/
	fontSize: any
	/**
	* Unknown
	*/
	textSpace: any
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	viewQuestMaxNum: any
	/**
	* Unknown
	*/
	cursor: any
	/**
	* Unknown
	*/
	talkData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	clear(): any
	/**
	* Unknown
	*/
	viewWindow(a: any, b: any): any
	/**
	* Unknown
	*/
	drawPage(a: any): any
	/**
	* Unknown
	*/
	getCursor(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_dispose(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_frame(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_draw(a: any): any
	/**
	* Unknown
	*/
	clearCanvas(): any
	/**
	* Unknown
	*/
	setCursor(a: any): any
	/**
	* Unknown
	*/
	updateQuests(): any
	/**
	* Unknown
	*/
	viewInfoWindow(a: any): any
	/**
	* Unknown
	*/
	viewConfirm(a: any): any
	/**
	* Unknown
	*/
	checkFinish(a: any): any
	/**
	* Unknown
	*/
	getSuccessItem(a: any): any
	/**
	* Unknown
	*/
	addSuccessFaith(a: any, b: any): any
	/**
	* Unknown
	*/
	firstAccess(a: any, b: any): any
	/**
	* Unknown
	*/
	getGmChara(a: any): any
	/**
	* Unknown
	*/
	loadTalkData(a: any): any
	/**
	* Unknown
	*/
	firstGmAccess(a: any): any
	/**
	* Unknown
	*/
	gmNohin(a: any): any
	/**
	* Unknown
	*/
	inGuildMokutekichi(a: any, b: any): any
	/**
	* Unknown
	*/
	getQuestMessage(a: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_guildtargetitem(a: any, b: any): any
}
