/**
 * tGameShitaiasari.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameShitaiasari
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	tryCreate(a: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_shitaiasarifirst(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_shitaiasariinmap(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_shitaiasarichecktimeout(a: any, b: any): any
	/**
	* Unknown
	*/
	viewMap(a: any): any
	/**
	* Unknown
	*/
	deleteCharactor(): any
	/**
	* Unknown
	*/
	selectAnswer(a: any): any
	/**
	* Unknown
	*/
	affectAnswer(a: any): any
	/**
	* Unknown
	*/
	createTargetMap(): any
	/**
	* Unknown
	*/
	affectEnemyHone(a: any, b: any): any
	/**
	* Unknown
	*/
	timeoutEvent(a: any): any
}
