/**
 * tGameMeiro.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameMeiro
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	data: any
	/**
	* Unknown
	*/
	imgs: any
	/**
	* Unknown
	*/
	objs: any
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	size: any
	/**
	* Unknown
	*/
	chipsize: any
	/**
	* Unknown
	*/
	vcvs: any
	/**
	* Unknown
	*/
	vctx: any
	/**
	* Unknown
	*/
	isInit: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	tryMap(a: any): any
	/**
	* Unknown
	*/
	createMap(): any
	/**
	* Unknown
	*/
	affectDoor(a: any, b: any): any
	/**
	* Unknown
	*/
	affect(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	isHoshu(): any
	/**
	* Unknown
	*/
	hoshu(a: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_createmeiro(a: any, b: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	loadLinkJson(a: any): any
	/**
	* Unknown
	*/
	initFrame(a: any): any
	/**
	* Unknown
	*/
	view(a: any): any
	/**
	* Unknown
	*/
	clear(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_dispose(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_frame(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_draw(a: any): any
	/**
	* Unknown
	*/
	inputKey(): any
	/**
	* Unknown
	*/
	setStage(a: any): any
	/**
	* Unknown
	*/
	drawView(): any
	/**
	* Unknown
	*/
	draw3DMeiro(): any
	/**
	* Unknown
	*/
	getTargetPosition(a: any, b: any): any
	/**
	* Unknown
	*/
	drawBg(): any
	/**
	* Unknown
	*/
	drawMap(): any
	/**
	* Unknown
	*/
	actDeguchi(): any
	/**
	* Unknown
	*/
	actMenu(): any
}
