/**
 * tGameIcon24Resource.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameIcon24Resource
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	iconData: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	getIconData(a: any): any
}
