/**
 * tGameMenu.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameMenu
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	viewMenu(a: any, b: any): any
	/**
	* Unknown
	*/
	viewItem(a: any, b: any): any
	/**
	* Unknown
	*/
	viewEquipment(a: any, b: any): any
	/**
	* Unknown
	*/
	viewSkillAction(a: any, b: any): any
	/**
	* Unknown
	*/
	viewSkill(a: any, b: any): any
	/**
	* Unknown
	*/
	viewStatus(a: any, b: any): any
	/**
	* Unknown
	*/
	viewAllocateStatus(a: any): any
	/**
	* Unknown
	*/
	viewReceivedQuest(a: any): any
	/**
	* Unknown
	*/
	viewDairyQuest(a: any): any
	/**
	* Unknown
	*/
	viewOptionGroup(a: any, b: any): any
	/**
	* Unknown
	*/
	viewOption(a: any): any
	/**
	* Unknown
	*/
	viewOption2(a: any): any
	/**
	* Unknown
	*/
	viewOption3(a: any): any
	/**
	* Unknown
	*/
	viewMenuShortcut(a: any): any
	/**
	* Unknown
	*/
	viewGameOption(a: any): any
	/**
	* Unknown
	*/
	viewHelp(a: any): any
	/**
	* Unknown
	*/
	viewEditMyTown(a: any, b: any): any
	/**
	* Unknown
	*/
	viewEditSubTown(a: any, b: any): any
	/**
	* Unknown
	*/
	viewEditNouchi(a: any, b: any): any
	/**
	* Unknown
	*/
	viewEditMember(a: any, b: any): any
	/**
	* Unknown
	*/
	viewLog(a: any, b: any): any
	/**
	* Unknown
	*/
	viewSubInfo(a: any): any
}
