/**
 * tGameFishing.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameFishing
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	data: any
	/**
	* Unknown
	*/
	img: any
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	size: any
	/**
	* Unknown
	*/
	skillId: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	getSp(a: any, b: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	loadLinkJson(a: any): any
	/**
	* Unknown
	*/
	view(a: any): any
	/**
	* Unknown
	*/
	setFishData(): any
	/**
	* Unknown
	*/
	clear(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_dispose(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_frame(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_draw(a: any): any
	/**
	* Unknown
	*/
	addTime(a: any): any
	/**
	* Unknown
	*/
	getExp(a: any, b: any, c: any): any
}
