/**
 * tGameSleep.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameSleep
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	sleep(a: any, b: any): any
	/**
	* Unknown
	*/
	sleepInn(a: any, b: any): any
	/**
	* Unknown
	*/
	sleepAction(a: any, b: any, c: any, d: any): any
	/**
	* Unknown
	*/
	getTogetherCharas(): any
	/**
	* Unknown
	*/
	sleepTogether(a: any, b: any): any
	/**
	* Unknown
	*/
	getSleepTime(a: any, b: any): any
	/**
	* Unknown
	*/
	sleepSave(a: any): any
}
