/**
 * tGameMaigo.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameMaigo
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	tryCreate(a: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_maigofirst(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_maigoevent1(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_maigoevent2(a: any, b: any): any
	/**
	* Unknown
	*/
	oneActionFinishAction_maigobossgekiha(a: any, b: any): any
	/**
	* Unknown
	*/
	viewMap(a: any): any
	/**
	* Unknown
	*/
	deleteMaigoCharactor(): any
	/**
	* Unknown
	*/
	affectAnswer(a: any): any
	/**
	* Unknown
	*/
	calBasho(): any
	/**
	* Unknown
	*/
	affectObject(a: any): any
	/**
	* Unknown
	*/
	inTargetMap(a: any, b: any, c: any): any
	/**
	* Unknown
	*/
	createTargetMap(a: any, b: any): any
	/**
	* Unknown
	*/
	errorFix(a: any, b: any): any
	/**
	* Unknown
	*/
	setTargetEvent1(a: any, b: any): any
	/**
	* Unknown
	*/
	setTargetEvent2(a: any, b: any): any
}
