/**
 * tGameSlot.ts
 * Autogenerated by WaahTool v2.1.1 >:3
 */

import { tGameMain } from "./tGameMain"
export interface tGameSlot
{
	/**
	* Unknown
	*/
	parent: tGameMain
	/**
	* Unknown
	*/
	data: any
	/**
	* Unknown
	*/
	img: any
	/**
	* Unknown
	*/
	objs: any
	/**
	* Unknown
	*/
	viewData: any
	/**
	* Unknown
	*/
	reelNum: any
	/**
	* Unknown
	*/
	reels: any
	/**
	* Unknown
	*/
	init(a: any): any
	/**
	* Unknown
	*/
	getPlayerCoin(): any
	/**
	* Unknown
	*/
	initFrame(a: any): any
	/**
	* Unknown
	*/
	initLoad(a: any): any
	/**
	* Unknown
	*/
	loadLinkJson(a: any): any
	/**
	* Unknown
	*/
	updateMymoney(): any
	/**
	* Unknown
	*/
	getMatchLines(a: any): any
	/**
	* Unknown
	*/
	view(a: any): any
	/**
	* Unknown
	*/
	clear(): any
	/**
	* Unknown
	*/
	startGame(): any
	/**
	* Unknown
	*/
	finishGame(): any
	/**
	* Unknown
	*/
	choseiBet(): any
	/**
	* Unknown
	*/
	animationGetCoin(a: any): any
	/**
	* Unknown
	*/
	hit(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_dispose(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_frame(a: any): any
	/**
	* Unknown
	*/
	setFrameEvent_draw(a: any): any
	/**
	* Unknown
	*/
	drawBet(): any
	/**
	* Unknown
	*/
	drawGaming(): any
}
